/* DefineExamDate */
export const GET_DEFINE_EXAM_DATES = "GET_DEFINE_EXAM_DATES";
export const GET_DEFINE_EXAM_DATES_SUCCESS = "GET_DEFINE_EXAM_DATES_SUCCESS";
export const GET_DEFINE_EXAM_DATES_FAIL = "GET_DEFINE_EXAM_DATES_FAIL";

/* DefineExamDate */
export const GET_DEFINE_EXAM_DATE_DELETED_VALUE =
  "GET_DEFINE_EXAM_DATE_DELETED_VALUE";
export const GET_DEFINE_EXAM_DATE_DELETED_VALUE_SUCCESS =
  "GET_DEFINE_EXAM_DATE_DELETED_VALUE_SUCCESS";
export const GET_DEFINE_EXAM_DATE_DELETED_VALUE_FAIL =
  "GET_DEFINE_EXAM_DATE_DELETED_VALUE_FAIL";

export const ADD_NEW_DEFINE_EXAM_DATE = "ADD_NEW_DEFINE_EXAM_DATE";
export const ADD_DEFINE_EXAM_DATE_SUCCESS = "ADD_DEFINE_EXAM_DATE_SUCCESS";
export const ADD_DEFINE_EXAM_DATE_FAIL = "ADD_DEFINE_EXAM_DATE_FAIL";

export const UPDATE_DEFINE_EXAM_DATE = "UPDATE_DEFINE_EXAM_DATE";
export const UPDATE_DEFINE_EXAM_DATE_SUCCESS =
  "UPDATE_DEFINE_EXAM_DATE_SUCCESS";
export const UPDATE_DEFINE_EXAM_DATE_FAIL = "UPDATE_DEFINE_EXAM_DATE_FAIL";

export const DELETE_DEFINE_EXAM_DATE = "DELETE_DEFINE_EXAM_DATE";
export const DELETE_DEFINE_EXAM_DATE_SUCCESS =
  "DELETE_DEFINE_EXAM_DATE_SUCCESS";
export const DELETE_DEFINE_EXAM_DATE_FAIL = "DELETE_DEFINE_EXAM_DATE_FAIL";

//students order
export const GET_STUDENTS_ORDER = "GET_STUDENTS_ORDER";
export const GET_STUDENTS_ORDER_SUCCESS = "GET_STUDENTS_ORDER_SUCCESS";
export const GET_STUDENTS_ORDER_FAIL = "GET_STUDENTS_ORDER_FAIL";
