/* EXAM_OBSERVERS */
export const GET_EXAM_OBSERVERS = "GET_EXAM_OBSERVERS";
export const GET_EXAM_OBSERVERS_SUCCESS = "GET_EXAM_OBSERVERS_SUCCESS";
export const GET_EXAM_OBSERVERS_FAIL = "GET_EXAM_OBSERVERS_FAIL";

/* EXAM_OBSERVERS PROFILE*/
export const GET_EXAM_OBSERVER_PROFILE = "GET_EXAM_OBSERVER_PROFILE";
export const GET_EXAM_OBSERVER_PROFILE_SUCCESS =
  "GET_EXAM_OBSERVER_PROFILE_SUCCESS";
export const GET_EXAM_OBSERVER_PROFILE_FAIL = "GET_EXAM_OBSERVER_PROFILE_FAIL";

export const ADD_NEW_EXAM_OBSERVER = "ADD_NEW_EXAM_OBSERVER";
export const ADD_EXAM_OBSERVER_SUCCESS = "ADD_EXAM_OBSERVER_SUCCESS";
export const ADD_EXAM_OBSERVER_FAIL = "ADD_EXAM_OBSERVER_FAIL";

export const UPDATE_EXAM_OBSERVER = "UPDATE_EXAM_OBSERVER";
export const UPDATE_EXAM_OBSERVER_SUCCESS = "UPDATE_EXAM_OBSERVER_SUCCESS";
export const UPDATE_EXAM_OBSERVER_FAIL = "UPDATE_EXAM_OBSERVER_FAIL";

export const DELETE_EXAM_OBSERVER = "DELETE_EXAM_OBSERVER";
export const DELETE_EXAM_OBSERVER_SUCCESS = "DELETE_EXAM_OBSERVER_SUCCESS";
export const DELETE_EXAM_OBSERVER_FAIL = "DELETE_EXAM_OBSERVER_FAIL";
