/* DISMISS_DECREES_EXAM */
export const GET_DISMISS_DECREES_EXAM = " GET_DISMISS_DECREES_EXAM";
export const GET_DISMISS_DECREES_EXAM_SUCCESS =
  " GET_DISMISS_DECREES_EXAM_SUCCESS";
export const GET_DISMISS_DECREES_EXAM_FAIL = " GET_DISMISS_DECREES_EXAM_FAIL";

/* DISMISS_DECREE_EXAMS PROFILE */
export const GET_DISMISS_DECREE_EXAM_DELETED_VALUE =
  " GET_DISMISS_DECREE_EXAM_DELETED_VALUE";
export const GET_DISMISS_DECREE_EXAM_DELETED_VALUE_SUCCESS =
  " GET_DISMISS_DECREE_EXAM_DELETED_VALUE_SUCCESS";
export const GET_DISMISS_DECREE_EXAM_DELETED_VALUE_FAIL =
  " GET_DISMISS_DECREE_EXAM_DELETED_VALUE_FAIL";

export const ADD_NEW_DISMISS_DECREE_EXAM = "ADD_NEW_DISMISS_DECREE_EXAM";
export const ADD_DISMISS_DECREE_EXAM_SUCCESS =
  "ADD_DISMISS_DECREE_EXAM_SUCCESS";
export const ADD_DISMISS_DECREE_EXAM_FAIL = "ADD_DISMISS_DECREE_EXAM_FAIL";

export const UPDATE_DISMISS_DECREE_EXAM = "UPDATE_DISMISS_DECREE_EXAM";
export const UPDATE_DISMISS_DECREE_EXAM_SUCCESS =
  "UPDATE_DISMISS_DECREE_EXAM_SUCCESS";
export const UPDATE_DISMISS_DECREE_EXAM_FAIL =
  "UPDATE_DISMISS_DECREE_EXAM_FAIL";

export const DELETE_DISMISS_DECREE_EXAM = "DELETE_DISMISS_DECREE_EXAM";
export const DELETE_DISMISS_DECREE_EXAM_SUCCESS =
  "DELETE_DISMISS_DECREE_EXAM_SUCCESS";
export const DELETE_DISMISS_DECREE_EXAM_FAIL =
  "DELETE_DISMISS_DECREE_EXAM_FAIL";
