/* COURSES_REGISTRATIONS */
export const GET_COURSES_REGISTRATIONS = "GET_COURSES_REGISTRATIONS"
export const GET_COURSES_REGISTRATIONS_SUCCESS = "GET_COURSES_REGISTRATIONS_SUCCESS"
export const GET_COURSES_REGISTRATIONS_FAIL = "GET_COURSES_REGISTRATIONS_FAIL"

/* COURSES_REGISTRATIONS PROFILE*/
export const GET_STUDENT_REGISTER_INFO = "GET_STUDENT_REGISTER_INFO"
export const GET_STUDENT_REGISTER_INFO_SUCCESS = "GET_STUDENT_REGISTER_INFO_SUCCESS"
export const GET_STUDENT_REGISTER_INFO_FAIL = "GET_STUDENT_REGISTER_INFO_FAIL"

export const ADD_NEW_COURSES_REGISTRATION = "ADD_NEW_COURSES_REGISTRATION"
export const ADD_COURSES_REGISTRATION_SUCCESS = "ADD_COURSES_REGISTRATION_SUCCESS"
export const ADD_COURSES_REGISTRATION_FAIL = "ADD_COURSES_REGISTRATION_FAIL"

export const UPDATE_COURSES_REGISTRATION = "UPDATE_COURSES_REGISTRATION"
export const UPDATE_COURSES_REGISTRATION_SUCCESS = "UPDATE_COURSES_REGISTRATION_SUCCESS"
export const UPDATE_COURSES_REGISTRATION_FAIL = "UPDATE_COURSES_REGISTRATION_FAIL"

export const DELETE_COURSES_REGISTRATION = "DELETE_COURSES_REGISTRATION"
export const DELETE_COURSES_REGISTRATION_SUCCESS = "DELETE_COURSES_REGISTRATION_SUCCESS"
export const DELETE_COURSES_REGISTRATION_FAIL = "DELETE_COURSES_REGISTRATION_FAIL"


/* AVAILABLE_COURSES */
export const GET_AVAILABLE_COURSES = "GET_AVAILABLE_COURSES"
export const GET_AVAILABLE_COURSES_SUCCESS = "GET_AVAILABLE_COURSES_SUCCESS"
export const GET_AVAILABLE_COURSES_FAIL = "GET_AVAILABLE_COURSES_FAIL"


export const ADD_NEW_AVAILABLE_COURSE = "ADD_NEW_AVAILABLE_COURSE"
export const ADD_AVAILABLE_COURSE_SUCCESS = "ADD_AVAILABLE_COURSE_SUCCESS"
export const ADD_AVAILABLE_COURSE_FAIL = "ADD_AVAILABLE_COURSE_FAIL"

/* NON_ACTIVE_STD_CURRS*/
export const GET_NON_ACTIVE_STD_CURRS = "GET_NON_ACTIVE_STD_CURRS"
export const GET_NON_ACTIVE_STD_CURRS_SUCCESS = "GET_NON_ACTIVE_STD_CURRS_SUCCESS"
export const GET_NON_ACTIVE_STD_CURRS_FAIL = "GET_NON_ACTIVE_STD_CURRS_FAIL"

export const UPDATE_NON_ACTIVE_STD_CURR = "UPDATE_NON_ACTIVE_STD_CURR"
export const UPDATE_NON_ACTIVE_STD_CURR_SUCCESS = "UPDATE_NON_ACTIVE_STD_CURR_SUCCESS"
export const UPDATE_NON_ACTIVE_STD_CURR_FAIL = "UPDATE_NON_ACTIVE_STD_CURR_FAIL"

export const DELETE_NON_ACTIVE_STD_CURR = "DELETE_NON_ACTIVE_STD_CURR"
export const DELETE_NON_ACTIVE_STD_CURR_SUCCESS = "DELETE_NON_ACTIVE_STD_CURR_SUCCESS"
export const DELETE_NON_ACTIVE_STD_CURR_FAIL = "DELETE_NON_ACTIVE_STD_CURR_FAIL"


/* TEMP_STD_SCHEDULES */
export const GET_TEMP_STD_SCHEDULES = "GET_TEMP_STD_SCHEDULES"
export const GET_TEMP_STD_SCHEDULES_SUCCESS = "GET_TEMP_STD_SCHEDULES_SUCCESS"
export const GET_TEMP_STD_SCHEDULES_FAIL = "GET_TEMP_STD_SCHEDULES_FAIL"


export const DELETE_ALL_NON_ACTIVE_STD_CURR = "DELETE_ALL_NON_ACTIVE_STD_CURR"
export const DELETE_ALL_NON_ACTIVE_STD_CURR_SUCCESS = "DELETE_ALL_NON_ACTIVE_STD_CURR_SUCCESS"
export const DELETE_ALL_NON_ACTIVE_STD_CURR_FAIL = "DELETE_ALL_NON_ACTIVE_STD_CURR_FAIL"

export const SAVE_ALL_NON_ACTIVE_STD_CURR = "SAVE_ALL_NON_ACTIVE_STD_CURR"
export const SAVE_ALL_NON_ACTIVE_STD_CURR_SUCCESS = "SAVE_ALL_NON_ACTIVE_STD_CURR_SUCCESS"
export const SAVE_ALL_NON_ACTIVE_STD_CURR_FAIL = "SAVE_ALL_NON_ACTIVE_STD_CURR_FAIL"


/* ACHIEVED_COURSES */
export const GET_ACHIEVED_COURSES = "GET_ACHIEVED_COURSES"
export const GET_ACHIEVED_COURSES_SUCCESS = "GET_ACHIEVED_COURSES_SUCCESS"
export const GET_ACHIEVED_COURSES_FAIL = "GET_ACHIEVED_COURSES_FAIL"