/* ESTIMATES */
export const GET_ESTIMATES = "GET_ESTIMATES"
export const GET_ESTIMATES_SUCCESS = "GET_ESTIMATES_SUCCESS"
export const GET_ESTIMATES_FAIL = "GET_ESTIMATES_FAIL"

/* ESTIMATE PROFILE */
export const GET_ESTIMATE_DELETED_VALUE = "GET_ESTIMATE_DELETED_VALUE"
export const GET_ESTIMATE_DELETED_VALUE_SUCCESS = "GET_ESTIMATE_DELETED_VALUE_SUCCESS"
export const GET_ESTIMATE_DELETED_VALUE_FAIL = "GET_ESTIMATE_DELETED_VALUE_FAIL"

export const ADD_NEW_ESTIMATE = "ADD_NEW_ESTIMATE"
export const ADD_ESTIMATE_SUCCESS = "ADD_ESTIMATE_SUCCESS"
export const ADD_ESTIMATE_FAIL = "ADD_ESTIMATE_FAIL"

export const UPDATE_ESTIMATE = "UPDATE_ESTIMATE"
export const UPDATE_ESTIMATE_SUCCESS = "UPDATE_ESTIMATE_SUCCESS"
export const UPDATE_ESTIMATE_FAIL = "UPDATE_ESTIMATE_FAIL"

export const DELETE_ESTIMATE = "DELETE_ESTIMATE"
export const DELETE_ESTIMATE_SUCCESS = "DELETE_ESTIMATE_SUCCESS"
export const DELETE_ESTIMATE_FAIL = "DELETE_ESTIMATE_FAIL"