/* TIMELINES */
export const GET_TIMELINES = "GET_TIMELINES";
export const GET_TIMELINES_SUCCESS = "GET_TIMELINES_SUCCESS";
export const GET_TIMELINES_FAIL = "GET_TIMELINES_FAIL";

/* TIMELINE PROFILE */
export const GET_TIMELINE_DELETED_VALUE = "GET_TIMELINE_DELETED_VALUE";
export const GET_TIMELINE_DELETED_VALUE_SUCCESS =
  "GET_TIMELINE_DELETED_VALUE_SUCCESS";
export const GET_TIMELINE_DELETED_VALUE_FAIL =
  "GET_TIMELINE_DELETED_VALUE_FAIL";

export const ADD_NEW_TIMELINE = "ADD_NEW_TIMELINE";
export const ADD_TIMELINE_SUCCESS = "ADD_TIMELINE_SUCCESS";
export const ADD_TIMELINE_FAIL = "ADD_TIMELINE_FAIL";

export const UPDATE_TIMELINE = "UPDATE_TIMELINE";
export const UPDATE_TIMELINE_SUCCESS = "UPDATE_TIMELINE_SUCCESS";
export const UPDATE_TIMELINE_FAIL = "UPDATE_TIMELINE_FAIL";

export const DELETE_TIMELINE = "DELETE_TIMELINE";
export const DELETE_TIMELINE_SUCCESS = "DELETE_TIMELINE_SUCCESS";
export const DELETE_TIMELINE_FAIL = "DELETE_TIMELINE_FAIL";

export const GET_REQUEST_PERIOD_ALLOWANCE = "GET_REQUEST_PERIOD_ALLOWANCE";
export const GET_REQUEST_PERIOD_ALLOWANCE_SUCCESS =
  "GET_REQUEST_PERIOD_ALLOWANCE_SUCCESS";
export const GET_REQUEST_PERIOD_ALLOWANCE_FAIL =
  "GET_REQUEST_PERIOD_ALLOWANCE_FAIL";

export const GET_REQUEST_PERIOD_ALLOWANCE_TIME =
  "GET_REQUEST_PERIOD_ALLOWANCE_TIME";
export const GET_REQUEST_PERIOD_ALLOWANCE_TIME_SUCCESS =
  "GET_REQUEST_PERIOD_ALLOWANCE_TIME_SUCCESS";
export const GET_REQUEST_PERIOD_ALLOWANCE_TIME_FAIL =
  "GET_REQUEST_PERIOD_ALLOWANCE_TIME_FAIL";

export const UPDATE_REQUEST_PERIOD_ALLOWANCE_TIME =
  "UPDATE_REQUEST_PERIOD_ALLOWANCE_TIME";
export const UPDATE_REQUEST_PERIOD_ALLOWANCE_TIME_SUCCESS =
  "UPDATE_REQUEST_PERIOD_ALLOWANCE_TIME_SUCCESS";
export const UPDATE_REQUEST_PERIOD_ALLOWANCE_TIME_FAIL =
  "UPDATE_REQUEST_PERIOD_ALLOWANCE_TIME_FAIL";

export const GENERALIZE_REQUEST_PERIOD_ALLOWANCE_TIME =
  "GENERALIZE_REQUEST_PERIOD_ALLOWANCE_TIME";
export const GENERALIZE_REQUEST_PERIOD_ALLOWANCE_TIME_SUCCESS =
  "GENERALIZE_REQUEST_PERIOD_ALLOWANCE_TIME_SUCCESS";
export const GENERALIZE_REQUEST_PERIOD_ALLOWANCE_TIME_FAIL =
  "GENERALIZE_REQUEST_PERIOD_ALLOWANCE_TIME_FAIL";

export const GET_REQUEST_PERIOD_PERMISSION = "GET_REQUEST_PERIOD_PERMISSION";
export const GET_REQUEST_PERIOD_PERMISSION_SUCCESS =
  "GET_REQUEST_PERIOD_PERMISSION_SUCCESS";
export const GET_REQUEST_PERIOD_PERMISSION_FAIL =
  "GET_REQUEST_PERIOD_PERMISSION_FAIL";

export const ADD_REQUEST_PERIOD_PERMISSION = "ADD_REQUEST_PERIOD_PERMISSION";
export const ADD_REQUEST_PERIOD_PERMISSION_SUCCESS =
  "ADD_REQUEST_PERIOD_PERMISSION_SUCCESS";
export const ADD_REQUEST_PERIOD_PERMISSION_FAIL =
  "ADD_REQUEST_PERIOD_PERMISSION_FAIL";

export const UPDATE_REQUEST_PERIOD_PERMISSION =
  "UPDATE_REQUEST_PERIOD_PERMISSION";
export const UPDATE_REQUEST_PERIOD_PERMISSION_SUCCESS =
  "UPDATE_REQUEST_PERIOD_PERMISSION_SUCCESS";
export const UPDATE_REQUEST_PERIOD_PERMISSION_FAIL =
  "UPDATE_REQUEST_PERIOD_PERMISSION_FAIL";

export const DELETE_REQUEST_PERIOD_PERMISSION =
  "DELETE_REQUEST_PERIOD_PERMISSION";
export const DELETE_REQUEST_PERIOD_PERMISSION_SUCCESS =
  "DELETE_REQUEST_PERIOD_PERMISSION_SUCCESS";
export const DELETE_REQUEST_PERIOD_PERMISSION_FAIL =
  "DELETE_REQUEST_PERIOD_PERMISSION_FAIL";
