/* SCHEDULES */
export const GET_SCHEDULES = "GET_SCHEDULES"
export const GET_SCHEDULES_SUCCESS = "GET_SCHEDULES_SUCCESS"
export const GET_SCHEDULES_FAIL = "GET_SCHEDULES_FAIL"

/* SCHEDULE PROFILE */
export const GET_SCHEDULE_PROFILE = "GET_SCHEDULE_PROFILE"
export const GET_SCHEDULE_PROFILE_SUCCESS = "GET_SCHEDULE_PROFILE_SUCCESS"
export const GET_SCHEDULE_PROFILE_FAIL = "GET_SCHEDULE_PROFILE_FAIL"

export const ADD_NEW_SCHEDULE = "ADD_NEW_SCHEDULE"
export const ADD_SCHEDULE_SUCCESS = "ADD_SCHEDULE_SUCCESS"
export const ADD_SCHEDULE_FAIL = "ADD_SCHEDULE_FAIL"

export const UPDATE_SCHEDULE = "UPDATE_SCHEDULE"
export const UPDATE_SCHEDULE_SUCCESS = "UPDATE_SCHEDULE_SUCCESS"
export const UPDATE_SCHEDULE_FAIL = "UPDATE_SCHEDULE_FAIL"

export const DELETE_SCHEDULE = "DELETE_SCHEDULE"
export const DELETE_SCHEDULE_SUCCESS = "DELETE_SCHEDULE_SUCCESS"
export const DELETE_SCHEDULE_FAIL = "DELETE_SCHEDULE_FAIL"