/* ORAL_WARNING_DECREES */
export const GET_ORAL_WARNING_DECREES = " GET_ORAL_WARNING_DECREES";
export const GET_ORAL_WARNING_DECREES_SUCCESS =
  " GET_ORAL_WARNING_DECREES_SUCCESS";
export const GET_ORAL_WARNING_DECREES_FAIL = " GET_ORAL_WARNING_DECREES_FAIL";

/* ORAL_WARNING_DECREES PROFILE */
export const GET_ORAL_WARNING_DECREE_DELETED_VALUE =
  " GET_ORAL_WARNING_DECREE_DELETED_VALUE";
export const GET_ORAL_WARNING_DECREE_DELETED_VALUE_SUCCESS =
  " GET_ORAL_WARNING_DECREE_DELETED_VALUE_SUCCESS";
export const GET_ORAL_WARNING_DECREE_DELETED_VALUE_FAIL =
  " GET_ORAL_WARNING_DECREE_DELETED_VALUE_FAIL";

export const ADD_NEW_ORAL_WARNING_DECREE = "ADD_NEW_ORAL_WARNING_DECREE";
export const ADD_ORAL_WARNING_DECREE_SUCCESS =
  "ADD_ORAL_WARNING_DECREE_SUCCESS";
export const ADD_ORAL_WARNING_DECREE_FAIL = "ADD_ORAL_WARNING_DECREE_FAIL";

export const UPDATE_ORAL_WARNING_DECREE = "UPDATE_ORAL_WARNING_DECREE";
export const UPDATE_ORAL_WARNING_DECREE_SUCCESS =
  "UPDATE_ORAL_WARNING_DECREE_SUCCESS";
export const UPDATE_ORAL_WARNING_DECREE_FAIL =
  "UPDATE_ORAL_WARNING_DECREE_FAIL";

export const DELETE_ORAL_WARNING_DECREE = "DELETE_ORAL_WARNING_DECREE";
export const DELETE_ORAL_WARNING_DECREE_SUCCESS =
  "DELETE_ORAL_WARNING_DECREE_SUCCESS";
export const DELETE_ORAL_WARNING_DECREE_FAIL =
  "DELETE_ORAL_WARNING_DECREE_FAIL";
