/* DISMISS_DECREES_OTHER */
export const GET_DISMISS_DECREES_OTHER = " GET_DISMISS_DECREES_OTHER";
export const GET_DISMISS_DECREES_OTHER_SUCCESS =
  " GET_DISMISS_DECREES_OTHER_SUCCESS";
export const GET_DISMISS_DECREES_OTHER_FAIL = " GET_DISMISS_DECREES_OTHER_FAIL";

/* DISMISS_DECREE_OTHERS PROFILE */
export const GET_DISMISS_DECREE_OTHER_DELETED_VALUE =
  " GET_DISMISS_DECREE_OTHER_DELETED_VALUE";
export const GET_DISMISS_DECREE_OTHER_DELETED_VALUE_SUCCESS =
  " GET_DISMISS_DECREE_OTHER_DELETED_VALUE_SUCCESS";
export const GET_DISMISS_DECREE_OTHER_DELETED_VALUE_FAIL =
  " GET_DISMISS_DECREE_OTHER_DELETED_VALUE_FAIL";

export const ADD_NEW_DISMISS_DECREE_OTHER = "ADD_NEW_DISMISS_DECREE_OTHER";
export const ADD_DISMISS_DECREE_OTHER_SUCCESS =
  "ADD_DISMISS_DECREE_OTHER_SUCCESS";
export const ADD_DISMISS_DECREE_OTHER_FAIL = "ADD_DISMISS_DECREE_OTHER_FAIL";

export const UPDATE_DISMISS_DECREE_OTHER = "UPDATE_DISMISS_DECREE_OTHER";
export const UPDATE_DISMISS_DECREE_OTHER_SUCCESS =
  "UPDATE_DISMISS_DECREE_OTHER_SUCCESS";
export const UPDATE_DISMISS_DECREE_OTHER_FAIL =
  "UPDATE_DISMISS_DECREE_OTHER_FAIL";

export const DELETE_DISMISS_DECREE_OTHER = "DELETE_DISMISS_DECREE_OTHER";
export const DELETE_DISMISS_DECREE_OTHER_SUCCESS =
  "DELETE_DISMISS_DECREE_OTHER_SUCCESS";
export const DELETE_DISMISS_DECREE_OTHER_FAIL =
  "DELETE_DISMISS_DECREE_OTHER_FAIL";
