/* warining */
export const GET_TRAINING_MEMBERS = "GET_TRAINING_MEMBERS"
export const GET_TRAINING_MEMBERS_SUCCESS = "GET_TRAINING_MEMBERS_SUCCESS"
export const GET_TRAINING_MEMBERS_FAIL = "GET_TRAINING_MEMBERS_FAIL"

export const ADD_NEW_TRAINING_MEMBER = "ADD_NEW_TRAINING_MEMBER"
export const ADD_TRAINING_MEMBER_SUCCESS = "ADD_TRAINING_MEMBER_SUCCESS"
export const ADD_TRAINING_MEMBER_FAIL = "ADD_TRAINING_MEMBER_FAIL"

export const UPDATE_TRAINING_MEMBER = "UPDATE_TRAINING_MEMBER"
export const UPDATE_TRAINING_MEMBER_SUCCESS = "UPDATE_TRAINING_MEMBER_SUCCESS"
export const UPDATE_TRAINING_MEMBER_FAIL = "UPDATE_TRAINING_MEMBER_FAIL"

export const DELETE_TRAINING_MEMBER = "DELETE_TRAINING_MEMBER"
export const DELETE_TRAINING_MEMBER_SUCCESS = "DELETE_TRAINING_MEMBER_SUCCESS"
export const DELETE_TRAINING_MEMBER_FAIL = "DELETE_TRAINING_MEMBER_FAIL"

export const GET_TRAINING_MEMBER_DELETED_VALUE = "GET_TRAINING_MEMBER_DELETED_VALUE"
export const GET_TRAINING_MEMBER_DELETED_VALUE_SUCCESS = "GET_TRAINING_MEMBER_DELETED_VALUE_SUCCESS"
export const GET_TRAINING_MEMBER_DELETED_VALUE_FAIL = "GET_TRAINING_MEMBER_DELETED_VALUE_FAIL"