/* GRANT_SPONSORS */
export const GET_GRANT_SPONSORS = "GET_GRANT_SPONSORS"
export const GET_GRANT_SPONSORS_SUCCESS = "GET_GRANT_SPONSORS_SUCCESS"
export const GET_GRANT_SPONSORS_FAIL = "GET_GRANT_SPONSORS_FAIL"

/* GRANT_SPONSOR PROFILE */
export const GET_GRANT_SPONSOR_PROFILE = "GET_GRANT_SPONSOR_PROFILE"
export const GET_GRANT_SPONSOR_PROFILE_SUCCESS = "GET_GRANT_SPONSOR_PROFILE_SUCCESS"
export const GET_GRANT_SPONSOR_PROFILE_FAIL = "GET_GRANT_SPONSOR_PROFILE_FAIL"

export const ADD_NEW_GRANT_SPONSOR = "ADD_NEW_GRANT_SPONSOR"
export const ADD_GRANT_SPONSOR_SUCCESS = "ADD_GRANT_SPONSOR_SUCCESS"
export const ADD_GRANT_SPONSOR_FAIL = "ADD_GRANT_SPONSOR_FAIL"

export const UPDATE_GRANT_SPONSOR = "UPDATE_GRANT_SPONSOR"
export const UPDATE_GRANT_SPONSOR_SUCCESS = "UPDATE_GRANT_SPONSOR_SUCCESS"
export const UPDATE_GRANT_SPONSOR_FAIL = "UPDATE_GRANT_SPONSOR_FAIL"

export const DELETE_GRANT_SPONSOR = "DELETE_GRANT_SPONSOR"
export const DELETE_GRANT_SPONSOR_SUCCESS = "DELETE_GRANT_SPONSOR_SUCCESS"
export const DELETE_GRANT_SPONSOR_FAIL = "DELETE_GRANT_SPONSOR_FAIL"


export const GET_GRANT_SPONSOR_DELETED_VALUE = "GET_GRANT_SPONSOR_DELETED_VALUE"
export const GET_GRANT_SPONSOR_DELETED_VALUE_SUCCESS = "GET_GRANT_SPONSOR_DELETED_VALUE_SUCCESS"
export const GET_GRANT_SPONSOR_DELETED_VALUE_FAIL = "GET_GRANT_SPONSOR_DELETED_VALUE_FAIL"