/* PERIODS */
export const GET_PERIODS = "GET_PERIODS"
export const GET_PERIODS_SUCCESS = "GET_PERIODS_SUCCESS"
export const GET_PERIODS_FAIL = "GET_PERIODS_FAIL"

/* PERIODS DELETED_VALUE*/
export const GET_PERIOD_DELETED_VALUE = "GET_PERIOD_DELETED_VALUE"
export const GET_PERIOD_DELETED_VALUE_SUCCESS = "GET_PERIOD_DELETED_VALUE_SUCCESS"
export const GET_PERIOD_DELETED_VALUE_FAIL = "GET_PERIOD_DELETED_VALUE_FAIL"

export const ADD_NEW_PERIOD = "ADD_NEW_PERIOD"
export const ADD_PERIOD_SUCCESS = "ADD_PERIOD_SUCCESS"
export const ADD_PERIOD_FAIL = "ADD_PERIOD_FAIL"

export const UPDATE_PERIOD = "UPDATE_PERIOD"
export const UPDATE_PERIOD_SUCCESS = "UPDATE_PERIOD_SUCCESS"
export const UPDATE_PERIOD_FAIL = "UPDATE_PERIOD_FAIL"

export const DELETE_PERIOD = "DELETE_PERIOD"
export const DELETE_PERIOD_SUCCESS = "DELETE_PERIOD_SUCCESS"
export const DELETE_PERIOD_FAIL = "DELETE_PERIOD_FAIL"

export const GET_FISCAL_YEAR_CONTENTS = "GET_FISCAL_YEAR_CONTENTS"
export const GET_FISCAL_YEAR_CONTENTS_SUCCESS = "GET_FISCAL_YEAR_CONTENTS_SUCCESS"
export const GET_FISCAL_YEAR_CONTENTS_FAIL = "GET_FISCAL_YEAR_CONTENTS_FAIL"

export const GET_FISCAL_YEARS = "GET_FISCAL_YEARS"
export const GET_FISCAL_YEARS_SUCCESS = "GET_FISCAL_YEARS_SUCCESS"
export const GET_FISCAL_YEARS_FAIL = "GET_FISCAL_YEARS_FAIL"

export const GET_FILTERED_PERIODS = "GET_FILTERED_PERIODS"
export const GET_FILTERED_PERIODS_SUCCESS = "GET_FILTERED_PERIODS_SUCCESS"
export const GET_FILTERED_PERIODS_FAIL = "GET_FILTERED_PERIODS_FAIL"