/* ARCHIVE GRADES */
export const GET_ARCHIVED_GRADES = "GET_ARCHIVED_GRADES"
export const GET_ARCHIVED_GRADES_SUCCESS = "GET_ARCHIVED_GRADES_SUCCESS"
export const GET_ARCHIVED_GRADES_FAIL = "GET_ARCHIVED_GRADES_FAIL"

export const UPDATE_ARCHIVED_GRADE = "UPDATE_ARCHIVED_GRADE"
export const UPDATE_ARCHIVED_GRADE_SUCCESS = "UPDATE_ARCHIVED_GRADE_SUCCESS"
export const UPDATE_ARCHIVED_GRADE_FAIL = "UPDATE_ARCHIVED_GRADE_FAIL"
