/* sidbarcontent */
export const GET_SIDEBAR_CONTENTS = "GET_SIDEBAR_CONTENTS"
export const GET_SIDEBAR_CONTENTS_SUCCESS = "GET_SIDEBAR_CONTENTS_SUCCESS"
export const GET_SIDEBAR_CONTENTS_FAIL = "GET_SIDEBAR_CONTENTS_FAIL"

export const GET_USER_SIDEBAR_CONTENTS = "GET_USER_SIDEBAR_CONTENTS"
export const GET_USER_SIDEBAR_CONTENTS_SUCCESS = "GET_USER_SIDEBAR_CONTENTS_SUCCESS"
export const GET_USER_SIDEBAR_CONTENTS_FAIL = "GET_USER_SIDEBAR_CONTENTS_FAIL"

export const GET_SEARCH_MENU = "GET_SEARCH_MENU"
export const GET_SEARCH_MENU_SUCCESS = "GET_SEARCH_MENU_SUCCESS"
export const GET_SEARCH_MENU_FAIL = "GET_SEARCH_MENU_FAIL"

export const GET_ROLE_SIDEBAR = "GET_ROLE_SIDEBAR"
export const GET_ROLE_SIDEBAR_SUCCESS = "GET_ROLE_SIDEBAR_SUCCESS"
export const GET_ROLE_SIDEBAR_FAIL = "GET_ROLE_SIDEBAR_FAIL"