/* EXAMS_ATTENDANCE */
export const GET_EXAM_ATTENDANCE_OBSERVERS = "GET_EXAM_ATTENDANCE_OBSERVERS";
export const GET_EXAM_ATTENDANCE_OBSERVERS_SUCCESS =
  "GET_EXAM_ATTENDANCE_OBSERVERS_SUCCESS";
export const GET_EXAM_ATTENDANCE_OBSERVERS_FAIL =
  "GET_EXAM_ATTENDANCE_OBSERVERS_FAIL";

export const ADD_NEW_EXAM_ATTENDANCE_OBSERVER =
  "ADD_NEW_EXAM_ATTENDANCE_OBSERVER";
export const ADD_EXAM_ATTENDANCE_OBSERVER_SUCCESS =
  "ADD_EXAM_ATTENDANCE_OBSERVER_SUCCESS";
export const ADD_EXAM_ATTENDANCE_OBSERVER_FAIL =
  "ADD_EXAM_ATTENDANCE_OBSERVER_FAIL";

export const UPDATE_EXAM_ATTENDANCE_OBSERVER =
  "UPDATE_EXAM_ATTENDANCE_OBSERVER";
export const UPDATE_EXAM_ATTENDANCE_OBSERVER_SUCCESS =
  "UPDATE_EXAM_ATTENDANCE_OBSERVER_SUCCESS";
export const UPDATE_EXAM_ATTENDANCE_OBSERVER_FAIL =
  "UPDATE_EXAM_ATTENDANCE_OBSERVER_FAIL";

export const DELETE_EXAM_ATTENDANCE_OBSERVER =
  "DELETE_EXAM_ATTENDANCE_OBSERVER";
export const DELETE_EXAM_ATTENDANCE_OBSERVER_SUCCESS =
  "DELETE_EXAM_ATTENDANCE_OBSERVER_SUCCESS";
export const DELETE_EXAM_ATTENDANCE_OBSERVER_FAIL =
  "DELETE_EXAM_ATTENDANCE_OBSERVER_FAIL";

export const GET_EXAM_ATTENDANCE_OBSERVER_DELETED_VALUE =
  "GET_EXAM_ATTENDANCE_OBSERVER_DELETED_VALUE";
export const GET_EXAM_ATTENDANCE_OBSERVER_DELETED_VALUE_SUCCESS =
  "GET_EXAM_ATTENDANCE_OBSERVER_DELETED_VALUE_SUCCESS";
export const GET_EXAM_ATTENDANCE_OBSERVER_DELETED_VALUE_FAIL =
  "GET_EXAM_ATTENDANCE_OBSERVER_DELETED_VALUE_FAIL";

// /* ATTEND STATUS */
// export const GET_ATTEND_STATUS = "GET_ATTEND_STATUS";
// export const GET_ATTEND_STATUS_SUCCESS = "GET_ATTEND_STATUS_SUCCESS";
// export const GET_ATTEND_STATUS_FAIL = "GET_ATTEND_STATUS_FAIL";
