/* EMPLOYMENT_CASES */
export const GET_EMPLOYMENT_CASES = "GET_EMPLOYMENT_CASES";
export const GET_EMPLOYMENT_CASES_SUCCESS = "GET_EMPLOYMENT_CASES_SUCCESS";
export const GET_EMPLOYMENT_CASES_FAIL = "GET_EMPLOYMENT_CASES_FAIL";

/* EMPLOYMENT_CASES PROFILE */
export const GET_EMPLOYMENT_CASE_DELETED_VALUE =
  "GET_EMPLOYMENT_CASE_DELETED_VALUE";
export const GET_EMPLOYMENT_CASE_DELETED_VALUE_SUCCESS =
  "GET_EMPLOYMENT_CASE_DELETED_VALUE_SUCCESS";
export const GET_EMPLOYMENT_CASE_DELETED_VALUE_FAIL =
  "GET_EMPLOYMENT_CASE_DELETED_VALUE_FAIL";

export const ADD_NEW_EMPLOYMENT_CASE = "ADD_NEW_EMPLOYMENT_CASE";
export const ADD_EMPLOYMENT_CASE_SUCCESS = "ADD_EMPLOYMENT_CASE_SUCCESS";
export const ADD_EMPLOYMENT_CASE_FAIL = "ADD_EMPLOYMENT_CASE_FAIL";

export const UPDATE_EMPLOYMENT_CASE = "UPDATE_EMPLOYMENT_CASE";
export const UPDATE_EMPLOYMENT_CASE_SUCCESS = "UPDATE_EMPLOYMENT_CASE_SUCCESS";
export const UPDATE_EMPLOYMENT_CASE_FAIL = "UPDATE_EMPLOYMENT_CASE_FAIL";

export const DELETE_EMPLOYMENT_CASE = "DELETE_EMPLOYMENT_CASE";
export const DELETE_EMPLOYMENT_CASE_SUCCESS = "DELETE_EMPLOYMENT_CASE_SUCCESS";
export const DELETE_EMPLOYMENT_CASE_FAIL = "DELETE_EMPLOYMENT_CASE_FAIL";
