/* warining */
export const GET_STD_WARNING_TEST = "GET_STD_WARNING_TEST"
export const GET_STD_WARNING_TEST_SUCCESS = "GET_STD_WARNING_TEST_SUCCESS"
export const GET_STD_WARNING_TEST_FAIL = "GET_STD_WARNING_TEST_FAIL"

export const ADD_NEW_STD_WARNING_TEST = "ADD_NEW_STD_WARNING_TEST"
export const ADD_STD_WARNING_TEST_SUCCESS = "ADD_STD_WARNING_TEST_SUCCESS"
export const ADD_STD_WARNING_TEST_FAIL = "ADD_STD_WARNING_TEST_FAIL"

export const UPDATE_STD_WARNING_TEST = "UPDATE_STD_WARNING_TEST"
export const UPDATE_STD_WARNING_TEST_SUCCESS = "UPDATE_STD_WARNING_TEST_SUCCESS"
export const UPDATE_STD_WARNING_TEST_FAIL = "UPDATE_STD_WARNING_TEST_FAIL"

export const DELETE_STD_WARNING_TEST = "DELETE_STD_WARNING_TEST"
export const DELETE_STD_WARNING_TEST_SUCCESS = "DELETE_STD_WARNING_TEST_SUCCESS"
export const DELETE_STD_WARNING_TEST_FAIL = "DELETE_STD_WARNING_TEST_FAIL"

export const GET_STD_WARNING_TEST_DELETED_VALUE = "GET_STD_WARNING_TEST_DELETED_VALUE"
export const GET_STD_WARNING_TEST_DELETED_VALUE_SUCCESS = "GET_STD_WARNING_TEST_DELETED_VALUE_SUCCESS"
export const GET_STD_WARNING_TEST_DELETED_VALUE_FAIL = "GET_STD_WARNING_TEST_DELETED_VALUE_FAIL"
