/* TRAINEES */
export const GET_TRAINEES = "GET_TRAINEES";
export const GET_TRAINEES_SUCCESS = "GET_TRAINEES_SUCCESS";
export const GET_TRAINEES_FAIL = "GET_TRAINEES_FAIL";

export const GET_SOCIAL_STATUS = "GET_SOCIAL_STATUS";
export const GET_SOCIAL_STATUS_SUCCESS = "GET_SOCIAL_STATUS_SUCCESS";
export const GET_SOCIAL_STATUS_FAIL = "GET_SOCIAL_STATUS_FAIL";
