/* LEVELS */
export const GET_LEVELS = "GET_LEVELS"
export const GET_LEVELS_SUCCESS = "GET_LEVELS_SUCCESS"
export const GET_LEVELS_FAIL = "GET_LEVELS_FAIL"

/* LEVEL PROFILE */
export const GET_LEVEL_DELETED_VALUE = "GET_LEVEL_DELETED_VALUE"
export const GET_LEVEL_DELETED_VALUE_SUCCESS = "GET_LEVEL_DELETED_VALUE_SUCCESS"
export const GET_LEVEL_DELETED_VALUE_FAIL = "GET_LEVEL_DELETED_VALUE_FAIL"

export const ADD_NEW_LEVEL = "ADD_NEW_LEVEL"
export const ADD_LEVEL_SUCCESS = "ADD_LEVEL_SUCCESS"
export const ADD_LEVEL_FAIL = "ADD_LEVEL_FAIL"

export const UPDATE_LEVEL = "UPDATE_LEVEL"
export const UPDATE_LEVEL_SUCCESS = "UPDATE_LEVEL_SUCCESS"
export const UPDATE_LEVEL_FAIL = "UPDATE_LEVEL_FAIL"

export const DELETE_LEVEL = "DELETE_LEVEL"
export const DELETE_LEVEL_SUCCESS = "DELETE_LEVEL_SUCCESS"
export const DELETE_LEVEL_FAIL = "DELETE_LEVEL_FAIL"