export const GET_GRANTS= "GET_GRANTS"
export const GET_GRANTS_SUCCESS= "GET_GRANTS_SUCCESS"
export const GET_GRANTS_FAIL="GET_GRANTS_FAIL"

export const ADD_NEW_GRANT= "ADD_NEW_GRANT"
export const ADD_GRANT_SUCCESS= "ADD_GRANT_SUCCESS"
export const ADD_GRANT_FAIL="ADD_GRANT_FAIL"

export const UPDATE_GRANT= "UPDATE_GRANT"
export const UPDATE_GRANT_SUCCESS= "UPDATE_GRANT_SUCCESS"
export const UPDATE_GRANT_FAIL="UPDATE_GRANT__FAIL"

export const DELETE_GRANT= "DELETE_GRANT"
export const DELETE_GRANT_SUCCESS= "DELETE_GRANT_SUCCESS"
export const DELETE_GRANT_FAIL= "DELETE_GRANT_FAIL"

export const GET_GRANT_DELETED_VALUE = "GET_GRANT_DELETED_VALUE"
export const GET_GRANT_DELETED_VALUE_SUCCESS = "GET_GRANT_DELETED_VALUE_SUCCESS"
export const GET_GRANT_DELETED_VALUE_FAIL = "GET_GRANT_DELETED_VALUE_FAIL"