/* GENERATE_SIDS */
export const GET_GENERATE_SIDS = "GET_GENERATE_SIDS"
export const GET_GENERATE_SIDS_SUCCESS = "GET_GENERATE_SIDS_SUCCESS"
export const GET_GENERATE_SIDS_FAIL = "GET_GENERATE_SIDS_FAIL"

/* GENERATE_SIDS PROFILE*/
export const GET_GENERATE_SID_PROFILE = "GET_GENERATE_SID_PROFILE"
export const GET_GENERATE_SID_PROFILE_SUCCESS = "GET_GENERATE_SID_PROFILE_SUCCESS"
export const GET_GENERATE_SID_PROFILE_FAIL = "GET_GENERATE_SID_PROFILE_FAIL"

export const ADD_NEW_GENERATE_SID = "ADD_NEW_GENERATE_SID"
export const ADD_GENERATE_SID_SUCCESS = "ADD_GENERATE_SID_SUCCESS"
export const ADD_GENERATE_SID_FAIL = "ADD_GENERATE_SID_FAIL"

export const UPDATE_GENERATE_SID = "UPDATE_GENERATE_SID"
export const UPDATE_GENERATE_SID_SUCCESS = "UPDATE_GENERATE_SID_SUCCESS"
export const UPDATE_GENERATE_SID_FAIL = "UPDATE_GENERATE_SID_FAIL"

export const DELETE_GENERATE_SID = "DELETE_GENERATE_SID"
export const DELETE_GENERATE_SID_SUCCESS = "DELETE_GENERATE_SID_SUCCESS"
export const DELETE_GENERATE_SID_FAIL = "DELETE_GENERATE_SID_FAIL"


/* TEMPSTUDENTS */
export const GET_TEMPSTUDENTS = "GET_TEMPSTUDENTS"
export const GET_TEMPSTUDENTS_SUCCESS = "GET_TEMPSTUDENTS_SUCCESS"
export const GET_TEMPSTUDENTS_FAIL = "GET_TEMPSTUDENTS_FAIL"



export const GET_TEMPSTD = "GET_TEMPSTD"