/* SCHEDULING_LECTURES */
export const GET_COURSES_OFFERING = "GET_COURSES_OFFERING";
export const GET_COURSES_OFFERING_SUCCESS = "GET_COURSES_OFFERING_SUCCESS";
export const GET_COURSES_OFFERING_FAIL = "GET_COURSES_OFFERING_FAIL";

export const GET_ALL_COURSES_OFFERING = "GET_ALL_COURSES_OFFERING";
export const GET_ALL_COURSES_OFFERING_SUCCESS =
  "GET_ALL_COURSES_OFFERING_SUCCESS";
export const GET_ALL_COURSES_OFFERING_FAIL = "GET_ALL_COURSES_OFFERING_FAIL";

/* SCHEDULING_LECTURE PROFILE */
export const GET_COURSE_OFFERING_PROFILE = "GET_COURSE_OFFERING_PROFILE";
export const GET_COURSE_OFFERING_PROFILE_SUCCESS =
  "GET_COURSE_OFFERING_PROFILE_SUCCESS";
export const GET_COURSE_OFFERING_PROFILE_FAIL =
  "GET_COURSE_OFFERING_PROFILE_FAIL";

export const ADD_NEW_COURSE_OFFERING = "ADD_NEW_COURSE_OFFERING";
export const ADD_COURSE_OFFERING_SUCCESS = "ADD_COURSE_OFFERING_SUCCESS";
export const ADD_COURSE_OFFERING_FAIL = "ADD_COURSE_OFFERING_FAIL";

export const UPDATE_COURSE_OFFERING = "UPDATE_COURSE_OFFERING";
export const UPDATE_COURSE_OFFERING_SUCCESS = "UPDATE_COURSE_OFFERING_SUCCESS";
export const UPDATE_COURSE_OFFERING_FAIL = "UPDATE_COURSE_OFFERING_FAIL";

export const DELETE_COURSE_OFFERING = "DELETE_COURSE_OFFERING";
export const DELETE_COURSE_OFFERING_SUCCESS = "DELETE_COURSE_OFFERING_SUCCESS";
export const DELETE_COURSE_OFFERING_FAIL = "DELETE_COURSE_OFFERING_FAIL";

/* SECTION_LABS */
export const GET_SECTION_LABS = "GET_SECTION_LABS";
export const GET_SECTION_LABS_SUCCESS = "GET_SECTION_LABS_SUCCESS";
export const GET_SECTION_LABS_FAIL = "GET_SECTION_LABS_FAIL";

/* SECTION_LAB_DETAILS */
export const GET_SECTION_LAB_DETAILS = "GET_SECTION_LAB_DETAILS";
export const GET_SECTION_LAB_DETAILS_SUCCESS =
  "GET_SECTION_LAB_DETAILS_SUCCESS";
export const GET_SECTION_LAB_DETAILS_FAIL = "GET_SECTION_LAB_DETAILS_FAIL";

/* SECTION_LAB PROFILE */
export const GET_SECTION_LAB_PROFILE = "GET_SECTION_LAB_PROFILE";
export const GET_SECTION_LAB_PROFILE_SUCCESS =
  "GET_SECTION_LAB_PROFILE_SUCCESS";
export const GET_SECTION_LAB_PROFILE_FAIL = "GET_SECTION_LAB_PROFILE_FAIL";

export const ADD_NEW_SECTION_LAB = "ADD_NEW_SECTION_LAB";
export const ADD_SECTION_LAB_SUCCESS = "ADD_SECTION_LAB_SUCCESS";
export const ADD_SECTION_LAB_FAIL = "ADD_SECTION_LAB_FAIL";

export const ADD_NEW_SECTION_LAB_DETAIL = "ADD_NEW_SECTION_LAB_DETAIL";
export const ADD_SECTION_LAB_DETAIL_SUCCESS = "ADD_SECTION_LAB_DETAIL_SUCCESS";
export const ADD_SECTION_LAB_DETAIL_FAIL = "ADD_SECTION_LAB_DETAIL_FAIL";

export const UPDATE_SECTION_LAB = "UPDATE_SECTION_LAB";
export const UPDATE_SECTION_LAB_SUCCESS = "UPDATE_SECTION_LAB_SUCCESS";
export const UPDATE_SECTION_LAB_FAIL = "UPDATE_SECTION_LAB_FAIL";

export const UPDATE_SECTION_LAB_DETAIL = " UPDATE_SECTION_LAB_DETAIL";
export const UPDATE_SECTION_LAB_DETAIL_SUCCESS =
  " UPDATE_SECTION_LAB_DETAIL_SUCCESS";
export const UPDATE_SECTION_LAB_DETAIL_FAIL = " UPDATE_SECTION_LAB_DETAIL_FAIL";

export const DELETE_SECTION_LAB = "DELETE_SECTION_LAB";
export const DELETE_SECTION_LAB_SUCCESS = "DELETE_SECTION_LAB_SUCCESS";
export const DELETE_SECTION_LAB_FAIL = "DELETE_SECTION_LAB_FAIL";

export const DELETE_SECTION_LAB_DETAIL = "DELETE_SECTION_LAB_DETAIL";
export const DELETE_SECTION_LAB_DETAIL_SUCCESS =
  "DELETE_SECTION_LAB_DETAIL_SUCCESS";
export const DELETE_SECTION_LAB_DETAIL_FAIL = "DELETE_SECTION_LAB_DETAIL_FAIL";

/* SCHEDULE_TIMING */

export const GET_SCHEDULE_TIMINGS = "GET_SCHEDULE_TIMINGS";
export const GET_SCHEDULE_TIMINGS_SUCCESS = "GET_SCHEDULE_TIMINGS_SUCCESS";
export const GET_SCHEDULE_TIMINGS_FAIL = "GET_SCHEDULE_TIMINGS_FAIL";

export const GET_SCHEDULE_TIMING_PROFILE = "GET_SCHEDULE_TIMING_PROFILE";
export const GET_SCHEDULE_TIMING_PROFILE_SUCCESS =
  "GET_SCHEDULE_TIMING_PROFILE_SUCCESS";
export const GET_SCHEDULE_TIMING_PROFILE_FAIL =
  "GET_SCHEDULE_TIMING_PROFILE_FAIL";

export const ADD_NEW_SCHEDULE_TIMING = "ADD_NEW_SCHEDULE_TIMING";
export const ADD_SCHEDULE_TIMING_SUCCESS = "ADD_SCHEDULE_TIMING_SUCCESS";
export const ADD_SCHEDULE_TIMING_FAIL = "ADD_SCHEDULE_TIMING_FAIL";

export const DELETE_SCHEDULE_TIMING = "DELETE_SCHEDULE_TIMING";
export const DELETE_SCHEDULE_TIMING_SUCCESS = "DELETE_SCHEDULE_TIMING_SUCCESS";
export const DELETE_SCHEDULE_TIMING_FAIL = "DELETE_SCHEDULE_TIMING_FAIL";

/* SCHEDULE_TIMING_DESCS */
export const GET_SCHEDULE_TIMING_DESCS = "GET_SCHEDULE_TIMING_DESCS";
export const GET_SCHEDULE_TIMING_DESCS_SUCCESS =
  "GET_SCHEDULE_TIMING_DESCS_SUCCESS";
export const GET_SCHEDULE_TIMING_DESCS_FAIL = "GET_SCHEDULE_TIMING_DESCS_FAIL";

export const GET_FILTERED_SECTIONS = "GET_FILTERED_SECTIONS";
export const GET_FILTERED_SECTIONS_SUCCESS = "GET_FILTERED_SECTIONS_SUCCESS";
export const GET_FILTERED_SECTIONS_FAIL = "GET_COURSES_OFFERING_FAIL";

/* DEFAULT_SETTINGS */
export const GET_DEFAULT_SETTINGS = "GET_DEFAULT_SETTINGS";

export const GET_SCHEDULE_MSG_VALUE = "GET_SCHEDULE_MSG_VALUE";
export const GET_SCHEDULE_MSG_VALUE_SUCCESS = "GET_SCHEDULE_MSG_VALUE_SUCCESS";
export const GET_SCHEDULE_MSG_VALUE_FAIL = "GET_SCHEDULE_MSG_VALUE_FAIL";

/* HALL_TIMING */

export const GET_HALL_TIMINGS = "GET_HALL_TIMINGS";
export const GET_HALL_TIMINGS_SUCCESS = "GET_HALL_TIMINGS_SUCCESS";
export const GET_HALL_TIMINGS_FAIL = "GET_HALL_TIMINGS_FAIL";

/* METHODS_OF_OFFERING_COURSES */
export const GET_METHODS_OF_OFFERING_COURSES =
  "GET_METHODS_OF_OFFERING_COURSES";
export const GET_METHODS_OF_OFFERING_COURSES_SUCCESS =
  "GET_METHODS_OF_OFFERING_COURSES_SUCCESS";
export const GET_METHODS_OF_OFFERING_COURSES_FAIL =
  "GET_METHODS_OF_OFFERING_COURSES_FAIL";
