/* REQUEST_FEESS */
export const GET_REQUESTS_FEES = "GET_REQUESTS_FEES"
export const GET_REQUESTS_FEES_SUCCESS = "GET_REQUESTS_FEES_SUCCESS"
export const GET_REQUESTS_FEES_FAIL = "GET_REQUESTS_FEES_FAIL"

/* REQUEST_FEESS DELETED_VALUE*/
export const GET_REQUEST_FEES_DELETED_VALUE = "GET_REQUEST_FEES_DELETED_VALUE"
export const GET_REQUEST_FEES_DELETED_VALUE_SUCCESS = "GET_REQUEST_FEES_DELETED_VALUE_SUCCESS"
export const GET_REQUEST_FEES_DELETED_VALUE_FAIL = "GET_REQUEST_FEES_DELETED_VALUE_FAIL"

export const ADD_NEW_REQUEST_FEES = "ADD_NEW_REQUEST_FEES"
export const ADD_REQUEST_FEES_SUCCESS = "ADD_REQUEST_FEES_SUCCESS"
export const ADD_REQUEST_FEES_FAIL = "ADD_REQUEST_FEES_FAIL"

export const UPDATE_REQUEST_FEES = "UPDATE_REQUEST_FEES"
export const UPDATE_REQUEST_FEES_SUCCESS = "UPDATE_REQUEST_FEES_SUCCESS"
export const UPDATE_REQUEST_FEES_FAIL = "UPDATE_REQUEST_FEES_FAIL"

export const DELETE_REQUEST_FEES = "DELETE_REQUEST_FEES"
export const DELETE_REQUEST_FEES_SUCCESS = "DELETE_REQUEST_FEES_SUCCESS"
export const DELETE_REQUEST_FEES_FAIL = "DELETE_REQUEST_FEES_FAIL"

export const GET_REQUEST_CRITERIA = "GET_REQUEST_CRITERIA";
export const GET_REQUEST_CRITERIA_SUCCESS = "GET_REQUEST_CRITERIA_SUCCESS";
export const GET_REQUEST_CRITERIA_FAIL = "GET_REQUEST_CRITERIA_FAIL";

export const COPY_REQUEST_FEES = "COPY_REQUEST_FEES"
export const COPY_REQUEST_FEES_SUCCESS = "COPY_REQUEST_FEES_SUCCESS"
export const COPY_REQUEST_FEES_FAIL = "COPY_REQUEST_FEES_FAIL"

export const GET_YEAR_CONTENTS = "GET_YEAR_CONTENTS"
export const GET_YEAR_CONTENTS_SUCCESS = "GET_YEAR_CONTENTS_SUCCESS"
export const GET_YEAR_CONTENTS_FAIL = "GET_YEAR_CONTENTS_FAIL"

