export const GET_ACADEMIC_LOADS = "GET_ACADEMIC_LOADS"
export const GET_ACADEMIC_LOADS_SUCCESS = "GET_ACADEMIC_LOADS_SUCCESS"
export const GET_ACADEMIC_LOADS_FAIL = "GET_ACADEMIC_LOADS_FAIL"

export const ADD_NEW_ACADEMIC_LOAD = "ADD_NEW_ACADEMIC_LOAD"
export const ADD_ACADEMIC_LOAD_SUCCESS = "ADD_ACADEMIC_LOAD_SUCCESS"
export const ADD_ACADEMIC_LOAD_FAIL = "ADD_ACADEMIC_LOAD_FAIL"

export const UPDATE_ACADEMIC_LOAD = "UPDATE_ACADEMIC_LOAD"
export const UPDATE_ACADEMIC_LOAD_SUCCESS = "UPDATE_ACADEMIC_LOAD_SUCCESS"
export const UPDATE_ACADEMIC_LOAD_FAIL = "UPDATE_ACADEMIC_LOAD_FAIL"

export const DELETE_ACADEMIC_LOAD = "DELETE_ACADEMIC_LOAD"
export const DELETE_ACADEMIC_LOAD_SUCCESS = "DELETE_ACADEMIC_LOAD_SUCCESS"
export const DELETE_ACADEMIC_LOAD_FAIL = "DELETE_ACADEMIC_LOAD_FAIL"

export const GET_ACADEMIC_LOAD_DELETED_VALUE = "GET_ACADEMIC_LOAD_DELETED_VALUE"
export const GET_ACADEMIC_LOAD_DELETED_VALUE_SUCCESS = "GET_ACADEMIC_LOAD_DELETED_VALUE_SUCCESS"
export const GET_ACADEMIC_LOAD_DELETED_VALUE_FAIL = "GET_ACADEMIC_LOAD_DELETED_VALUE_FAIL"