/* HALLS */
export const GET_HALLS = "GET_HALLS"
export const GET_HALLS_SUCCESS = "GET_HALLS_SUCCESS"
export const GET_HALLS_FAIL = "GET_HALLS_FAIL"

/* HALLS PROFILE */
export const GET_HALL_DELETED_VALUE = "GET_HALL_DELETED_VALUE"
export const GET_HALL_DELETED_VALUE_SUCCESS = "GET_HALL_DELETED_VALUE_SUCCESS"
export const GET_HALL_DELETED_VALUE_FAIL = "GET_HALL_DELETED_VALUE_FAIL"

export const ADD_NEW_HALL = "ADD_NEW_HALL"
export const ADD_HALL_SUCCESS = "ADD_HALL_SUCCESS"
export const ADD_HALL_FAIL = "ADD_HALL_FAIL"

export const UPDATE_HALL = "UPDATE_HALL"
export const UPDATE_HALL_SUCCESS = "UPDATE_HALL_SUCCESS"
export const UPDATE_HALL_FAIL = "UPDATE_HALL_FAIL"

export const DELETE_HALL = "DELETE_HALL"
export const DELETE_HALL_SUCCESS = "DELETE_HALL_SUCCESS"
export const DELETE_HALL_FAIL = "DELETE_HALL_FAIL"