/* STUDENTS_HISTORY */
export const GET_STUDENTS_HISTORY = "GET_STUDENTS_HISTORY"
export const GET_STUDENTS_HISTORY_SUCCESS = "GET_STUDENTS_HISTORY_SUCCESS"
export const GET_STUDENTS_HISTORY_FAIL = "GET_STUDENTS_HISTORY_FAIL"

export const ADD_NEW_STUDENT_HISTORY = "ADD_NEW_STUDENT_HISTORY"
export const ADD_STUDENT_HISTORY_SUCCESS = "ADD_STUDENT_HISTORY_SUCCESS"
export const ADD_STUDENT_HISTORY_FAIL = "ADD_STUDENT_HISTORY_FAIL"

export const CALCULATE_STUDENT_HISTORY = "CALCULATE_STUDENT_HISTORY"
export const CALCULATE_STUDENT_HISTORY_SUCCESS = "CALCULATE_STUDENT_HISTORY_SUCCESS"
export const CALCULATE_STUDENT_HISTORY_FAIL = "CALCULATE_STUDENT_HISTORY_FAIL"

export const CALCULATE_ALL_STUDENT_HISTORY = "CALCULATE_ALL_STUDENT_HISTORY"
export const CALCULATE_ALL_STUDENT_HISTORY_SUCCESS = "CALCULATE_ALL_STUDENT_HISTORY_SUCCESS"
export const CALCULATE_ALL_STUDENT_HISTORY_FAIL = "CALCULATE_ALL_STUDENT_HISTORY_FAIL"