/* EXAM_ROOMS */
export const GET_EXAM_ROOMS = "GET_EXAM_ROOMS";
export const GET_EXAM_ROOMS_SUCCESS = "GET_EXAM_ROOMS_SUCCESS";
export const GET_EXAM_ROOMS_FAIL = "GET_EXAM_ROOMS_FAIL";

/* EXAM_ROOMS PROFILE*/
export const GET_EXAM_ROOM_PROFILE = "GET_EXAM_ROOM_PROFILE";
export const GET_EXAM_ROOM_PROFILE_SUCCESS = "GET_EXAM_ROOM_PROFILE_SUCCESS";
export const GET_EXAM_ROOM_PROFILE_FAIL = "GET_EXAM_ROOM_PROFILE_FAIL";

export const ADD_NEW_EXAM_ROOM = "ADD_NEW_EXAM_ROOM";
export const ADD_EXAM_ROOM_SUCCESS = "ADD_EXAM_ROOM_SUCCESS";
export const ADD_EXAM_ROOM_FAIL = "ADD_EXAM_ROOM_FAIL";

export const UPDATE_EXAM_ROOM = "UPDATE_EXAM_ROOM";
export const UPDATE_EXAM_ROOM_SUCCESS = "UPDATE_EXAM_ROOM_SUCCESS";
export const UPDATE_EXAM_ROOM_FAIL = "UPDATE_EXAM_ROOM_FAIL";

export const DELETE_EXAM_ROOM = "DELETE_EXAM_ROOM";
export const DELETE_EXAM_ROOM_SUCCESS = "DELETE_EXAM_ROOM_SUCCESS";
export const DELETE_EXAM_ROOM_FAIL = "DELETE_EXAM_ROOM_FAIL";

export const GET_SETTING_EXAM_ROOM = "GET_SETTING_EXAM_ROOM";
