/* traineesDeservesDeprivation */
export const GET_TRAINEES_DESERVES_DEPRIVATION =
  "GET_TRAINEES_DESERVES_DEPRIVATION";
export const GET_TRAINEES_DESERVES_DEPRIVATION_SUCCESS =
  "GET_TRAINEES_DESERVES_DEPRIVATION_SUCCESS";
export const GET_TRAINEES_DESERVES_DEPRIVATION_FAIL =
  "GET_TRAINEES_DESERVES_DEPRIVATION_FAIL";

/* traineesDeservesDeprivation */
export const GET_TRAINEE_DESERVE_DEPRIVATION_DELETED_VALUE =
  "GET_TRAINEE_DESERVE_DEPRIVATION_DELETED_VALUE";
export const GET_TRAINEE_DESERVE_DEPRIVATION_DELETED_VALUE_SUCCESS =
  "GET_TRAINEE_DESERVE_DEPRIVATION_DELETED_VALUE_SUCCESS";
export const GET_TRAINEE_DESERVE_DEPRIVATION_DELETED_VALUE_FAIL =
  "GET_TRAINEE_DESERVE_DEPRIVATION_DELETED_VALUE_FAIL";

export const ADD_NEW_TRAINEE_DESERVE_DEPRIVATION =
  "ADD_NEW_TRAINEE_DESERVE_DEPRIVATION";
export const ADD_TRAINEE_DESERVE_DEPRIVATION_SUCCESS =
  "ADD_TRAINEE_DESERVE_DEPRIVATION_SUCCESS";
export const ADD_TRAINEE_DESERVE_DEPRIVATION_FAIL =
  "ADD_TRAINEE_DESERVE_DEPRIVATION_FAIL";

export const UPDATE_TRAINEE_DESERVE_DEPRIVATION =
  "UPDATE_TRAINEE_DESERVE_DEPRIVATION";
export const UPDATE_TRAINEE_DESERVE_DEPRIVATION_SUCCESS =
  "UPDATE_TRAINEE_DESERVE_DEPRIVATION_SUCCESS";
export const UPDATE_TRAINEE_DESERVE_DEPRIVATION_FAIL =
  "UPDATE_TRAINEE_DESERVE_DEPRIVATION_FAIL";

export const DELETE_TRAINEE_DESERVE_DEPRIVATION =
  "DELETE_TRAINEE_DESERVE_DEPRIVATION";
export const DELETE_TRAINEE_DESERVE_DEPRIVATION_SUCCESS =
  "DELETE_TRAINEE_DESERVE_DEPRIVATION_SUCCESS";
export const DELETE_TRAINEE_DESERVE_DEPRIVATION_FAIL =
  "DELETE_TRAINEE_DESERVE_DEPRIVATION_FAIL";
