/* WRITTEN_WARNING_DECREES */
export const GET_WRITTEN_WARNING_DECREES = " GET_WRITTEN_WARNING_DECREES";
export const GET_WRITTEN_WARNING_DECREES_SUCCESS =
  " GET_WRITTEN_WARNING_DECREES_SUCCESS";
export const GET_WRITTEN_WARNING_DECREES_FAIL =
  " GET_WRITTEN_WARNING_DECREES_FAIL";

/* WRITTEN_WARNING_DECREES PROFILE */
export const GET_WRITTEN_WARNING_DECREE_DELETED_VALUE =
  " GET_WRITTEN_WARNING_DECREE_DELETED_VALUE";
export const GET_WRITTEN_WARNING_DECREE_DELETED_VALUE_SUCCESS =
  " GET_WRITTEN_WARNING_DECREE_DELETED_VALUE_SUCCESS";
export const GET_WRITTEN_WARNING_DECREE_DELETED_VALUE_FAIL =
  " GET_WRITTEN_WARNING_DECREE_DELETED_VALUE_FAIL";

export const ADD_NEW_WRITTEN_WARNING_DECREE = "ADD_NEW_WRITTEN_WARNING_DECREE";
export const ADD_WRITTEN_WARNING_DECREE_SUCCESS =
  "ADD_WRITTEN_WARNING_DECREE_SUCCESS";
export const ADD_WRITTEN_WARNING_DECREE_FAIL =
  "ADD_WRITTEN_WARNING_DECREE_FAIL";

export const UPDATE_WRITTEN_WARNING_DECREE = "UPDATE_WRITTEN_WARNING_DECREE";
export const UPDATE_WRITTEN_WARNING_DECREE_SUCCESS =
  "UPDATE_WRITTEN_WARNING_DECREE_SUCCESS";
export const UPDATE_WRITTEN_WARNING_DECREE_FAIL =
  "UPDATE_WRITTEN_WARNING_DECREE_FAIL";

export const DELETE_WRITTEN_WARNING_DECREE = "DELETE_WRITTEN_WARNING_DECREE";
export const DELETE_WRITTEN_WARNING_DECREE_SUCCESS =
  "DELETE_WRITTEN_WARNING_DECREE_SUCCESS";
export const DELETE_WRITTEN_WARNING_DECREE_FAIL =
  "DELETE_WRITTEN_WARNING_DECREE_FAIL";
