export const GET_DOCUMENTS = "GET_DOCUMENTS"
export const GET_DOCUMENTS_SUCCESS = "GET_DOCUMENTS_SUCCESS"
export const GET_DOCUMENTS_FAIL = "GET_DOCUMENTS_FAIL"

export const GET_DOCUMENT_DELETED_VALUE = "GET_DOCUMENT_DELETED_VALUE"
export const GET_DOCUMENT_DELETED_VALUE_SUCCESS = "GET_DOCUMENT_DELETED_VALUE_SUCCESS"
export const GET_DOCUMENT_DELETED_VALUE_FAIL = "GET_DOCUMENT_DELETED_VALUE_FAIL"

export const ADD_NEW_DOCUMENT = "ADD_NEW_DOCUMENT"
export const ADD_DOCUMENT_SUCCESS = "ADD_DOCUMENT_SUCCESS"
export const ADD_DOCUMENT_FAIL = "ADD_DOCUMENT_FAIL"

export const UPDATE_DOCUMENT = "UPDATE_DOCUMENT"
export const UPDATE_DOCUMENT_SUCCESS = "UPDATE_DOCUMENT_SUCCESS"
export const UPDATE_DOCUMENT_FAIL = "UPDATE_DOCUMENT_FAIL"

export const DELETE_DOCUMENT = "DELETE_DOCUMENT"
export const DELETE_DOCUMENT_SUCCESS = "DELETE_DOCUMENT_SUCCESS"
export const DELETE_DOCUMENT_FAIL = "DELETE_DOCUMENT_FAIL"