export const GET_REG_REQ_DOCUMENTS = "GET_REG_REQ_DOCUMENTS"
export const GET_REG_REQ_DOCUMENTS_SUCCESS = "GET_REG_REQ_DOCUMENTS_SUCCESS"
export const GET_REG_REQ_DOCUMENTS_FAIL = "GET_REG_REQ_DOCUMENTS_FAIL"





/* REG_REQ_DOCUMENT PROFILE */
export const GET_REG_REQ_DOCUMENT_DELETED_VALUE = "GET_REG_REQ_DOCUMENT_DELETED_VALUE"
export const GET_REG_REQ_DOCUMENT_DELETED_VALUE_SUCCESS = "GET_REG_REQ_DOCUMENT_DELETED_VALUE_SUCCESS"
export const GET_REG_REQ_DOCUMENT_DELETED_VALUE_FAIL = "GET_REG_REQ_DOCUMENT_DELETED_VALUE_FAIL"

export const ADD_NEW_REG_REQ_DOCUMENT = "ADD_NEW_REG_REQ_DOCUMENT"
export const ADD_REG_REQ_DOCUMENT_SUCCESS = "ADD_REG_REQ_DOCUMENT_SUCCESS"
export const ADD_REG_REQ_DOCUMENT_FAIL = "ADD_REG_REQ_DOCUMENT_FAIL"

export const UPDATE_REG_REQ_DOCUMENT = "UPDATE_REG_REQ_DOCUMENT"
export const UPDATE_REG_REQ_DOCUMENT_SUCCESS = "UPDATE_REG_REQ_DOCUMENT_SUCCESS"
export const UPDATE_REG_REQ_DOCUMENT_FAIL = "UPDATE_REG_REQ_DOCUMENT_FAIL"

export const DELETE_REG_REQ_DOCUMENT = "DELETE_REG_REQ_DOCUMENT"
export const DELETE_REG_REQ_DOCUMENT_SUCCESS = "DELETE_REG_REQ_DOCUMENT_SUCCESS"
export const DELETE_REG_REQ_DOCUMENT_FAIL = "DELETE_REG_REQ_DOCUMENT_FAIL"


export const COPY_REG_REQ_DOC = "COPY_REG_REQ_DOC"
export const COPY_REG_REQ_DOC_SUCCESS = "COPY_REG_REQ_DOC_SUCCESS"
export const COPY_REG_REQ_DOC_FAIL = "COPY_REG_REQ_DOC_FAIL"
export const GET_REG_REQ_DOC_SETTINGS = "GET_REG_REQ_DOC_SETTINGS"


