/* ABSENCE_JUSTIFICATIONS */
export const GET_ABSENCES_JUSTIFICATIONS = "GET_ABSENCES_JUSTIFICATIONS";
export const GET_ABSENCES_JUSTIFICATIONS_SUCCESS = "GET_ABSENCES_JUSTIFICATIONS_SUCCESS";
export const GET_ABSENCES_JUSTIFICATIONS_FAIL = "GET_ABSENCES_JUSTIFICATIONS_FAIL";

/* ABSENCE_JUSTIFICATIONS PROFILE */
export const GET_ABSENCE_JUSTIFICATION_DELETED_VALUE =
  "GET_ABSENCE_JUSTIFICATION_DELETED_VALUE";
export const GET_ABSENCE_JUSTIFICATION_DELETED_VALUE_SUCCESS =
  "GET_ABSENCE_JUSTIFICATION_DELETED_VALUE_SUCCESS";
export const GET_ABSENCE_JUSTIFICATION_DELETED_VALUE_FAIL =
  "GET_ABSENCE_JUSTIFICATION_DELETED_VALUE_FAIL";

export const ADD_NEW_ABSENCE_JUSTIFICATION = "ADD_NEW_ABSENCE_JUSTIFICATION";
export const ADD_ABSENCE_JUSTIFICATION_SUCCESS = "ADD_ABSENCE_JUSTIFICATION_SUCCESS";
export const ADD_ABSENCE_JUSTIFICATION_FAIL = "ADD_ABSENCE_JUSTIFICATION_FAIL";

export const UPDATE_ABSENCE_JUSTIFICATION = "UPDATE_ABSENCE_JUSTIFICATION";
export const UPDATE_ABSENCE_JUSTIFICATION_SUCCESS = "UPDATE_ABSENCE_JUSTIFICATION_SUCCESS";
export const UPDATE_ABSENCE_JUSTIFICATION_FAIL = "UPDATE_ABSENCE_JUSTIFICATION_FAIL";

export const DELETE_ABSENCE_JUSTIFICATION = "DELETE_ABSENCE_JUSTIFICATION";
export const DELETE_ABSENCE_JUSTIFICATION_SUCCESS = "DELETE_ABSENCE_JUSTIFICATION_SUCCESS";
export const DELETE_ABSENCE_JUSTIFICATION_FAIL = "DELETE_ABSENCE_JUSTIFICATION_FAIL";
