/* POSITIONS */
export const GET_POSITIONS = "GET_POSITIONS";
export const GET_POSITIONS_SUCCESS = "GET_POSITIONS_SUCCESS";
export const GET_POSITIONS_FAIL = "GET_POSITIONS_FAIL";

/* POSITIONS */
export const GET_POSITION_DELETED_VALUE = "GET_POSITION_DELETED_VALUE";
export const GET_POSITION_DELETED_VALUE_SUCCESS =
  "GET_POSITION_DELETED_VALUE_SUCCESS";
export const GET_POSITION_DELETED_VALUE_FAIL =
  "GET_POSITION_DELETED_VALUE_FAIL";

export const ADD_NEW_POSITION = "ADD_NEW_POSITION";
export const ADD_POSITION_SUCCESS = "ADD_POSITION_SUCCESS";
export const ADD_POSITION_FAIL = "ADD_POSITION_FAIL";

export const UPDATE_POSITION = "UPDATE_POSITION";
export const UPDATE_POSITION_SUCCESS = "UPDATE_POSITION_SUCCESS";
export const UPDATE_POSITION_FAIL = "UPDATE_POSITION_FAIL";

export const DELETE_POSITION = "DELETE_POSITION";
export const DELETE_POSITION_SUCCESS = "DELETE_POSITION_SUCCESS";
export const DELETE_POSITION_FAIL = "DELETE_POSITION_FAIL";
