export const GET_CURRENCIES = "GET_CURRENCIES"
export const GET_CURRENCIES_SUCCESS = "GET_CURRENCIES_SUCCESS"
export const GET_CURRENCIES_FAIL = "GET_CURRENCIES_FAIL"

/* CURRENCY PROFILE */
export const GET_CURRENCY_DELETED_VALUE = "GET_CURRENCY_DELETED_VALUE"
export const GET_CURRENCY_DELETED_VALUE_SUCCESS = "GET_CURRENCY_DELETED_VALUE_SUCCESS"
export const GET_CURRENCY_DELETED_VALUE_FAIL = "GET_CURRENCY_DELETED_VALUE_FAIL"

export const ADD_NEW_CURRENCY = "ADD_NEW_CURRENCY"
export const ADD_CURRENCY_SUCCESS = "ADD_CURRENCY_SUCCESS"
export const ADD_CURRENCY_FAIL = "ADD_CURRENCY_FAIL"

export const UPDATE_CURRENCY = "UPDATE_CURRENCY"
export const UPDATE_CURRENCY_SUCCESS = "UPDATE_CURRENCY_SUCCESS"
export const UPDATE_CURRENCY_FAIL = "UPDATE_CURRENCY_FAIL"

export const DELETE_CURRENCY = "DELETE_CURRENCY"
export const DELETE_CURRENCY_SUCCESS = "DELETE_CURRENCY_SUCCESS"
export const DELETE_CURRENCY_FAIL = "DELETE_CURRENCY_FAIL"