/* _HALL_SCHEDULE */
export const GET_HALL_SCHEDULES = "GET_HALL_SCHEDULES";
export const GET_HALL_SCHEDULES_SUCCESS = "GET_HALL_SCHEDULES_SUCCESS";
export const GET_HALL_SCHEDULES_FAIL = "GET_HALL_SCHEDULES_FAIL";

export const ADD_NEW_HALL_SCHEDULE = "ADD_NEW_HALL_SCHEDULE";
export const ADD_HALL_SCHEDULE_SUCCESS = "ADD_HALL_SCHEDULE_SUCCESS";
export const ADD_HALL_SCHEDULE_FAIL = "ADD_HALL_SCHEDULE_FAIL";

export const UPDATE_HALL_SCHEDULE = "UPDATE_HALL_SCHEDULE";
export const UPDATE_HALL_SCHEDULE_SUCCESS = "UPDATE_HALL_SCHEDULE_SUCCESS";
export const UPDATE_HALL_SCHEDULE_FAIL = "UPDATE_HALL_SCHEDULE_FAIL";

export const DELETE_HALL_SCHEDULE = "DELETE_HALL_SCHEDULE";
export const DELETE_HALL_SCHEDULE_SUCCESS = "DELETE_HALL_SCHEDULE_SUCCESS";
export const DELETE_HALL_SCHEDULE_FAIL = "DELETE_HALL_SCHEDULE_FAIL";

export const GET_HALL_SCHEDULE_DELETED_VALUE =
  "GET_HALL_SCHEDULE_DELETED_VALUE";
export const GET_HALL_SCHEDULE_DELETED_VALUE_SUCCESS =
  "GET_HALL_SCHEDULE_DELETED_VALUE_SUCCESS";
export const GET_HALL_SCHEDULE_DELETED_VALUE_FAIL =
  "GET_HALL_SCHEDULE_DELETED_VALUE_FAIL";

/* ATTEND STATUS */
export const GET_ATTEND_STATUS = "GET_ATTEND_STATUS";
export const GET_ATTEND_STATUS_SUCCESS = "GET_ATTEND_STATUS_SUCCESS";
export const GET_ATTEND_STATUS_FAIL = "GET_ATTEND_STATUS_FAIL";
