export const GET_ABSENCE_PERCENTS = "GET_ABSENCE_PERCENTS"
export const GET_ABSENCE_PERCENTS_SUCCESS = "GET_ABSENCE_PERCENTS_SUCCESS"
export const GET_ABSENCE_PERCENTS_FAIL = "GET_ABSENCE_PERCENTS_FAIL"

export const GET_ABSENCE_PERCENT_DELETED_VALUE = "GET_ABSENCE_PERCENT_DELETED_VALUE"
export const GET_ABSENCE_PERCENT_DELETED_VALUE_SUCCESS = "GET_ABSENCE_PERCENT_DELETED_VALUE_SUCCESS"
export const GET_ABSENCE_PERCENT_DELETED_VALUE_FAIL = "GET_ABSENCE_PERCENT_DELETED_VALUE_FAIL"




export const ADD_NEW_ABSENCE_PERCENT = "ADD_NEW_ABSENCE_PERCENT"
export const ADD_ABSENCE_PERCENT_SUCCESS = "ADD_ABSENCE_PERCENT_SUCCESS"
export const ADD_ABSENCE_PERCENT_FAIL = "ADD_ABSENCE_PERCENT_FAIL"

export const UPDATE_ABSENCE_PERCENT = "UPDATE_ABSENCE_PERCENT"
export const UPDATE_ABSENCE_PERCENT_SUCCESS = "UPDATE_ABSENCE_PERCENT_SUCCESS"
export const UPDATE_ABSENCE_PERCENT_FAIL = "UPDATE_ABSENCE_PERCENT_FAIL"

export const DELETE_ABSENCE_PERCENT = "DELETE_ABSENCE_PERCENT"
export const DELETE_ABSENCE_PERCENT_SUCCESS = "DELETE_ABSENCE_PERCENT_SUCCESS"
export const DELETE_ABSENCE_PERCENT_FAIL = "DELETE_ABSENCE_PERCENT_FAIL"