/* CONTRACTS */
export const GET_CONTRACTS = "GET_CONTRACTS";
export const GET_CONTRACTS_SUCCESS = "GET_CONTRACTS_SUCCESS";
export const GET_CONTRACTS_FAIL = "GET_CONTRACTS_FAIL";

/* CONTRACTS */
export const GET_CONTRACT_DELETED_VALUE = "GET_CONTRACT_DELETED_VALUE";
export const GET_CONTRACT_DELETED_VALUE_SUCCESS =
  "GET_CONTRACT_DELETED_VALUE_SUCCESS";
export const GET_CONTRACT_DELETED_VALUE_FAIL =
  "GET_CONTRACT_DELETED_VALUE_FAIL";

export const ADD_NEW_CONTRACT = "ADD_NEW_CONTRACT";
export const ADD_CONTRACT_SUCCESS = "ADD_CONTRACT_SUCCESS";
export const ADD_CONTRACT_FAIL = "ADD_CONTRACT_FAIL";

export const UPDATE_CONTRACT = "UPDATE_CONTRACT";
export const UPDATE_CONTRACT_SUCCESS = "UPDATE_CONTRACT_SUCCESS";
export const UPDATE_CONTRACT_FAIL = "UPDATE_CONTRACT_FAIL";

export const DELETE_CONTRACT = "DELETE_CONTRACT";
export const DELETE_CONTRACT_SUCCESS = "DELETE_CONTRACT_SUCCESS";
export const DELETE_CONTRACT_FAIL = "DELETE_CONTRACT_FAIL";
