/* ABSENCE_TYPES */
export const GET_ABSENCES_TYPES = "GET_ABSENCES_TYPES";
export const GET_ABSENCES_TYPES_SUCCESS = "GET_ABSENCES_TYPES_SUCCESS";
export const GET_ABSENCES_TYPES_FAIL = "GET_ABSENCES_TYPES_FAIL";

/* ABSENCE_TYPES PROFILE */
export const GET_ABSENCE_TYPE_DELETED_VALUE =
  "GET_ABSENCE_TYPE_DELETED_VALUE";
export const GET_ABSENCE_TYPE_DELETED_VALUE_SUCCESS =
  "GET_ABSENCE_TYPE_DELETED_VALUE_SUCCESS";
export const GET_ABSENCE_TYPE_DELETED_VALUE_FAIL =
  "GET_ABSENCE_TYPE_DELETED_VALUE_FAIL";

export const ADD_NEW_ABSENCE_TYPE = "ADD_NEW_ABSENCE_TYPE";
export const ADD_ABSENCE_TYPE_SUCCESS = "ADD_ABSENCE_TYPE_SUCCESS";
export const ADD_ABSENCE_TYPE_FAIL = "ADD_ABSENCE_TYPE_FAIL";

export const UPDATE_ABSENCE_TYPE = "UPDATE_ABSENCE_TYPE";
export const UPDATE_ABSENCE_TYPE_SUCCESS = "UPDATE_ABSENCE_TYPE_SUCCESS";
export const UPDATE_ABSENCE_TYPE_FAIL = "UPDATE_ABSENCE_TYPE_FAIL";

export const DELETE_ABSENCE_TYPE = "DELETE_ABSENCE_TYPE";
export const DELETE_ABSENCE_TYPE_SUCCESS = "DELETE_ABSENCE_TYPE_SUCCESS";
export const DELETE_ABSENCE_TYPE_FAIL = "DELETE_ABSENCE_TYPE_FAIL";
