/* TRAINEES */
export const GET_TRAINEES = "GET_TRAINEES";
export const GET_TRAINEES_SUCCESS = "GET_TRAINEES_SUCCESS";
export const GET_TRAINEES_FAIL = "GET_TRAINEES_FAIL";

/* TRAINEE PROFILE */
export const GET_TRAINEE_DELETED_VALUE = "GET_TRAINEE_DELETED_VALUE";
export const GET_TRAINEE_DELETED_VALUE_SUCCESS =
  "GET_TRAINEE_DELETED_VALUE_SUCCESS";
export const GET_TRAINEE_DELETED_VALUE_FAIL = "GET_TRAINEE_DELETED_VALUE_FAIL";

export const ADD_NEW_TRAINEE = "ADD_NEW_TRAINEE";
export const ADD_TRAINEE_SUCCESS = "ADD_TRAINEE_SUCCESS";
export const ADD_TRAINEE_FAIL = "ADD_TRAINEE_FAIL";

export const UPDATE_TRAINEE = "UPDATE_TRAINEE";
export const UPDATE_TRAINEE_SUCCESS = "UPDATE_TRAINEE_SUCCESS";
export const UPDATE_TRAINEE_FAIL = "UPDATE_TRAINEE_FAIL";

export const DELETE_TRAINEE = "DELETE_TRAINEE";
export const DELETE_TRAINEE_SUCCESS = "DELETE_TRAINEE_SUCCESS";
export const DELETE_TRAINEE_FAIL = "DELETE_TRAINEE_FAIL";

export const GET_TRAINEE_DEFAULT_REGREQDOCS = "GET_TRAINEE_DEFAULT_REGREQDOCS";
export const GET_TRAINEE_DEFAULT_REGREQDOCS_SUCCESS =
  "GET_TRAINEE_DEFAULT_REGREQDOCS_SUCCESS";
export const GET_TRAINEE_DEFAULT_REGREQDOCS_FAIL =
  "GET_TRAINEE_DEFAULT_REGREQDOCS_FAIL";

/* TEMP_RELATIVES */
export const GET_TEMP_RELATIVES = "GET_TEMP_RELATIVES";
export const GET_TEMP_RELATIVES_SUCCESS = "GET_TEMP_RELATIVES_SUCCESS";
export const GET_TEMP_RELATIVES_FAIL = "GET_TEMP_RELATIVES_FAIL";

/* RegisterCertificates */

export const GET_REGISTER_CERTIFICATES = "GET_REGISTER_CERTIFICATES";
export const GET_REGISTER_CERTIFICATES_SUCCESS =
  "GET_REGISTER_CERTIFICATES_SUCCESS";
export const GET_REGISTER_CERTIFICATES_FAIL = "GET_REGISTER_CERTIFICATES_FAIL";

/* TRAINEES */
export const GET_SOCIAL_STATUS = "GET_SOCIAL_STATUS";
export const GET_SOCIAL_STATUS_SUCCESS = "GET_SOCIAL_STATUS_SUCCESS";
export const GET_SOCIAL_STATUS_FAIL = "GET_SOCIAL_STATUS_FAIL";

/*pofessional experience*/
export const ADD_NEW_PROFESSIONAL_EXPERIENCE =
  "ADD_NEW_PROFESSIONAL_EXPERIENCE";
export const ADD_PROFESSIONAL_EXPERIENCE_SUCCESS =
  "ADD_PROFESSIONAL_EXPERIENCE_SUCCESS";
export const ADD_PROFESSIONAL_EXPERIENCE_FAIL =
  "ADD_PROFESSIONAL_EXPERIENCE_FAIL";

export const UPDATE_PROFESSIONAL_EXPERIENCE = "UPDATE_PROFESSIONAL_EXPERIENCE";
export const UPDATE_PROFESSIONAL_EXPERIENCE_SUCCESS =
  "UPDATE_PROFESSIONAL_EXPERIENCE_SUCCESS";
export const UPDATE_PROFESSIONAL_EXPERIENCE_FAIL =
  "UPDATE_PROFESSIONAL_EXPERIENCE_FAIL";

export const DELETE_PROFESSIONAL_EXPERIENCE = "DELETE_PROFESSIONAL_EXPERIENCE";
export const DELETE_PROFESSIONAL_EXPERIENCE_SUCCESS =
  "DELETE_PROFESSIONAL_EXPERIENCE_SUCCESS";
export const DELETE_PROFESSIONAL_EXPERIENCE_FAIL =
  "DELETE_PROFESSIONAL_EXPERIENCE_FAIL";
