export const GET_TRAINEES_OPTIONS = "GET_TRAINEES_OPTIONS";
export const GET_TRAINEES_OPTIONS_SUCCESS = "GET_TRAINEES_OPTIONS_SUCCESS";
export const GET_TRAINEES_OPTIONS_FAIL = "GET_TRAINEES_OPTIONS_FAIL";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";
