export const GET_ROLES = "GET_ROLES";
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_ROLES_FAIL = "GET_ROLES_FAIL";

export const ADD_NEW_ROLE = "ADD_NEW_ROLE";
export const ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS";
export const ADD_ROLE_FAIL = "ADD_ROLE_FAIL";

export const UPDATE_ROLE = "UPDATE_ROLE";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_FAIL = "UPDATE_ROLE_FAIL";

export const DELETE_ROLE = "DELETE_ROLE";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAIL = "DELETE_ROLE_FAIL";

export const GET_ROLE_DELETED_VALUE = "GET_ROLE_DELETED_VALUE";
export const GET_ROLE_DELETED_VALUE_SUCCESS = "GET_ROLE_DELETED_VALUE_SUCCESS";
export const GET_ROLE_DELETED_VALUE_FAIL = "GET_ROLE_DELETED_VALUE_FAIL";
//role permissions
export const GET_ROLE_PERMISSIONS = "GET_ROLE_PERMISSIONS";
export const GET_ROLE_PERMISSIONS_SUCCESS = "GET_ROLE_PERMISSIONS_SUCCESS";
export const GET_ROLE_PERMISSIONS_FAIL = "GET_ROLE_PERMISSIONS_FAIL";

export const ADD_NEW_ROLE_PERMISSION = "ADD_NEW_ROLE_PERMISSION";
export const ADD_ROLE_PERMISSION_SUCCESS = "ADD_ROLE_PERMISSION_SUCCESS";
export const ADD_ROLE_PERMISSION_FAIL = "ADD_ROLE_PERMISSION_FAIL";

export const UPDATE_ROLE_PERMISSION = "UPDATE_ROLE_PERMISSION";
export const UPDATE_ROLE_PERMISSION_SUCCESS = "UPDATE_ROLE_PERMISSION_SUCCESS";
export const UPDATE_ROLE_PERMISSION_FAIL = "UPDATE_ROLE_PERMISSION_FAIL";

export const DELETE_ROLE_PERMISSION = "DELETE_ROLE_PERMISSION";
export const DELETE_ROLE_PERMISSION_SUCCESS = "DELETE_ROLE_PERMISSION_SUCCESS";
export const DELETE_ROLE_PERMISSION_FAIL = "DELETE_ROLE_PERMISSION_FAIL";

export const GET_ROLE_PERMISSION_DELETED_VALUE =
  "GET_ROLE_PERMISSION_DELETED_VALUE";
export const GET_ROLE_PERMISSION_DELETED_VALUE_SUCCESS =
  "GET_ROLE_PERMISSION_DELETED_VALUE_SUCCESS";
export const GET_ROLE_PERMISSION_DELETED_VALUE_FAIL =
  "GET_ROLE_PERMISSION_DELETED_VALUE_FAIL";

// role user

export const ADD_NEW_ROLE_USER = "ADD_NEW_ROLE_USER";
export const ADD_ROLE_USER_SUCCESS = "ADD_ROLE_USER_SUCCESS";
export const ADD_ROLE_USER_FAIL = "ADD_ROLE_USER_FAIL";
