/* PREREQS */
export const GET_PREREQS = "GET_PREREQS"
export const GET_PREREQS_SUCCESS = "GET_PREREQS_SUCCESS"
export const GET_PREREQS_FAIL = "GET_PREREQS_FAIL"

export const GET_PREREQ_DELETED_VALUE = "GET_PREREQ_DELETED_VALUE"
export const GET_PREREQ_DELETED_VALUE_SUCCESS = "GET_PREREQ_DELETED_VALUE_SUCCESS"
export const GET_PREREQ_DELETED_VALUE_FAIL = "GET_PREREQ_DELETED_VALUE_FAIL"

export const ADD_NEW_PREREQ = "ADD_NEW_PREREQ"
export const ADD_PREREQ_SUCCESS = "ADD_PREREQ_SUCCESS"
export const ADD_PREREQ_FAIL = "ADD_PREREQ_FAIL"

export const UPDATE_PREREQ = "UPDATE_PREREQ"
export const UPDATE_PREREQ_SUCCESS = "UPDATE_PREREQ_SUCCESS"
export const UPDATE_PREREQ_FAIL = "UPDATE_PREREQ_FAIL"

export const DELETE_PREREQ = "DELETE_PREREQ"
export const DELETE_PREREQ_SUCCESS = "DELETE_PREREQ_SUCCESS"
export const DELETE_PREREQ_FAIL = "DELETE_PREREQ_FAIL"