/* ABSENCE_WARNINGS */
export const GET_ABSENCE_WARNINGS = "GET_ABSENCE_WARNINGS";
export const GET_ABSENCE_WARNINGS_SUCCESS = "GET_ABSENCE_WARNINGS_SUCCESS";
export const GET_ABSENCE_WARNINGS_FAIL = "GET_ABSENCE_WARNINGS_FAIL";

/* ABSENCE_WARNINGS PROFILE */
export const GET_ABSENCE_WARNING_DELETED_VALUE =
  "GET_ABSENCE_WARNING_DELETED_VALUE";
export const GET_ABSENCE_WARNING_DELETED_VALUE_SUCCESS =
  "GET_ABSENCE_WARNING_DELETED_VALUE_SUCCESS";
export const GET_ABSENCE_WARNING_DELETED_VALUE_FAIL =
  "GET_ABSENCE_WARNING_DELETED_VALUE_FAIL";

export const ADD_NEW_ABSENCE_WARNING = "ADD_NEW_ABSENCE_WARNING";
export const ADD_ABSENCE_WARNING_SUCCESS = "ADD_ABSENCE_WARNING_SUCCESS";
export const ADD_ABSENCE_WARNING_FAIL = "ADD_ABSENCE_WARNING_FAIL";

export const UPDATE_ABSENCE_WARNING = "UPDATE_ABSENCE_WARNING";
export const UPDATE_ABSENCE_WARNING_SUCCESS = "UPDATE_ABSENCE_WARNING_SUCCESS";
export const UPDATE_ABSENCE_WARNING_FAIL = "UPDATE_ABSENCE_WARNING_FAIL";

export const DELETE_ABSENCE_WARNING = "DELETE_ABSENCE_WARNING";
export const DELETE_ABSENCE_WARNING_SUCCESS = "DELETE_ABSENCE_WARNING_SUCCESS";
export const DELETE_ABSENCE_WARNING_FAIL = "DELETE_ABSENCE_WARNING_FAIL";

export const GET_DECISION_REASONS = "GET_DECISION_REASONS";
export const GET_DECISION_REASONS_SUCCESS = "GET_DECISION_REASONS_SUCCESS";
export const GET_DECISION_REASONS_FAIL = "GET_DECISION_REASONS_FAIL";

export const GET_TURN_REASONS = "GET_TURN_REASONS";
export const GET_TURN_REASONS_SUCCESS = "GET_TURN_REASONS_SUCCESS";
export const GET_TURN_REASONS_FAIL = "GET_TURN_REASONS_FAIL";
