/* STUDY_PLANS */
export const GET_STUDENTS_STATISTICS = "GET_STUDENTS_STATISTICS"
export const GET_STUDENTS_STATISTICS_SUCCESS = "GET_STUDENTS_STATISTICS_SUCCESS"
export const GET_STUDENTS_STATISTICS_FAIL = "GET_STUDENTS_STATISTICS_FAIL"
