/* WORK_CLASSIFICATIONS */
export const GET_WORK_CLASSIFICATIONS = "GET_WORK_CLASSIFICATIONS";
export const GET_WORK_CLASSIFICATIONS_SUCCESS =
  "GET_WORK_CLASSIFICATIONS_SUCCESS";
export const GET_WORK_CLASSIFICATIONS_FAIL = "GET_WORK_CLASSIFICATIONS_FAIL";

/* WORK_CLASSIFICATIONS PROFILE */
export const GET_WORK_CLASSIFICATION_DELETED_VALUE =
  "GET_WORK_CLASSIFICATION_DELETED_VALUE";
export const GET_WORK_CLASSIFICATION_DELETED_VALUE_SUCCESS =
  "GET_WORK_CLASSIFICATION_DELETED_VALUE_SUCCESS";
export const GET_WORK_CLASSIFICATION_DELETED_VALUE_FAIL =
  "GET_WORK_CLASSIFICATION_DELETED_VALUE_FAIL";

export const ADD_NEW_WORK_CLASSIFICATION = "ADD_NEW_WORK_CLASSIFICATION";
export const ADD_WORK_CLASSIFICATION_SUCCESS =
  "ADD_WORK_CLASSIFICATION_SUCCESS";
export const ADD_WORK_CLASSIFICATION_FAIL = "ADD_WORK_CLASSIFICATION_FAIL";

export const UPDATE_WORK_CLASSIFICATION = "UPDATE_WORK_CLASSIFICATION";
export const UPDATE_WORK_CLASSIFICATION_SUCCESS =
  "UPDATE_WORK_CLASSIFICATION_SUCCESS";
export const UPDATE_WORK_CLASSIFICATION_FAIL =
  "UPDATE_WORK_CLASSIFICATION_FAIL";

export const DELETE_WORK_CLASSIFICATION = "DELETE_WORK_CLASSIFICATION";
export const DELETE_WORK_CLASSIFICATION_SUCCESS =
  "DELETE_WORK_CLASSIFICATION_SUCCESS";
export const DELETE_WORK_CLASSIFICATION_FAIL =
  "DELETE_WORK_CLASSIFICATION_FAIL";
