/* CERTIFICATE GRADES */
export const GET_CERTIFICATE_GRADES = "GET_CERTIFICATE_GRADES";
export const GET_CERTIFICATE_GRADES_SUCCESS = "GET_CERTIFICATE_GRADES_SUCCESS";
export const GET_CERTIFICATE_GRADES_FAIL = "GET_CERTIFICATE_GRADES_FAIL";

export const ADD_NEW_CERTIFICATE_GRADE = "ADD_NEW_CERTIFICATE_GRADE";
export const ADD_CERTIFICATE_GRADE_SUCCESS = "ADD_CERTIFICATE_GRADE_SUCCESS";
export const ADD_CERTIFICATE_GRADE_FAIL = "ADD_CERTIFICATE_GRADE_FAIL";

export const UPDATE_CERTIFICATE_GRADE = "UPDATE_CERTIFICATE_GRADE";
export const UPDATE_CERTIFICATE_GRADE_SUCCESS = "UPDATE_CERTIFICATE_GRADE_SUCCESS";
export const UPDATE_CERTIFICATE_GRADE_FAIL = "UPDATE_CERTIFICATE_GRADE_FAIL";

export const DELETE_CERTIFICATE_GRADE = "DELETE_CERTIFICATE_GRADE";
export const DELETE_CERTIFICATE_GRADE_SUCCESS = "DELETE_CERTIFICATE_GRADE_SUCCESS";
export const DELETE_CERTIFICATE_GRADE_FAIL = "DELETE_CERTIFICATE_GRADE_FAIL";

export const GET_CERTIFICATE_GRADE_DELETED_VALUE = "GET_CERTIFICATE_GRADE_DELETED_VALUE";
export const GET_CERTIFICATE_GRADE_DELETED_VALUE_SUCCESS = "GET_CERTIFICATE_GRADE_DELETED_VALUE_SUCCESS";
export const GET_CERTIFICATE_GRADE_DELETED_VALUE_FAIL = "GET_CERTIFICATE_GRADE_DELETED_VALUE_FAIL";

export const GET_FILTERED_CERTIFICATE_GRADES = "GET_FILTERED_CERTIFICATE_GRADES";
export const GET_FILTERED_CERTIFICATE_GRADES_SUCCESS = "GET_FILTERED_CERTIFICATE_GRADES_SUCCESS";
export const GET_FILTERED_CERTIFICATE_GRADES_FAIL = "GET_FILTERED_CERTIFICATE_GRADES_FAIL";
