/* DECISION_TYPES */
export const GET_DECISIONS_TYPES = "GET_DECISIONS_TYPES";
export const GET_DECISIONS_TYPES_SUCCESS = "GET_DECISIONS_TYPES_SUCCESS";
export const GET_DECISIONS_TYPES_FAIL = "GET_DECISIONS_TYPES_FAIL";

/* DECISION_TYPES PROFILE */
export const GET_DECISION_TYPE_DELETED_VALUE =
  "GET_DECISION_TYPE_DELETED_VALUE";
export const GET_DECISION_TYPE_DELETED_VALUE_SUCCESS =
  "GET_DECISION_TYPE_DELETED_VALUE_SUCCESS";
export const GET_DECISION_TYPE_DELETED_VALUE_FAIL =
  "GET_DECISION_TYPE_DELETED_VALUE_FAIL";

export const ADD_NEW_DECISION_TYPE = "ADD_NEW_DECISION_TYPE";
export const ADD_DECISION_TYPE_SUCCESS = "ADD_DECISION_TYPE_SUCCESS";
export const ADD_DECISION_TYPE_FAIL = "ADD_DECISION_TYPE_FAIL";

export const UPDATE_DECISION_TYPE = "UPDATE_DECISION_TYPE";
export const UPDATE_DECISION_TYPE_SUCCESS = "UPDATE_DECISION_TYPE_SUCCESS";
export const UPDATE_DECISION_TYPE_FAIL = "UPDATE_DECISION_TYPE_FAIL";

export const DELETE_DECISION_TYPE = "DELETE_DECISION_TYPE";
export const DELETE_DECISION_TYPE_SUCCESS = "DELETE_DECISION_TYPE_SUCCESS";
export const DELETE_DECISION_TYPE_FAIL = "DELETE_DECISION_TYPE_FAIL";
