/* STUDENTMANAGEMENTS */
export const GET_STUDENTMANAGEMENTS = "GET_STUDENTMANAGEMENTS"
export const GET_STUDENTMANAGEMENTS_SUCCESS = "GET_STUDENTMANAGEMENTS_SUCCESS"
export const GET_STUDENTMANAGEMENTS_FAIL = "GET_STUDENTMANAGEMENTS_FAIL"

/* STUDENTMANAGEMENTS PROFILE */
export const GET_STUDENTMANAGEMENT_PROFILE = "GET_STUDENTMANAGEMENT_PROFILE"
export const GET_STUDENTMANAGEMENT_PROFILE_SUCCESS = "GET_STUDENTMANAGEMENT_PROFILE_SUCCESS"
export const GET_STUDENTMANAGEMENT_PROFILE_FAIL = "GET_STUDENTMANAGEMENT_PROFILE_FAIL"

export const ADD_NEW_STUDENTMANAGEMENT = "ADD_NEW_STUDENTMANAGEMENT"
export const ADD_STUDENTMANAGEMENT_SUCCESS = "ADD_STUDENTMANAGEMENT_SUCCESS"
export const ADD_STUDENTMANAGEMENT_FAIL = "ADD_STUDENTMANAGEMENT_FAIL"

export const UPDATE_STUDENTMANAGEMENT = "UPDATE_STUDENTMANAGEMENT"
export const UPDATE_STUDENTMANAGEMENT_SUCCESS = "UPDATE_STUDENTMANAGEMENT_SUCCESS"
export const UPDATE_STUDENTMANAGEMENT_FAIL = "UPDATE_STUDENTMANAGEMENT_FAIL"

export const DELETE_STUDENTMANAGEMENT = "DELETE_STUDENTMANAGEMENT"
export const DELETE_STUDENTMANAGEMENT_SUCCESS = "DELETE_STUDENTMANAGEMENT_SUCCESS"
export const DELETE_STUDENTMANAGEMENT_FAIL = "DELETE_STUDENTMANAGEMENT_FAIL"