/* university defenision*/
export const GET_UNIVERSITYINFO = "GET_UNIVERSITYINFO"
export const GET_UNIVERSITYINFO_SUCCESS = "GET_UNIVERSITYS_SUCCESS"
export const GET_UNIVERSITYINFO_FAIL = "GET_UNIVERSITYS_FAIL"

/* Universty actions */

export const UPDATE_UNIVERSITYINFO = "UPDATE_UNIVERSITYINFO"
export const UPDATE_UNIVERSITYINFO_SUCCESS = "UPDATE_UNIVERSITYINFO_SUCCESS"
export const UPDATE_UNIVERSITYINFO_FAIL = "UPDATE_UNIVERSITYINFO_FAIL"


export const ADD_UNIVERSITYINFO = "ADD_UNIVERSITYINFO"
export const ADD_UNIVERSITYINFO_SUCCESS = "ADD_UNIVERSITYINFO_SUCCESS"
export const ADD_UNIVERSITYINFO_FAIL = "ADD_UNIVERSITYINFO_FAIL"