/* WEEKDAYS */
export const GET_WEEKDAYS = "GET_WEEKDAYS"
export const GET_WEEKDAYS_SUCCESS = "GET_WEEKDAYS_SUCCESS"
export const GET_WEEKDAYS_FAIL = "GET_WEEKDAYS_FAIL"

/* WEEKDAY PROFILE */
export const GET_WEEKDAY_PROFILE = "GET_WEEKDAY_PROFILE"
export const GET_WEEKDAY_PROFILE_SUCCESS = "GET_WEEKDAY_PROFILE_SUCCESS"
export const GET_WEEKDAY_PROFILE_FAIL = "GET_WEEKDAY_PROFILE_FAIL"

export const ADD_NEW_WEEKDAY = "ADD_NEW_WEEKDAY"
export const ADD_WEEKDAY_SUCCESS = "ADD_WEEKDAY_SUCCESS"
export const ADD_WEEKDAY_FAIL = "ADD_WEEKDAY_FAIL"

export const UPDATE_WEEKDAY = "UPDATE_WEEKDAY"
export const UPDATE_WEEKDAY_SUCCESS = "UPDATE_WEEKDAY_SUCCESS"
export const UPDATE_WEEKDAY_FAIL = "UPDATE_WEEKDAY_FAIL"

export const DELETE_WEEKDAY = "DELETE_WEEKDAY"
export const DELETE_WEEKDAY_SUCCESS = "DELETE_WEEKDAY_SUCCESS"
export const DELETE_WEEKDAY_FAIL = "DELETE_WEEKDAY_FAIL"