/* UNIVERSITY_STUDENTS */
export const GET_UNIVERSITY_STUDENTS = "GET_UNIVERSITY_STUDENTS"
export const GET_UNIVERSITY_STUDENTS_SUCCESS = "GET_UNIVERSITY_STUDENTS_SUCCESS"
export const GET_UNIVERSITY_STUDENTS_FAIL = "GET_UNIVERSITY_STUDENTS_FAIL"

export const ADD_NEW_UNIVERSITY_STUDENT = "ADD_NEW_UNIVERSITY_STUDENT"
export const ADD_UNIVERSITY_STUDENT_SUCCESS = "ADD_UNIVERSITY_STUDENT_SUCCESS"
export const ADD_UNIVERSITY_STUDENT_FAIL = "ADD_UNIVERSITY_STUDENT_FAIL"

export const UPDATE_UNIVERSITY_STUDENT = "UPDATE_UNIVERSITY_STUDENT"
export const UPDATE_UNIVERSITY_STUDENT_SUCCESS = "UPDATE_UNIVERSITY_STUDENT_SUCCESS"
export const UPDATE_UNIVERSITY_STUDENT_FAIL = "UPDATE_UNIVERSITY_STUDENT_FAIL"

export const DELETE_UNIVERSITY_STUDENT = "DELETE_UNIVERSITY_STUDENT"
export const DELETE_UNIVERSITY_STUDENT_SUCCESS = "DELETE_UNIVERSITY_STUDENT_SUCCESS"
export const DELETE_UNIVERSITY_STUDENT_FAIL = "DELETE_UNIVERSITY_STUDENT_FAIL"

export const GET_UNIVERSITY_STUDENT_BY_ID = "GET_UNIVERSITY_STUDENT_BY_ID"
export const GET_UNIVERSITY_STUDENT_BY_ID_SUCCESS = "GET_UNIVERSITY_STUDENT_BY_ID_SUCCESS"
export const GET_UNIVERSITY_STUDENT_BY_ID_FAIL = "GET_UNIVERSITY_STUDENT_BY_ID_FAIL"

export const GET_UNIVERSITY_STUDENT_REGREQDOCS = "GET_UNIVERSITY_STUDENT_REGREQDOCS"
export const GET_UNIVERSITY_STUDENT_REGREQDOCS_SUCCESS = "GET_UNIVERSITY_STUDENT_REGREQDOCS_SUCCESS"
export const GET_UNIVERSITY_STUDENT_REGREQDOCS_FAIL = "GET_UNIVERSITY_STUDENT_REGREQDOCS_FAIL"

export const UPDATE_UNIVERSITY_STUDENT_REGREQDOC = "UPDATE_UNIVERSITY_STUDENT_REGREQDOC"
export const UPDATE_UNIVERSITY_STUDENT_REGREQDOC_SUCCESS = "UPDATE_UNIVERSITY_STUDENT_REGREQDOC_SUCCESS"
export const UPDATE_UNIVERSITY_STUDENT_REGREQDOC_FAIL = "UPDATE_UNIVERSITY_STUDENT_REGREQDOC_FAIL"

export const GET_STUDENTS_OPT = "GET_STUDENTS_OPT"
export const GET_STUDENTS_OPT_SUCCESS = "GET_STUDENTS_OPT_SUCCESS"
export const GET_STUDENTS_OPT_FAIL = "GET_STUDENTS_OPT_FAIL"

export const ADD_BROTHER = "ADD_BROTHER"
export const ADD_BROTHER_SUCCESS = "ADD_BROTHER_SUCCESS"
export const ADD_BROTHER_FAIL = "ADD_BROTHER_FAIL"

export const GET_BROTHERS = "GET_BROTHERS"
export const GET_BROTHERS_SUCCESS = "GET_BROTHERS_SUCCESS"
export const GET_BROTHERS_FAIL = "GET_BROTHERS_FAIL"

export const DELETE_BROTHER = "DELETE_BROTHER"
export const DELETE_BROTHER_SUCCESS = "DELETE_BROTHER_SUCCESS"
export const DELETE_BROTHER_FAIL = "DELETE_BROTHER_FAIL"

export const UPDATE_BROTHER = "UPDATE_BROTHER"
export const UPDATE_BROTHER_SUCCESS = "UPDATE_BROTHER_SUCCESS"
export const UPDATE_BROTHER_FAIL = "UPDATE_BROTHER_FAIL"

/* STD_RELATIVES */
export const GET_STD_RELATIVES = "GET_STD_RELATIVES"
export const GET_STD_RELATIVES_SUCCESS = "GET_STD_RELATIVES_SUCCESS" 
export const GET_STD_RELATIVES_FAIL = "GET_STD_RELATIVES_FAIL"

export const ADD_NEW_STD_RELATIVE = "ADD_NEW_STD_RELATIVE"
export const ADD_STD_RELATIVE_SUCCESS = "ADD_STD_RELATIVE_SUCCESS"
export const ADD_STD_RELATIVE_FAIL = "ADD_STD_RELATIVE_FAIL"

export const UPDATE_STD_RELATIVE = "UPDATE_STD_RELATIVE"
export const UPDATE_STD_RELATIVE_SUCCESS = "UPDATE_STD_RELATIVE_SUCCESS"
export const UPDATE_STD_RELATIVE_FAIL = "UPDATE_STD_RELATIVE_FAIL"

export const DELETE_STD_RELATIVE = "DELETE_STD_RELATIVE"
export const DELETE_STD_RELATIVE_SUCCESS = "DELETE_STD_RELATIVE_SUCCESS"
export const DELETE_STD_RELATIVE_FAIL = "DELETE_STD_RELATIVE_FAIL"

export const GET_STD_RELATIVE_DELETED_VALUE = "GET_STD_RELATIVE_DELETED_VALUE"
export const GET_STD_RELATIVE_DELETED_VALUE_SUCCESS = "GET_STD_RELATIVE_DELETED_VALUE_SUCCESS"
export const GET_STD_RELATIVE_DELETED_VALUE_FAIL = "GET_STD_RELATIVE_DELETED_VALUE_FAIL"