/* DISMISS_PERIOD_DECREES */
export const GET_DISMISS_PERIOD_DECREES = " GET_DISMISS_PERIOD_DECREES";
export const GET_DISMISS_PERIOD_DECREES_SUCCESS =
  " GET_DISMISS_PERIOD_DECREES_SUCCESS";
export const GET_DISMISS_PERIOD_DECREES_FAIL =
  " GET_DISMISS_PERIOD_DECREES_FAIL";

/* DISMISS_PERIOD_DECREES PROFILE */
export const GET_DISMISS_PERIOD_DECREE_DELETED_VALUE =
  " GET_DISMISS_PERIOD_DECREE_DELETED_VALUE";
export const GET_DISMISS_PERIOD_DECREE_DELETED_VALUE_SUCCESS =
  " GET_DISMISS_PERIOD_DECREE_DELETED_VALUE_SUCCESS";
export const GET_DISMISS_PERIOD_DECREE_DELETED_VALUE_FAIL =
  " GET_DISMISS_PERIOD_DECREE_DELETED_VALUE_FAIL";

export const ADD_NEW_DISMISS_PERIOD_DECREE = "ADD_NEW_DISMISS_PERIOD_DECREE";
export const ADD_DISMISS_PERIOD_DECREE_SUCCESS =
  "ADD_DISMISS_PERIOD_DECREE_SUCCESS";
export const ADD_DISMISS_PERIOD_DECREE_FAIL = "ADD_DISMISS_PERIOD_DECREE_FAIL";

export const UPDATE_DISMISS_PERIOD_DECREE = "UPDATE_DISMISS_PERIOD_DECREE";
export const UPDATE_DISMISS_PERIOD_DECREE_SUCCESS =
  "UPDATE_DISMISS_PERIOD_DECREE_SUCCESS";
export const UPDATE_DISMISS_PERIOD_DECREE_FAIL =
  "UPDATE_DISMISS_PERIOD_DECREE_FAIL";

export const DELETE_DISMISS_PERIOD_DECREE = "DELETE_DISMISS_PERIOD_DECREE";
export const DELETE_DISMISS_PERIOD_DECREE_SUCCESS =
  "DELETE_DISMISS_PERIOD_DECREE_SUCCESS";
export const DELETE_DISMISS_PERIOD_DECREE_FAIL =
  "DELETE_DISMISS_PERIOD_DECREE_FAIL";
