/* TRAINERS */
export const GET_TRAINERS = "GET_TRAINERS";
export const GET_TRAINERS_SUCCESS = "GET_TRAINERS_SUCCESS";
export const GET_TRAINERS_FAIL = "GET_TRAINERS_FAIL";

/* TRAINERS */
export const GET_TRAINER_DELETED_VALUE = "GET_TRAINER_DELETED_VALUE";
export const GET_TRAINER_DELETED_VALUE_SUCCESS =
  "GET_TRAINER_DELETED_VALUE_SUCCESS";
export const GET_TRAINER_DELETED_VALUE_FAIL = "GET_TRAINER_DELETED_VALUE_FAIL";

export const ADD_NEW_TRAINER = "ADD_NEW_TRAINER";
export const ADD_TRAINER_SUCCESS = "ADD_TRAINER_SUCCESS";
export const ADD_TRAINER_FAIL = "ADD_TRAINER_FAIL";

export const UPDATE_TRAINER = "UPDATE_TRAINER";
export const UPDATE_TRAINER_SUCCESS = "UPDATE_TRAINER_SUCCESS";
export const UPDATE_TRAINER_FAIL = "UPDATE_TRAINER_FAIL";

export const DELETE_TRAINER = "DELETE_TRAINER";
export const DELETE_TRAINER_SUCCESS = "DELETE_TRAINER_SUCCESS";
export const DELETE_TRAINER_FAIL = "DELETE_TRAINER_FAIL";
