export const GET_COURSETYPES = "GET_COURSETYPES"
export const GET_COURSETYPES_SUCCESS = "GET_COURSETYPES_SUCCESS"
export const GET_COURSETYPES_FAIL = "GET_COURSETYPES_FAIL"

export const GET_COURSETYPE_DELETED_VALUE = "GET_COURSETYPE_DELETED_VALUE"
export const GET_COURSETYPE_DELETED_VALUE_SUCCESS = "GET_COURSETYPE_DELETED_VALUE_SUCCESS"
export const GET_COURSETYPE_DELETED_VALUE_FAIL = "GET_COURSETYPE_DELETED_VALUE_FAIL"

export const ADD_NEW_COURSETYPE = "ADD_NEW_COURSETYPE"
export const ADD_COURSETYPE_SUCCESS = "ADD_COURSETYPE_SUCCESS"
export const ADD_COURSETYPE_FAIL = "ADD_COURSETYPE_FAIL"

export const UPDATE_COURSETYPE = "UPDATE_COURSETYPE"
export const UPDATE_COURSETYPE_SUCCESS = "UPDATE_COURSETYPE_SUCCESS"
export const UPDATE_COURSETYPE_FAIL = "UPDATE_COURSETYPE_FAIL"

export const DELETE_COURSETYPE = "DELETE_COURSETYPE"
export const DELETE_COURSETYPE_SUCCESS = "DELETE_COURSETYPE_SUCCESS"
export const DELETE_COURSETYPE_FAIL = "DELETE_COURSETYPE_FAIL"