/* GRADES */
export const GET_ENTERED_GRADES = "GET_ENTERED_GRADES"
export const GET_ENTERED_GRADES_SUCCESS = "GET_ENTERED_GRADES_SUCCESS"
export const GET_ENTERED_GRADES_FAIL = "GET_ENTERED_GRADES_FAIL"

export const GET_COURSE_STATISTICS = "GET_COURSE_STATISTICS"
export const GET_COURSE_STATISTICS_SUCCESS = "GET_COURSE_STATISTICS_SUCCESS"
export const GET_COURSE_STATISTICS_FAIL = "GET_COURSE_STATISTICS_FAIL"

export const UPDATE_ENTERED_GRADE = "UPDATE_ENTERED_GRADE"
export const UPDATE_ENTERED_GRADE_SUCCESS = "UPDATE_ENTERED_GRADE_SUCCESS"
export const UPDATE_ENTERED_GRADE_FAIL = "UPDATE_ENTERED_GRADE_FAIL"

export const GET_COURSE_CONTENTS_ENTERED_GRADES = "GET_COURSE_CONTENTS_ENTERED_GRADES"
export const GET_COURSE_CONTENTS_ENTERED_GRADES_SUCCESS = "GET_COURSE_CONTENTS_ENTERED_GRADES_SUCCESS"
export const GET_COURSE_CONTENTS_ENTERED_GRADES_FAIL = "GET_COURSE_CONTENTS_ENTERED_GRADES_FAIL"
