/* academy defenision*/
export const GET_ACADEMYINFO = "GET_ACADEMYINFO"
export const GET_ACADEMYINFO_SUCCESS = "GET_ACADEMYS_SUCCESS"
export const GET_ACADEMYINFO_FAIL = "GET_ACADEMYS_FAIL"

/* academy actions */

export const UPDATE_ACADEMYINFO = "UPDATE_ACADEMYINFO"
export const UPDATE_ACADEMYINFO_SUCCESS = "UPDATE_ACADEMYINFO_SUCCESS"
export const UPDATE_ACADEMYINFO_FAIL = "UPDATE_ACADEMYINFO_FAIL"


export const ADD_ACADEMYINFO = "ADD_ACADEMYINFO"
export const ADD_ACADEMYINFO_SUCCESS = "ADD_ACADEMYINFO_SUCCESS"
export const ADD_ACADEMYINFO_FAIL = "ADD_ACADEMYINFO_FAIL"



