export const GET_COURSE_CONTENTS = "GET_COURSE_CONTENTS"
export const GET_COURSE_CONTENTS_SUCCESS = "GET_COURSE_CONTENTS_SUCCESS"
export const GET_COURSE_CONTENTS_FAIL = "GET_COURSE_CONTENTS_FAIL"

export const ADD_NEW_COURSE_CONTENT = "ADD_NEW_COURSE_CONTENT"
export const ADD_COURSE_CONTENT_SUCCESS = "ADD_COURSE_CONTENT_SUCCESS"
export const ADD_COURSE_CONTENT_FAIL = "ADD_COURSE_CONTENT_FAIL"

export const UPDATE_COURSE_CONTENT = "UPDATE_COURSE_CONTENT"
export const UPDATE_COURSE_CONTENT_SUCCESS = "UPDATE_COURSE_CONTENT_SUCCESS"
export const UPDATE_COURSE_CONTENT_FAIL = "UPDATE_COURSE_CONTENT_FAIL"

export const DELETE_COURSE_CONTENT = "DELETE_COURSE_CONTENT"
export const DELETE_COURSE_CONTENT_SUCCESS = "DELETE_COURSE_CONTENT_SUCCESS"
export const DELETE_COURSE_CONTENT_FAIL = "DELETE_COURSE_CONTENT_FAIL"

export const GET_DEFAULTVALUES = "GET_DEFAULTVALUES"
export const GET_DEFAULTVALUES_SUCCESS = "GET_DEFAULTVALUES_SUCCESS"
export const GET_DEFAULTVALUES_FAIL = "GET_DEFAULTVALUES_FAIL"

export const GET_COURSE_CONTENT_DELETED_VALUE = "GET_COURSE_CONTENT_DELETED_VALUE"
export const GET_COURSE_CONTENT_DELETED_VALUE_SUCCESS = "GET_COURSE_CONTENT_DELETED_VALUE_SUCCESS"
export const GET_COURSE_CONTENT_DELETED_VALUE_FAIL = "GET_COURSE_CONTENT_DELETED_VALUE_FAIL"