/* YEARS */
export const GET_YEARS = "GET_YEARS"
export const GET_YEARS_SUCCESS = "GET_YEARS_SUCCESS"
export const GET_YEARS_FAIL = "GET_YEARS_FAIL"

/* YEAR PROFILE */
export const GET_YEAR_DELETED_VALUE = "GET_YEAR_DELETED_VALUE"
export const GET_YEAR_DELETED_VALUE_SUCCESS = "GET_YEAR_DELETED_VALUE_SUCCESS"
export const GET_YEAR_DELETED_VALUE_FAIL = "GET_YEAR_DELETED_VALUE_FAIL"

export const ADD_NEW_YEAR = "ADD_NEW_YEAR"
export const ADD_YEAR_SUCCESS = "ADD_YEAR_SUCCESS"
export const ADD_YEAR_FAIL = "ADD_YEAR_FAIL"

export const UPDATE_YEAR = "UPDATE_YEAR"
export const UPDATE_YEAR_SUCCESS = "UPDATE_YEAR_SUCCESS"
export const UPDATE_YEAR_FAIL = "UPDATE_YEAR_FAIL"

export const DELETE_YEAR = "DELETE_YEAR"
export const DELETE_YEAR_SUCCESS = "DELETE_YEAR_SUCCESS"
export const DELETE_YEAR_FAIL = "DELETE_YEAR_FAIL"

export const GET_COUNTRY_DELETED_VALUE = "GET_COUNTRY_DELETED_VALUE"
export const GET_COUNTRY_DELETED_VALUE_SUCCESS = "GET_COUNTRY_DELETED_VALUE_SUCCESS"
export const GET_COUNTRY_DELETED_VALUE_FAIL = "GET_COUNTRY_DELETED_VALUE_FAIL"
