/* GRADE_VERSIONS */
export const GET_GRADES_VERSIONS = "GET_GRADES_VERSIONS";
export const GET_GRADES_VERSIONS_SUCCESS = "GET_GRADES_VERSIONS_SUCCESS";
export const GET_GRADES_VERSIONS_FAIL = "GET_GRADES_VERSIONS_FAIL";

/* GRADE_VERSIONS PROFILE */
export const GET_GRADE_VERSION_DELETED_VALUE =
  "GET_GRADE_VERSION_DELETED_VALUE";
export const GET_GRADE_VERSION_DELETED_VALUE_SUCCESS =
  "GET_GRADE_VERSION_DELETED_VALUE_SUCCESS";
export const GET_GRADE_VERSION_DELETED_VALUE_FAIL =
  "GET_GRADE_VERSION_DELETED_VALUE_FAIL";

export const ADD_NEW_GRADE_VERSION = "ADD_NEW_GRADE_VERSION";
export const ADD_GRADE_VERSION_SUCCESS = "ADD_GRADE_VERSION_SUCCESS";
export const ADD_GRADE_VERSION_FAIL = "ADD_GRADE_VERSION_FAIL";

export const UPDATE_GRADE_VERSION = "UPDATE_GRADE_VERSION";
export const UPDATE_GRADE_VERSION_SUCCESS = "UPDATE_GRADE_VERSION_SUCCESS";
export const UPDATE_GRADE_VERSION_FAIL = "UPDATE_GRADE_VERSION_FAIL";

export const DELETE_GRADE_VERSION = "DELETE_GRADE_VERSION";
export const DELETE_GRADE_VERSION_SUCCESS = "DELETE_GRADE_VERSION_SUCCESS";
export const DELETE_GRADE_VERSION_FAIL = "DELETE_GRADE_VERSION_FAIL";
