/* GRADE_VERSIONS */
export const GET_GRADES_VERSIONS = "GET_GRADES_VERSIONS";
export const GET_GRADES_VERSIONS_SUCCESS = "GET_GRADES_VERSIONS_SUCCESS";
export const GET_GRADES_VERSIONS_FAIL = "GET_GRADES_VERSIONS_FAIL";

/* GRADE_VERSIONS PROFILE */
export const GET_GRADE_VERSION_DELETED_VALUE =
  "GET_GRADE_VERSION_DELETED_VALUE";
export const GET_GRADE_VERSION_DELETED_VALUE_SUCCESS =
  "GET_GRADE_VERSION_DELETED_VALUE_SUCCESS";
export const GET_GRADE_VERSION_DELETED_VALUE_FAIL =
  "GET_GRADE_VERSION_DELETED_VALUE_FAIL";

export const ADD_NEW_GRADE_VERSION = "ADD_NEW_GRADE_VERSION";
export const ADD_GRADE_VERSION_SUCCESS = "ADD_GRADE_VERSION_SUCCESS";
export const ADD_GRADE_VERSION_FAIL = "ADD_GRADE_VERSION_FAIL";

export const UPDATE_GRADE_VERSION = "UPDATE_GRADE_VERSION";
export const UPDATE_GRADE_VERSION_SUCCESS = "UPDATE_GRADE_VERSION_SUCCESS";
export const UPDATE_GRADE_VERSION_FAIL = "UPDATE_GRADE_VERSION_FAIL";

export const DELETE_GRADE_VERSION = "DELETE_GRADE_VERSION";
export const DELETE_GRADE_VERSION_SUCCESS = "DELETE_GRADE_VERSION_SUCCESS";
export const DELETE_GRADE_VERSION_FAIL = "DELETE_GRADE_VERSION_FAIL";

export const GET_VERS_GRADE_DELETED_VALUE = "GET_VERS_GRADE_DELETED_VALUE";
export const GET_VERS_GRADE_DELETED_VALUE_FAIL = "GET_VERS_GRADE_DELETED_VALUE_FAIL";
export const GET_VERS_GRADE_DELETED_VALUE_SUCCESS =
  "GET_VERS_GRADE_DELETED_VALUE_SUCCESS";
export const GET_VERS_GRADES = "GET_VERS_GRADES";
export const GET_VERS_GRADES_FAIL = "GET_VERS_GRADES_FAIL";
export const GET_VERS_GRADES_SUCCESS = "GET_VERS_GRADES_SUCCESS";
export const ADD_NEW_VERS_GRADE = "ADD_NEW_VERS_GRADE";
export const ADD_VERS_GRADE_SUCCESS = "ADD_VERS_GRADE_SUCCESS";
export const ADD_VERS_GRADE_FAIL = "ADD_VERS_GRADE_FAIL";
export const UPDATE_VERS_GRADE = "UPDATE_VERS_GRADE";
export const UPDATE_VERS_GRADE_SUCCESS = "UPDATE_VERS_GRADE_SUCCESS";
export const UPDATE_VERS_GRADE_FAIL = "UPDATE_VERS_GRADE_FAIL";
export const DELETE_VERS_GRADE = "DELETE_VERS_GRADE";
export const DELETE_VERS_GRADE_SUCCESS = "DELETE_VERS_GRADE_SUCCESS";
export const DELETE_VERS_GRADE_FAIL = "DELETE_VERS_GRADE_FAIL";

export const GET_RANKS = "GET_RANKS";
export const GET_RANKS_SUCCESS = "GET_RANKS_SUCCESS";
export const GET_RANKS_FAIL = "GET_RANKS_FAIL";

export const GET_FINISH_STATUS = "GET_STATUSES";
export const GET_FINISH_STATUS_SUCCESS = "GET_STATUSES_SUCCESS";
export const GET_FINISH_STATUS_FAIL = "GET_STATUSES_FAIL";


