export const GET_STRUCTURES = "GET_STRUCTURES"
export const GET_STRUCTURES_SUCCESS = "GET_STRUCTURES_SUCCESS"
export const GET_STRUCTURES_FAIL = "GET_STRUCTURES_FAIL"

/* STRUCTURE PROFILE */
export const GET_STRUCTURE_DELETED_VALUE = "GET_STRUCTURE_DELETED_VALUE"
export const GET_STRUCTURE_DELETED_VALUE_SUCCESS = "GET_STRUCTURE_DELETED_VALUE_SUCCESS"
export const GET_STRUCTURE_DELETED_VALUE_FAIL = "GET_STRUCTURE_DELETED_VALUE_FAIL"

export const ADD_NEW_STRUCTURE = "ADD_NEW_STRUCTURE"
export const ADD_STRUCTURE_SUCCESS = "ADD_STRUCTURE_SUCCESS"
export const ADD_STRUCTURE_FAIL = "ADD_STRUCTURE_FAIL"

export const UPDATE_STRUCTURE = "UPDATE_STRUCTURE"
export const UPDATE_STRUCTURE_SUCCESS = "UPDATE_STRUCTURE_SUCCESS"
export const UPDATE_STRUCTURE_FAIL = "UPDATE_STRUCTURE_FAIL"

export const DELETE_STRUCTURE = "DELETE_STRUCTURE"
export const DELETE_STRUCTURE_SUCCESS = "DELETE_STRUCTURE_SUCCESS"
export const DELETE_STRUCTURE_FAIL = "DELETE_STRUCTURE_FAIL"