export const GET_GENDERS= "GET_GENDERS"
export const GET_GENDERS_SUCCESS= "GET_GENDERS_SUCCESS"
export const GET_GENDERS_FAIL="GET_GENDERS_FAIL"

export const ADD_NEW_GENDER= "ADD_NEW_GENDER"
export const ADD_GENDER_SUCCESS= "ADD_GENDER_SUCCESS"
export const ADD_GENDER_FAIL="ADD_GENDER_FAIL"

export const UPDATE_GENDER= "UPDATE_GENDER"
export const UPDATE_GENDER_SUCCESS= "UPDATE_GENDER_SUCCESS"
export const UPDATE_GENDER_FAIL="UPDATE_GENDER__FAIL"

export const DELETE_GENDER= "DELETE_GENDER"
export const DELETE_GENDER_SUCCESS= "DELETE_GENDER_SUCCESS"
export const DELETE_GENDER_FAIL= "DELETE_GENDER_FAIL"

export const GET_GENDER_DELETED_VALUE = "GET_GENDER_DELETED_VALUE"
export const GET_GENDER_DELETED_VALUE_SUCCESS = "GET_GENDER_DELETED_VALUE_SUCCESS"
export const GET_GENDER_DELETED_VALUE_FAIL = "GET_GENDER_DELETED_VALUE_FAIL"