/* DIPLOMALEVELS */
export const GET_DIPLOMALEVELS = "GET_DIPLOMALEVELS"
export const GET_DIPLOMALEVELS_SUCCESS = "GET_DIPLOMALEVELS_SUCCESS"
export const GET_DIPLOMALEVELS_FAIL = "GET_DIPLOMALEVELS_FAIL"

/* DIPLOMALEVELS PROFILE */
export const GET_DIPLOMALEVEL_DELETED_VALUE = "GET_DIPLOMALEVEL_DELETED_VALUE"
export const GET_DIPLOMALEVEL_DELETED_VALUE_SUCCESS = "GET_DIPLOMALEVEL_DELETED_VALUE_SUCCESS"
export const GET_DIPLOMALEVEL_DELETED_VALUE_FAIL = "GET_DIPLOMALEVEL_DELETED_VALUE_FAIL"

export const ADD_NEW_DIPLOMALEVEL = "ADD_NEW_DIPLOMALEVEL"
export const ADD_DIPLOMALEVEL_SUCCESS = "ADD_DIPLOMALEVEL_SUCCESS"
export const ADD_DIPLOMALEVEL_FAIL = "ADD_DIPLOMALEVEL_FAIL"

export const UPDATE_DIPLOMALEVEL = "UPDATE_DIPLOMALEVEL"
export const UPDATE_DIPLOMALEVEL_SUCCESS = "UPDATE_DIPLOMALEVEL_SUCCESS"
export const UPDATE_DIPLOMALEVEL_FAIL = "UPDATE_DIPLOMALEVEL_FAIL"

export const DELETE_DIPLOMALEVEL = "DELETE_DIPLOMALEVEL"
export const DELETE_DIPLOMALEVEL_SUCCESS = "DELETE_DIPLOMALEVEL_SUCCESS"
export const DELETE_DIPLOMALEVEL_FAIL = "DELETE_DIPLOMALEVEL_FAIL"
