/* RELATIVES */
export const GET_RELATIVES = "GET_RELATIVES"
export const GET_RELATIVES_SUCCESS = "GET_RELATIVES_SUCCESS"
export const GET_RELATIVES_FAIL = "GET_RELATIVES_FAIL"

/* RELATIVES PROFILE */
export const GET_RELATIVE_DELETED_VALUE = "GET_RELATIVE_DELETED_VALUE"
export const GET_RELATIVE_DELETED_VALUE_SUCCESS = "GET_RELATIVE_DELETED_VALUE_SUCCESS"
export const GET_RELATIVE_DELETED_VALUE_FAIL = "GET_RELATIVE_DELETED_VALUE_FAIL"

export const ADD_NEW_RELATIVE = "ADD_NEW_RELATIVE"
export const ADD_RELATIVE_SUCCESS = "ADD_RELATIVE_SUCCESS"
export const ADD_RELATIVE_FAIL = "ADD_RELATIVE_FAIL"

export const IMPORT_RELATIVES = "IMPORT_RELATIVES"
export const IMPORT_RELATIVES_SUCCESS = "IMPORT_RELATIVES_SUCCESS"
export const IMPORT_RELATIVES_FAIL = "IMPORT_RELATIVES_FAIL"

export const UPDATE_RELATIVE = "UPDATE_RELATIVE"
export const UPDATE_RELATIVE_SUCCESS = "UPDATE_RELATIVE_SUCCESS"
export const UPDATE_RELATIVE_FAIL = "UPDATE_RELATIVE_FAIL"

export const DELETE_RELATIVE = "DELETE_RELATIVE"
export const DELETE_RELATIVE_SUCCESS = "DELETE_RELATIVE_SUCCESS"
export const DELETE_RELATIVE_FAIL = "DELETE_RELATIVE_FAIL"