/* MOB_APP_FACULTY_ACCS */
export const GET_MOB_APP_FACULTY_ACCS = "GET_MOB_APP_FACULTY_ACCS"
export const GET_MOB_APP_FACULTY_ACCS_SUCCESS = "GET_MOB_APP_FACULTY_ACCS_SUCCESS"
export const GET_MOB_APP_FACULTY_ACCS_FAIL = "GET_MOB_APP_FACULTY_ACCS_FAIL"

/* MOB_APP_FACULTY_ACCS PROFILE*/
export const GET_MOB_APP_FACULTY_ACC_PROFILE = "GET_MOB_APP_FACULTY_ACC_PROFILE"
export const GET_MOB_APP_FACULTY_ACC_PROFILE_SUCCESS = "GET_MOB_APP_FACULTY_ACC_PROFILE_SUCCESS"
export const GET_MOB_APP_FACULTY_ACC_PROFILE_FAIL = "GET_MOB_APP_FACULTY_ACC_PROFILE_FAIL"

export const ADD_NEW_MOB_APP_FACULTY_ACC = "ADD_NEW_MOB_APP_FACULTY_ACC"
export const ADD_MOB_APP_FACULTY_ACC_SUCCESS = "ADD_MOB_APP_FACULTY_ACC_SUCCESS"
export const ADD_MOB_APP_FACULTY_ACC_FAIL = "ADD_MOB_APP_FACULTY_ACC_FAIL"

export const UPDATE_MOB_APP_FACULTY_ACC = "UPDATE_MOB_APP_FACULTY_ACC"
export const UPDATE_MOB_APP_FACULTY_ACC_SUCCESS = "UPDATE_MOB_APP_FACULTY_ACC_SUCCESS"
export const UPDATE_MOB_APP_FACULTY_ACC_FAIL = "UPDATE_MOB_APP_FACULTY_ACC_FAIL"

export const DELETE_MOB_APP_FACULTY_ACC = "DELETE_MOB_APP_FACULTY_ACC"
export const DELETE_MOB_APP_FACULTY_ACC_SUCCESS = "DELETE_MOB_APP_FACULTY_ACC_SUCCESS"
export const DELETE_MOB_APP_FACULTY_ACC_FAIL = "DELETE_MOB_APP_FACULTY_ACC_FAIL"





/* FACULTIES */
export const GET_FACULTIES = "GET_FACULTIES"
export const GET_FACULTIES_SUCCESS = "GET_FACULTIES_SUCCESS"
export const GET_FACULTIES_FAIL = "GET_FACULTIES_FAIL"

export const UPDATE_FACULTY = "UPDATE_FACULTY"
export const UPDATE_FACULTY_SUCCESS = "UPDATE_FACULTY_SUCCESS"
export const UPDATE_FACULTY_FAIL = "UPDATE_FACULTY_FAIL"



export const GET_SETTING = "GET_SETTING"




