/* HIGHSTUDYTYPES */
export const GET_HIGHSTUDYTYPES = "GET_HIGHSTUDYTYPES"
export const GET_HIGHSTUDYTYPES_SUCCESS = "GET_HIGHSTUDYTYPES_SUCCESS"
export const GET_HIGHSTUDYTYPES_FAIL = "GET_HIGHSTUDYTYPES_FAIL"

/* HIGHSTUDYTYPES PROFILE */
export const GET_HIGHSTUDYTYPE_DELETED_VALUE = "GET_HIGHSTUDYTYPE_DELETED_VALUE"
export const GET_HIGHSTUDYTYPE_DELETED_VALUE_SUCCESS = "GET_HIGHSTUDYTYPE_DELETED_VALUE_SUCCESS"
export const GET_HIGHSTUDYTYPE_DELETED_VALUE_FAIL = "GET_HIGHSTUDYTYPE_DELETED_VALUE_FAIL"

export const ADD_NEW_HIGHSTUDYTYPE = "ADD_NEW_HIGHSTUDYTYPE"
export const ADD_HIGHSTUDYTYPE_SUCCESS = "ADD_HIGHSTUDYTYPE_SUCCESS"
export const ADD_HIGHSTUDYTYPE_FAIL = "ADD_HIGHSTUDYTYPE_FAIL"

export const UPDATE_HIGHSTUDYTYPE = "UPDATE_HIGHSTUDYTYPE"
export const UPDATE_HIGHSTUDYTYPE_SUCCESS = "UPDATE_HIGHSTUDYTYPE_SUCCESS"
export const UPDATE_HIGHSTUDYTYPE_FAIL = "UPDATE_HIGHSTUDYTYPE_FAIL"

export const DELETE_HIGHSTUDYTYPE = "DELETE_HIGHSTUDYTYPE"
export const DELETE_HIGHSTUDYTYPE_SUCCESS = "DELETE_HIGHSTUDYTYPE_SUCCESS"
export const DELETE_HIGHSTUDYTYPE_FAIL = "DELETE_HIGHSTUDYTYPE_FAIL"
