/* warining */
export const GET_WARNING_RULES = "GET_WARNING_RULES"
export const GET_WARNING_RULES_SUCCESS = "GET_WARNING_RULES_SUCCESS"
export const GET_WARNING_RULES_FAIL = "GET_WARNING_RULES_FAIL"

export const ADD_NEW_WARNING_RULE = "ADD_NEW_WARNING_RULE"
export const ADD_WARNING_RULE_SUCCESS = "ADD_WARNING_RULE_SUCCESS"
export const ADD_WARNING_RULE_FAIL = "ADD_WARNING_RULE_FAIL"

export const UPDATE_WARNING_RULE = "UPDATE_WARNING_RULE"
export const UPDATE_WARNING_RULE_SUCCESS = "UPDATE_WARNING_RULE_SUCCESS"
export const UPDATE_WARNING_RULE_FAIL = "UPDATE_WARNING_RULE_FAIL"

export const DELETE_WARNING_RULE = "DELETE_WARNING_RULE"
export const DELETE_WARNING_RULE_SUCCESS = "DELETE_WARNING_RULE_SUCCESS"
export const DELETE_WARNING_RULE_FAIL = "DELETE_WARNING_RULE_FAIL"

export const GET_WARNING_RULE_DELETED_VALUE = "GET_WARNING_RULE_DELETED_VALUE"
export const GET_WARNING_RULE_DELETED_VALUE_SUCCESS = "GET_WARNING_RULE_DELETED_VALUE_SUCCESS"
export const GET_WARNING_RULE_DELETED_VALUE_FAIL = "GET_WARNING_RULE_DELETED_VALUE_FAIL"

export const GET_STUDENT_STATES = "GET_STUDENT_STATES"
export const GET_STUDENT_STATES_SUCCESS = "GET_STUDENT_STATES_SUCCESS"
export const GET_STUDENT_STATES_FAIL = "GET_STUDENT_STATES_FAIL"

export const GET_WARNING_RULES_OPT = "GET_WARNING_RULES_OPT"
export const GET_WARNING_RULES_OPT_SUCCESS = "GET_WARNING_RULES_OPT_SUCCESS"
export const GET_WARNING_RULES_OPT_FAIL = "GET_WARNING_RULES_OPT_FAIL"