/* GRADE TYPES */
export const GET_GRADE_TYPES = "GET_GRADE_TYPES"
export const GET_GRADE_TYPES_SUCCESS = "GET_GRADE_TYPES_SUCCESS"
export const GET_GRADE_TYPES_FAIL = "GET_GRADE_TYPES_FAIL"

/* GRADE TYPES PROFILE */
export const GET_GRADE_TYPE_DELETED_VALUE = "GET_GRADE_TYPE_DELETED_VALUE"
export const GET_GRADE_TYPE_DELETED_VALUE_SUCCESS = "GET_GRADE_TYPE_DELETED_VALUE_SUCCESS"
export const GET_GRADE_TYPE_DELETED_VALUE_FAIL = "GET_GRADE_TYPE_DELETED_VALUE_FAIL"

export const ADD_NEW_GRADE_TYPE = "ADD_NEW_GRADE_TYPE"
export const ADD_GRADE_TYPE_SUCCESS = "ADD_GRADE_TYPE_SUCCESS"
export const ADD_GRADE_TYPE_FAIL = "ADD_GRADE_TYPE_FAIL"

export const UPDATE_GRADE_TYPE = "UPDATE_GRADE_TYPE"
export const UPDATE_GRADE_TYPE_SUCCESS = "UPDATE_GRADE_TYPE_SUCCESS"
export const UPDATE_GRADE_TYPE_FAIL = "UPDATE_GRADE_TYPE_FAIL"

export const DELETE_GRADE_TYPE = "DELETE_GRADE_TYPE"
export const DELETE_GRADE_TYPE_SUCCESS = "DELETE_GRADE_TYPE_SUCCESS"
export const DELETE_GRADE_TYPE_FAIL = "DELETE_GRADE_TYPE_FAIL"
