/* FINES */
export const GET_FINES = "GET_FINES";
export const GET_FINES_SUCCESS = "GET_FINES_SUCCESS";
export const GET_FINES_FAIL = "GET_FINES_FAIL";

/* FINES PROFILE */
export const GET_FINE_DELETED_VALUE = "GET_FINE_DELETED_VALUE";
export const GET_FINE_DELETED_VALUE_SUCCESS = "GET_FINE_DELETED_VALUE_SUCCESS";
export const GET_FINE_DELETED_VALUE_FAIL = "GET_FINE_DELETED_VALUE_FAIL";

export const ADD_NEW_FINE = "ADD_NEW_FINE";
export const ADD_FINE_SUCCESS = "ADD_FINE_SUCCESS";
export const ADD_FINE_FAIL = "ADD_FINE_FAIL";

export const UPDATE_FINE = "UPDATE_FINE";
export const UPDATE_FINE_SUCCESS = "UPDATE_FINE_SUCCESS";
export const UPDATE_FINE_FAIL = "UPDATE_FINE_FAIL";

export const DELETE_FINE = "DELETE_FINE";
export const DELETE_FINE_SUCCESS = "DELETE_FINE_SUCCESS";
export const DELETE_FINE_FAIL = "DELETE_FINE_FAIL";
