

/* CURR_SEM_MANS */
export const GET_CURR_SEM_MANS = "GET_CURR_SEM_MANS"
export const GET_CURR_SEM_MANS_SUCCESS = "GET_CURR_SEM_MANS_SUCCESS"
export const GET_CURR_SEM_MANS_FAIL = "GET_CURR_SEM_MANS_FAIL"


export const ADD_NEW_CURR_SEM_MAN = "ADD_NEW_CURR_SEM_MAN"
export const ADD_CURR_SEM_MAN_SUCCESS = "ADD_CURR_SEM_MAN_SUCCESS"
export const ADD_CURR_SEM_MAN_FAIL = "ADD_CURR_SEM_MAN_FAIL"

export const UPDATE_CURR_SEM_MAN = "UPDATE_CURR_SEM_MAN"
export const UPDATE_CURR_SEM_MAN_SUCCESS = "UPDATE_CURR_SEM_MAN_SUCCESS"
export const UPDATE_CURR_SEM_MAN_FAIL = "UPDATE_CURR_SEM_MAN_FAIL"

export const DELETE_CURR_SEM_MAN = "DELETE_CURR_SEM_MAN"
export const DELETE_CURR_SEM_MAN_SUCCESS = "DELETE_CURR_SEM_MAN_SUCCESS"
export const DELETE_CURR_SEM_MAN_FAIL = "DELETE_CURR_SEM_MAN_FAIL"