export const GET_DECISIONS = "GET_DECISIONS";
export const GET_DECISIONS_SUCCESS = "GET_DECISIONS_SUCCESS";
export const GET_DECISIONS_FAIL = "GET_DECISIONS_FAIL";

export const ADD_NEW_DECISION = "ADD_NEW_DECISION";
export const ADD_DECISION_SUCCESS = "ADD_DECISION_SUCCESS";
export const ADD_DECISION_FAIL = "ADD_DECISION_FAIL";

export const UPDATE_DECISION = "UPDATE_DECISION";
export const UPDATE_DECISION_SUCCESS = "UPDATE_DECISION_SUCCESS";
export const UPDATE_DECISION_FAIL = "UPDATE_DECISION__FAIL";

export const DELETE_DECISION = "DELETE_DECISION";
export const DELETE_DECISION_SUCCESS = "DELETE_DECISION_SUCCESS";
export const DELETE_DECISION_FAIL = "DELETE_DECISION_FAIL";

export const GET_DECISION_DELETED_VALUE = "GET_DECISION_DELETED_VALUE";
export const GET_DECISION_DELETED_VALUE_SUCCESS =
  "GET_DECISION_DELETED_VALUE_SUCCESS";
export const GET_DECISION_DELETED_VALUE_FAIL =
  "GET_DECISION_DELETED_VALUE_FAIL";

export const GET_DECISION_MAKERS = "GET_DECISION_MAKERS";
export const GET_DECISION_MAKERS_SUCCESS = "GET_DECISION_MAKERS_SUCCESS";
export const GET_DECISION_MAKERS_FAIL = "GET_DECISION_MAKERS_FAIL";

export const GET_DECISION_STATUS = "GET_DECISION_STATUS";
export const GET_DECISION_STATUS_SUCCESS = "GET_DECISION_STATUS_SUCCESS";
export const GET_DECISION_STATUS_FAIL = "GET_DECISION_STATUS_FAIL";
