/* traineesDeservesDismiss */
export const GET_TRAINEES_DESERVES_DISMISS = "GET_TRAINEES_DESERVES_DISMISS";
export const GET_TRAINEES_DESERVES_DISMISS_SUCCESS =
  "GET_TRAINEES_DESERVES_DISMISS_SUCCESS";
export const GET_TRAINEES_DESERVES_DISMISS_FAIL =
  "GET_TRAINEES_DESERVES_DISMISS_FAIL";

/* traineesDeservesDismiss */
export const GET_TRAINEE_DESERVE_DISMISS_DELETED_VALUE =
  "GET_TRAINEE_DESERVE_DISMISS_DELETED_VALUE";
export const GET_TRAINEE_DESERVE_DISMISS_DELETED_VALUE_SUCCESS =
  "GET_TRAINEE_DESERVE_DISMISS_DELETED_VALUE_SUCCESS";
export const GET_TRAINEE_DESERVE_DISMISS_DELETED_VALUE_FAIL =
  "GET_TRAINEE_DESERVE_DISMISS_DELETED_VALUE_FAIL";

export const ADD_NEW_TRAINEE_DESERVE_DISMISS =
  "ADD_NEW_TRAINEE_DESERVE_DISMISS";
export const ADD_TRAINEE_DESERVE_DISMISS_SUCCESS =
  "ADD_TRAINEE_DESERVE_DISMISS_SUCCESS";
export const ADD_TRAINEE_DESERVE_DISMISS_FAIL =
  "ADD_TRAINEE_DESERVE_DISMISS_FAIL";

export const UPDATE_TRAINEE_DESERVE_DISMISS = "UPDATE_TRAINEE_DESERVE_DISMISS";
export const UPDATE_TRAINEE_DESERVE_DISMISS_SUCCESS =
  "UPDATE_TRAINEE_DESERVE_DISMISS_SUCCESS";
export const UPDATE_TRAINEE_DESERVE_DISMISS_FAIL =
  "UPDATE_TRAINEE_DESERVE_DISMISS_FAIL";

export const DELETE_TRAINEE_DESERVE_DISMISS = "DELETE_TRAINEE_DESERVE_DISMISS";
export const DELETE_TRAINEE_DESERVE_DISMISS_SUCCESS =
  "DELETE_TRAINEE_DESERVE_DISMISS_SUCCESS";
export const DELETE_TRAINEE_DESERVE_DISMISS_FAIL =
  "DELETE_TRAINEE_DESERVE_DISMISS_FAIL";
