export const GET_MISMATCHED_GRADES = "GET_MISMATCHED_GRADES";
export const GET_MISMATCHED_GRADES_SUCCESS = "GET_MISMATCHED_GRADES_SUCCESS";
export const GET_MISMATCHED_GRADES_FAIL = "GET_MISMATCHED_GRADES_FAIL";

export const GET_MISMATCHED_GRADE_DELETED_VALUE =
  "GET_MISMATCHED_GRADE_DELETED_VALUE";
export const GET_MISMATCHED_GRADE_DELETED_VALUE_SUCCESS =
  "GET_MISMATCHED_GRADE_DELETED_VALUE_SUCCESS";
export const GET_MISMATCHED_GRADE_DELETED_VALUE_FAIL =
  "GET_MISMATCHED_GRADE_DELETED_VALUE_FAIL";

export const ADD_NEW_MISMATCHED_GRADE = "ADD_NEW_MISMATCHED_GRADE";
export const ADD_MISMATCHED_GRADE_SUCCESS = "ADD_MISMATCHED_GRADE_SUCCESS";
export const ADD_MISMATCHED_GRADE_FAIL = "ADD_MISMATCHED_GRADE_FAIL";

export const UPDATE_MISMATCHED_GRADE = "UPDATE_MISMATCHED_GRADE";
export const UPDATE_MISMATCHED_GRADE_SUCCESS =
  "UPDATE_MISMATCHED_GRADE_SUCCESS";
export const UPDATE_MISMATCHED_GRADE_FAIL = "UPDATE_MISMATCHED_GRADE_FAIL";

export const DELETE_MISMATCHED_GRADE = "DELETE_MISMATCHED_GRADE";
export const DELETE_MISMATCHED_GRADE_SUCCESS =
  "DELETE_MISMATCHED_GRADE_SUCCESS";
export const DELETE_MISMATCHED_GRADE_FAIL = "DELETE_MISMATCHED_GRADE_FAIL";
