/* WARNINGS_TYPES */
export const GET_WARNINGS_TYPES = "GET_WARNINGS_TYPES";
export const GET_WARNINGS_TYPES_SUCCESS = "GET_WARNINGS_TYPES_SUCCESS";
export const GET_WARNINGS_TYPES_FAIL = "GET_WARNINGS_TYPES_FAIL";

/* WARNING_TYPES PROFILE */
export const GET_WARNING_TYPE_DELETED_VALUE = "GET_WARNING_TYPE_DELETED_VALUE";
export const GET_WARNING_TYPE_DELETED_VALUE_SUCCESS =
  "GET_WARNING_TYPE_DELETED_VALUE_SUCCESS";
export const GET_WARNING_TYPE_DELETED_VALUE_FAIL =
  "GET_WARNING_TYPE_DELETED_VALUE_FAIL";

export const ADD_NEW_WARNING_TYPE = "ADD_NEW_WARNING_TYPE";
export const ADD_WARNING_TYPE_SUCCESS = "ADD_WARNING_TYPE_SUCCESS";
export const ADD_WARNING_TYPE_FAIL = "ADD_WARNING_TYPE_FAIL";

export const UPDATE_WARNING_TYPE = "UPDATE_WARNING_TYPE";
export const UPDATE_WARNING_TYPE_SUCCESS = "UPDATE_WARNING_TYPE_SUCCESS";
export const UPDATE_WARNING_TYPE_FAIL = "UPDATE_WARNING_TYPE_FAIL";

export const DELETE_WARNING_TYPE = "DELETE_WARNING_TYPE";
export const DELETE_WARNING_TYPE_SUCCESS = "DELETE_WARNING_TYPE_SUCCESS";
export const DELETE_WARNING_TYPE_FAIL = "DELETE_WARNING_TYPE_FAIL";
