/* CERTIFICATELEVELS */
export const GET_CERTIFICATELEVELS = "GET_CERTIFICATELEVELS"
export const GET_CERTIFICATELEVELS_SUCCESS = "GET_CERTIFICATELEVELS_SUCCESS"
export const GET_CERTIFICATELEVELS_FAIL = "GET_CERTIFICATELEVELS_FAIL"

/* CERTIFICATELEVELS PROFILE */
export const GET_CERTIFICATELEVEL_DELETED_VALUE = "GET_CERTIFICATELEVEL_DELETED_VALUE"
export const GET_CERTIFICATELEVEL_DELETED_VALUE_SUCCESS = "GET_CERTIFICATELEVEL_DELETED_VALUE_SUCCESS"
export const GET_CERTIFICATELEVEL_DELETED_VALUE_FAIL = "GET_CERTIFICATELEVEL_DELETED_VALUE_FAIL"

export const ADD_NEW_CERTIFICATELEVEL = "ADD_NEW_CERTIFICATELEVEL"
export const ADD_CERTIFICATELEVEL_SUCCESS = "ADD_CERTIFICATELEVEL_SUCCESS"
export const ADD_CERTIFICATELEVEL_FAIL = "ADD_CERTIFICATELEVEL_FAIL"

export const UPDATE_CERTIFICATELEVEL = "UPDATE_CERTIFICATELEVEL"
export const UPDATE_CERTIFICATELEVEL_SUCCESS = "UPDATE_CERTIFICATELEVEL_SUCCESS"
export const UPDATE_CERTIFICATELEVEL_FAIL = "UPDATE_CERTIFICATELEVEL_FAIL"

export const DELETE_CERTIFICATELEVEL = "DELETE_CERTIFICATELEVEL"
export const DELETE_CERTIFICATELEVEL_SUCCESS = "DELETE_CERTIFICATELEVEL_SUCCESS"
export const DELETE_CERTIFICATELEVEL_FAIL = "DELETE_CERTIFICATELEVEL_FAIL"