/* STUDY_PLANS */
export const GET_STUDY_PLANS = "GET_STUDY_PLANS"
export const GET_STUDY_PLANS_SUCCESS = "GET_STUDY_PLANS_SUCCESS"
export const GET_STUDY_PLANS_FAIL = "GET_STUDY_PLANS_FAIL"

/* ALL_STUDY_PLANS */
export const GET_ALL_STUDY_PLANS = "GET_ALL_STUDY_PLANS"
export const GET_ALL_STUDY_PLANS_SUCCESS = "GET_ALL_STUDY_PLANS_SUCCESS"
export const GET_ALL_STUDY_PLANS_FAIL = "GET_ALL_STUDY_PLANS_FAIL"


/* STUDY_PLANS PROFILE*/
export const GET_STUDY_PLAN_PROFILE = "GET_STUDY_PLAN_PROFILE"
export const GET_STUDY_PLAN_PROFILE_SUCCESS = "GET_STUDY_PLAN_PROFILE_SUCCESS"
export const GET_STUDY_PLAN_PROFILE_FAIL = "GET_STUDY_PLAN_PROFILE_FAIL"

export const ADD_NEW_STUDY_PLAN = "ADD_NEW_STUDY_PLAN"
export const ADD_STUDY_PLAN_SUCCESS = "ADD_STUDY_PLAN_SUCCESS"
export const ADD_STUDY_PLAN_FAIL = "ADD_STUDY_PLAN_FAIL"

export const UPDATE_STUDY_PLAN = "UPDATE_STUDY_PLAN"
export const UPDATE_STUDY_PLAN_SUCCESS = "UPDATE_STUDY_PLAN_SUCCESS"
export const UPDATE_STUDY_PLAN_FAIL = "UPDATE_STUDY_PLAN_FAIL"

export const DELETE_STUDY_PLAN = "DELETE_STUDY_PLAN"
export const DELETE_STUDY_PLAN_SUCCESS = "DELETE_STUDY_PLAN_SUCCESS"
export const DELETE_STUDY_PLAN_FAIL = "DELETE_STUDY_PLAN_FAIL"


/*FILTERED_COURSES*/
export const GET_FILTERED_COURSES = "GET_FILTERED_COURSES"
export const GET_FILTERED_COURSES_SUCCESS = "GET_FILTERED_COURSES_SUCCESS"
export const GET_FILTERED_COURSES_FAIL = "GET_FILTERED_COURSES_FAIL"



/*PLAN_HOURS*/
export const GET_PLAN_HOURS = "GET_PLAN_HOURS"
export const GET_PLAN_HOURS_SUCCESS = "GET_PLAN_HOURS_SUCCESS"
export const GET_PLAN_HOURS_FAIL = "GET_PLAN_HOURS_FAIL"

export const ADD_NEW_PLAN_HOUR = "ADD_NEW_PLAN_HOUR"
export const ADD_PLAN_HOUR_SUCCESS = "ADD_PLAN_HOUR_SUCCESS"
export const ADD_PLAN_HOUR_FAIL = "ADD_PLAN_HOUR_FAIL"

export const UPDATE_PLAN_HOUR = "UPDATE_PLAN_HOUR"
export const UPDATE_PLAN_HOUR_SUCCESS = "UPDATE_PLAN_HOUR_SUCCESS"
export const UPDATE_PLAN_HOUR_FAIL = "UPDATE_PLAN_HOUR_FAIL"


/* GENERALIZE STUDY PLANS*/

export const GENERALIZE_STUDY_PLANS = "GENERALIZE_STUDY_PLANS"
export const GENERALIZE_STUDY_PLANS_SUCCESS = "GENERALIZE_STUDY_PLANS_SUCCESS"
export const GENERALIZE_STUDY_PLANS_FAIL = "GENERALIZE_STUDY_PLANS_FAIL"

