/* GRADES */
export const GET_GRADES = "GET_GRADES";
export const GET_GRADES_SUCCESS = "GET_GRADES_SUCCESS";
export const GET_GRADES_FAIL = "GET_GRADES_FAIL";

export const ADD_NEW_GRADE = "ADD_NEW_GRADE";
export const ADD_GRADE_SUCCESS = "ADD_GRADE_SUCCESS";
export const ADD_GRADE_FAIL = "ADD_GRADE_FAIL";

export const UPDATE_GRADE = "UPDATE_GRADE";
export const UPDATE_GRADE_SUCCESS = "UPDATE_GRADE_SUCCESS";
export const UPDATE_GRADE_FAIL = "UPDATE_GRADE_FAIL";

export const DELETE_GRADE = "DELETE_GRADE";
export const DELETE_GRADE_SUCCESS = "DELETE_GRADE_SUCCESS";
export const DELETE_GRADE_FAIL = "DELETE_GRADE_FAIL";

export const GET_GRADE_DELETED_VALUE = "GET_GRADE_DELETED_VALUE";
export const GET_GRADE_DELETED_VALUE_SUCCESS =
  "GET_GRADE_DELETED_VALUE_SUCCESS";
export const GET_GRADE_DELETED_VALUE_FAIL =
  "GET_CERTIFICATE_DELETED_VALUE_FAIL";

export const GET_FILTERED_GRADES = "GET_FILTERED_GRADES";
export const GET_FILTERED_GRADES_SUCCESS = "GET_FILTERED_GRADES_SUCCESS";
export const GET_FILTERED_GRADES_FAIL = "GET_FILTERED_GRADES_FAIL";
