/*  GRADES */
export const GET_GRADES = "GET_GRADES";
export const GET_GRADES_SUCCESS = "GET_GRADES_SUCCESS";
export const GET_GRADES_FAIL = "GET_GRADES_FAIL";

export const UPDATE_GRADE = "UPDATE_GRADE";
export const UPDATE_GRADE_SUCCESS = "UPDATE_GRADE_SUCCESS";
export const UPDATE_GRADE_FAIL = "UPDATE_GRADE_FAIL";

export const GET_COURSE_CONTENTS_ENTERED_GRADES =
  "GET_COURSE_CONTENTS_ENTERED_GRADES";
export const GET_COURSE_CONTENTS_ENTERED_GRADES_SUCCESS =
  "GET_COURSE_CONTENTS_ENTERED_GRADES_SUCCESS";
export const GET_COURSE_CONTENTS_ENTERED_GRADES_FAIL =
  "GET_COURSE_CONTENTS_ENTERED_GRADES_FAIL";

export const GET_COURSES_OPT = "GET_COURSES_OPT";
export const GET_COURSES_OPT_SUCCESS = "GET_COURSES_OPT_SUCCESS";
export const GET_COURSES_OPT_FAIL = "GET_COURSES_OPT_FAIL";
