/* GRADES */
export const GET_GRADES = "GET_GRADES"
export const GET_GRADES_SUCCESS = "GET_GRADES_SUCCESS"
export const GET_GRADES_FAIL = "GET_GRADES_FAIL"

export const GET_COURSE_STATISTICS = "GET_COURSE_STATISTICS"
export const GET_COURSE_STATISTICS_SUCCESS = "GET_COURSE_STATISTICS_SUCCESS"
export const GET_COURSE_STATISTICS_FAIL = "GET_COURSE_STATISTICS_FAIL"

export const UPDATE_GRADE = "UPDATE_GRADE"
export const UPDATE_GRADE_SUCCESS = "UPDATE_GRADE_SUCCESS"
export const UPDATE_GRADE_FAIL = "UPDATE_GRADE_FAIL"

export const GET_COURSE_CONTENTS_GRADES = "GET_COURSE_CONTENTS_GRADES"
export const GET_COURSE_CONTENTS_GRADES_SUCCESS = "GET_COURSE_CONTENTS_GRADES_SUCCESS"
export const GET_COURSE_CONTENTS_GRADES_FAIL = "GET_COURSE_CONTENTS_GRADES_FAIL"


