/* EXAMS_ATTENDANCE */
export const GET_EXAMS_ATTENDANCE = "GET_EXAMS_ATTENDANCE";
export const GET_EXAMS_ATTENDANCE_SUCCESS = "GET_EXAMS_ATTENDANCE_SUCCESS";
export const GET_EXAMS_ATTENDANCE_FAIL = "GET_EXAMS_ATTENDANCE_FAIL";

export const ADD_NEW_EXAM_ATTENDANCE = "ADD_NEW_EXAM_ATTENDANCE";
export const ADD_EXAM_ATTENDANCE_SUCCESS = "ADD_EXAM_ATTENDANCE_SUCCESS";
export const ADD_EXAM_ATTENDANCE_FAIL = "ADD_EXAM_ATTENDANCE_FAIL";

export const UPDATE_EXAM_ATTENDANCE = "UPDATE_EXAM_ATTENDANCE";
export const UPDATE_EXAM_ATTENDANCE_SUCCESS = "UPDATE_EXAM_ATTENDANCE_SUCCESS";
export const UPDATE_EXAM_ATTENDANCE_FAIL = "UPDATE_EXAM_ATTENDANCE_FAIL";

export const DELETE_EXAM_ATTENDANCE = "DELETE_EXAM_ATTENDANCE";
export const DELETE_EXAM_ATTENDANCE_SUCCESS = "DELETE_EXAM_ATTENDANCE_SUCCESS";
export const DELETE_EXAM_ATTENDANCE_FAIL = "DELETE_EXAM_ATTENDANCE_FAIL";

export const GET_EXAM_ATTENDANCE_DELETED_VALUE =
  "GET_EXAM_ATTENDANCE_DELETED_VALUE";
export const GET_EXAM_ATTENDANCE_DELETED_VALUE_SUCCESS =
  "GET_EXAM_ATTENDANCE_DELETED_VALUE_SUCCESS";
export const GET_EXAM_ATTENDANCE_DELETED_VALUE_FAIL =
  "GET_EXAM_ATTENDANCE_DELETED_VALUE_FAIL";

/* ATTEND STATUS */
export const GET_ATTEND_STATUS = "GET_ATTEND_STATUS";
export const GET_ATTEND_STATUS_SUCCESS = "GET_ATTEND_STATUS_SUCCESS";
export const GET_ATTEND_STATUS_FAIL = "GET_ATTEND_STATUS_FAIL";

/* Exam Name */
export const GET_EXAMS_NAMES = "GET_EXAMS_NAMES";
export const GET_EXAMS_NAMES_SUCCESS = "GET_EXAMS_NAMES_SUCCESS";
export const GET_EXAMS_NAMES_FAIL = "GET_EXAMS_NAMES_FAIL";

/* Exam periods */
export const GET_EXAMS_PERIODS = "GET_EXAMS_PERIODS";
export const GET_EXAMS_PERIODS_SUCCESS = "GET_EXAMS_PERIODS_SUCCESS";
export const GET_EXAMS_PERIODS_FAIL = "GET_EXAMS_PERIODS_FAIL";
