/* TRANSPORT_LINES */
export const GET_TRANSPORT_LINES = "GET_TRANSPORT_LINES"
export const GET_TRANSPORT_LINES_SUCCESS = "GET_TRANSPORT_LINES_SUCCESS"
export const GET_TRANSPORT_LINES_FAIL = "GET_TRANSPORT_LINES_FAIL"


export const ADD_NEW_TRANSPORT_LINE = "ADD_NEW_TRANSPORT_LINE"
export const ADD_TRANSPORT_LINE_SUCCESS = "ADD_TRANSPORT_LINE_SUCCESS"
export const ADD_TRANSPORT_LINE_FAIL = "ADD_TRANSPORT_LINE_FAIL"

export const UPDATE_TRANSPORT_LINE = "UPDATE_TRANSPORT_LINE"
export const UPDATE_TRANSPORT_LINE_SUCCESS = "UPDATE_TRANSPORT_LINE_SUCCESS"
export const UPDATE_TRANSPORT_LINE_FAIL = "UPDATE_TRANSPORT_LINE_FAIL"

export const DELETE_TRANSPORT_LINE = "DELETE_TRANSPORT_LINE"
export const DELETE_TRANSPORT_LINE_SUCCESS = "DELETE_TRANSPORT_LINE_SUCCESS"
export const DELETE_TRANSPORT_LINE_FAIL = "DELETE_TRANSPORT_LINE_FAIL"

/* TRANSPORT_LINE_DETAILS */
export const GET_TRANSPORT_LINE_DETAILS = "GET_TRANSPORT_LINE_DETAILS"
export const GET_TRANSPORT_LINE_DETAILS_SUCCESS = "GET_TRANSPORT_LINE_DETAILS_SUCCESS"
export const GET_TRANSPORT_LINE_DETAILS_FAIL = "GET_TRANSPORT_LINE_DETAILS_FAIL"


export const ADD_NEW_TRANSPORT_LINE_DETAIL = "ADD_NEW_TRANSPORT_LINE_DETAIL"
export const ADD_TRANSPORT_LINE_DETAIL_SUCCESS = "ADD_TRANSPORT_LINE_DETAIL_SUCCESS"
export const ADD_TRANSPORT_LINE_DETAIL_FAIL = "ADD_TRANSPORT_LINE_DETAIL_FAIL"

export const UPDATE_TRANSPORT_LINE_DETAIL = "UPDATE_TRANSPORT_LINE_DETAIL"
export const UPDATE_TRANSPORT_LINE_DETAIL_SUCCESS = "UPDATE_TRANSPORT_LINE_DETAIL_SUCCESS"
export const UPDATE_TRANSPORT_LINE_DETAIL_FAIL = "UPDATE_TRANSPORT_LINE_DETAIL_FAIL"

export const DELETE_TRANSPORT_LINE_DETAIL = "DELETE_TRANSPORT_LINE_DETAIL"
export const DELETE_TRANSPORT_LINE_DETAIL_SUCCESS = "DELETE_TRANSPORT_LINE_DETAIL_SUCCESS"
export const DELETE_TRANSPORT_LINE_DETAIL_FAIL = "DELETE_TRANSPORT_LINE_DETAIL_FAIL"

export const GET_TRANSPORT_LINE_DELETED_VALUE = "GET_TRANSPORT_LINE_DELETED_VALUE"
export const GET_TRANSPORT_LINE_DELETED_VALUE_SUCCESS = "GET_TRANSPORT_LINE_DELETED_VALUE_SUCCESS"
export const GET_TRANSPORT_LINE_DELETED_VALUE_FAIL = "GET_TRANSPORT_LINE_DELETED_VALUE_FAIL"

export const GET_TRANSPORT_LINE_DETAILS_DELETED_VALUE = "GET_TRANSPORT_LINE_DETAILS_DELETED_VALUE"
export const GET_TRANSPORT_LINE_DETAILS_DELETED_VALUE_SUCCESS = "GET_TRANSPORT_LINE_DETAILS_DELETED_VALUE_SUCCESS"
export const GET_TRANSPORT_LINE_DETAILS_DELETED_VALUE_FAIL = "GET_TRANSPORT_LINE_DETAILS_DELETED_VALUE_FAIL"

export const GET_STDS_TRANSPORT_LINE = "GET_STDS_TRANSPORT_LINE"
export const GET_STDS_TRANSPORT_LINE_SUCCESS = "GET_STDS_TRANSPORT_LINE_SUCCESS"
export const GET_STDS_TRANSPORT_LINE_FAIL = "GET_STDS_TRANSPORT_LINE_FAIL"

export const ADD_NEW_STD_TRANSPORT_LINE = "ADD_NEW_STD_TRANSPORT_LINE"
export const ADD_STD_TRANSPORT_LINE_SUCCESS = "ADD_STD_TRANSPORT_LINE_SUCCESS"
export const ADD_STD_TRANSPORT_LINE_FAIL = "ADD_STD_TRANSPORT_LINE_FAIL"

export const UPDATE_STD_TRANSPORT_LINE = "UPDATE_STD_TRANSPORT_LINE"
export const UPDATE_STD_TRANSPORT_LINE_SUCCESS = "UPDATE_STD_TRANSPORT_LINE_SUCCESS"
export const UPDATE_STD_TRANSPORT_LINE_FAIL = "UPDATE_STD_TRANSPORT_LINE_FAIL"

export const DELETE_STD_TRANSPORT_LINE = "DELETE_STD_TRANSPORT_LINE"
export const DELETE_STD_TRANSPORT_LINE_SUCCESS = "DELETE_STD_TRANSPORT_LINE_SUCCESS"
export const DELETE_STD_TRANSPORT_LINE_FAIL = "DELETE_STD_TRANSPORT_LINE_FAIL"

export const GET_STD_TRANSPORT_LINE_DELETED_VALUE = "GET_STD_TRANSPORT_LINE_DELETED_VALUE"
export const GET_STD_TRANSPORT_LINE_DELETED_VALUE_SUCCESS = "GET_STD_TRANSPORT_LINE_DELETED_VALUE_SUCCESS"
export const GET_STD_TRANSPORT_LINE_DELETED_VALUE_FAIL = "GET_STD_TRANSPORT_LINE_DELETED_VALUE_FAIL"

export const GET_UNIV_STD_DATA_LIST = "GET_UNIV_STD_DATA_LIST"
export const GET_UNIV_STD_DATA_LIST_SUCCESS = "GET_UNIV_STD_DATA_LIST_SUCCESS"
export const GET_UNIV_STD_DATA_LIST_FAIL = "GET_UNIV_STD_DATA_LIST_FAIL"
