/* REQUESTS */
export const GET_REQUESTS = "GET_REQUESTS";
export const GET_REQUESTS_SUCCESS = "GET_REQUESTS_SUCCESS";
export const GET_REQUESTS_FAIL = "GET_REQUESTS_FAIL";

/* REQUESTS PROFILE */
export const GET_REQUEST_DELETED_VALUE = "GET_REQUEST_DELETED_VALUE";
export const GET_REQUEST_DELETED_VALUE_SUCCESS = "GET_REQUEST_DELETED_VALUE_SUCCESS";
export const GET_REQUEST_DELETED_VALUE_FAIL = "GET_REQUEST_DELETED_VALUE_FAIL";

export const ADD_NEW_REQUEST = "ADD_NEW_REQUEST";
export const ADD_REQUEST_SUCCESS = "ADD_REQUEST_SUCCESS";
export const ADD_REQUEST_FAIL = "ADD_REQUEST_FAIL";

export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const UPDATE_REQUEST_SUCCESS = "UPDATE_REQUEST_SUCCESS";
export const UPDATE_REQUEST_FAIL = "UPDATE_REQUEST_FAIL";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
export const DELETE_REQUEST_FAIL = "DELETE_REQUEST_FAIL";
