export const GET_UNI_DOCUMENTS = "GET_UNI_DOCUMENTS"
export const GET_UNI_DOCUMENTS_SUCCESS = "GET_UNI_DOCUMENTS_SUCCESS"
export const GET_UNI_DOCUMENTS_FAIL = "GET_UNI_DOCUMENTS_FAIL"

export const GET_UNI_DOCUMENT_DELETED_VALUE = "GET_UNI_DOCUMENT_DELETED_VALUE"
export const GET_UNI_DOCUMENT_DELETED_VALUE_SUCCESS = "GET_UNI_DOCUMENT_DELETED_VALUE_SUCCESS"
export const GET_UNI_DOCUMENT_DELETED_VALUE_FAIL = "GET_UNI_DOCUMENT_DELETED_VALUE_FAIL"

export const ADD_NEW_UNI_DOCUMENT = "ADD_NEW_UNI_DOCUMENT"
export const ADD_UNI_DOCUMENT_SUCCESS = "ADD_UNI_DOCUMENT_SUCCESS"
export const ADD_UNI_DOCUMENT_FAIL = "ADD_UNI_DOCUMENT_FAIL"

export const UPDATE_UNI_DOCUMENT = "UPDATE_UNI_DOCUMENT"
export const UPDATE_UNI_DOCUMENT_SUCCESS = "UPDATE_UNI_DOCUMENT_SUCCESS"
export const UPDATE_UNI_DOCUMENT_FAIL = "UPDATE_UNI_DOCUMENT_FAIL"

export const DELETE_UNI_DOCUMENT = "DELETE_UNI_DOCUMENT"
export const DELETE_UNI_DOCUMENT_SUCCESS = "DELETE_UNI_DOCUMENT_SUCCESS"
export const DELETE_UNI_DOCUMENT_FAIL = "DELETE_UNI_DOCUMENT_FAIL"