export const GET_DECREES = "GET_DECREES";
export const GET_DECREES_SUCCESS = "GET_DECREES_SUCCESS";
export const GET_DECREES_FAIL = "GET_DECREES_FAIL";

export const ADD_NEW_DECREE = "ADD_NEW_DECREE";
export const ADD_DECREE_SUCCESS = "ADD_DECREE_SUCCESS";
export const ADD_DECREE_FAIL = "ADD_DECREE_FAIL";

export const UPDATE_DECREE = "UPDATE_DECREE";
export const UPDATE_DECREE_SUCCESS = "UPDATE_DECREE_SUCCESS";
export const UPDATE_DECREE_FAIL = "UPDATE_DECREE__FAIL";

export const DELETE_DECREE = "DELETE_DECREE";
export const DELETE_DECREE_SUCCESS = "DELETE_DECREE_SUCCESS";
export const DELETE_DECREE_FAIL = "DELETE_DECREE_FAIL";

export const GET_DECREE_DELETED_VALUE = "GET_DECREE_DELETED_VALUE";
export const GET_DECREE_DELETED_VALUE_SUCCESS =
  "GET_DECREE_DELETED_VALUE_SUCCESS";
export const GET_DECREE_DELETED_VALUE_FAIL = "GET_DECREE_DELETED_VALUE_FAIL";

export const GET_DECREE_CATEGORIES = "GET_DECREE_CATEGORIES";
export const GET_DECREE_CATEGORIES_SUCCESS = "GET_DECREE_CATEGORIES_SUCCESS";
export const GET_DECREE_CATEGORIES_FAIL = "GET_DECREE_CATEGORIES_FAIL";

export const GET_DECREES_RULES_REASONS = "GET_DECREES_RULES_REASONS";
export const GET_DECREES_RULES_REASONS_SUCCESS =
  "GET_DECREES_RULES_REASONS_SUCCESS";
export const GET_DECREES_RULES_REASONS_FAIL = "GET_DECREES_RULES_REASONS_FAIL";

export const ADD_NEW_DECREES_RULES_REASON = "ADD_NEW_DECREES_RULES_REASON";
export const ADD_DECREES_RULES_REASON_SUCCESS =
  "ADD_DECREES_RULES_REASON_SUCCESS";
export const ADD_DECREES_RULES_REASON_FAIL = "ADD_DECREES_RULES_REASON_FAIL";

export const UPDATE_DECREES_RULES_REASON = "UPDATE_DECREES_RULES_REASON";
export const UPDATE_DECREES_RULES_REASON_SUCCESS =
  "UPDATE_DECREES_RULES_REASON_SUCCESS";
export const UPDATE_DECREES_RULES_REASON_FAIL =
  "UPDATE_DECREES_RULES_REASON_FAIL";

export const DELETE_DECREES_RULES_REASON = "DELETE_DECREES_RULES_REASON";
export const DELETE_DECREES_RULES_REASON_SUCCESS =
  "DELETE_DECREES_RULES_REASON_SUCCESS";
export const DELETE_DECREES_RULES_REASON_FAIL =
  "DELETE_DECREES_RULES_REASON_FAIL";

export const GET_DECREES_RULES_REASON_DELETED_VALUE =
  "GET_DECREES_RULES_REASON_DELETED_VALUE";
export const GET_DECREES_RULES_REASON_DELETED_VALUE_SUCCESS =
  "GET_DECREES_RULES_REASON_DELETED_VALUE_SUCCESS";
export const GET_DECREES_RULES_REASON_DELETED_VALUE_FAIL =
  "GET_DECREES_RULES_REASON_DELETED_VALUE_FAIL";

export const GET_DECREES_RULES_CANCELED_REASONS =
  "GET_DECREES_RULES_CANCELED_REASONS";
export const GET_DECREES_RULES_CANCELED_REASONS_SUCCESS =
  "GET_DECREES_RULES_CANCELED_REASONS_SUCCESS";
export const GET_DECREES_RULES_CANCELED_REASONS_FAIL =
  "GET_DECREES_RULES_CANCELED_REASONS_FAIL";

export const ADD_NEW_DECREES_RULES_CANCELED_REASON =
  "ADD_NEW_DECREES_RULES_CANCELED_REASON";
export const ADD_DECREES_RULES_CANCELED_REASON_SUCCESS =
  "ADD_DECREES_RULES_CANCELED_REASON_SUCCESS";
export const ADD_DECREES_RULES_CANCELED_REASON_FAIL =
  "ADD_DECREES_RULES_CANCELED_REASON_FAIL";

export const UPDATE_DECREES_RULES_CANCELED_REASON =
  "UPDATE_DECREES_RULES_CANCELED_REASON";
export const UPDATE_DECREES_RULES_CANCELED_REASON_SUCCESS =
  "UPDATE_DECREES_RULES_CANCELED_REASON_SUCCESS";
export const UPDATE_DECREES_RULES_CANCELED_REASON_FAIL =
  "UPDATE_DECREES_RULES_CANCELED_REASON_FAIL";

export const DELETE_DECREES_RULES_CANCELED_REASON =
  "DELETE_DECREES_RULES_CANCELED_REASON";
export const DELETE_DECREES_RULES_CANCELED_REASON_SUCCESS =
  "DELETE_DECREES_RULES_CANCELED_REASON_SUCCESS";
export const DELETE_DECREES_RULES_CANCELED_REASON_FAIL =
  "DELETE_DECREES_RULES_CANCELED_REASON_FAIL";

export const GET_DECREES_RULES_CANCELED_REASON_DELETED_VALUE =
  "GET_DECREES_RULES_CANCELED_REASON_DELETED_VALUE";
export const GET_DECREES_RULES_CANCELED_REASON_DELETED_VALUE_SUCCESS =
  "GET_DECREES_RULES_CANCELED_REASON_DELETED_VALUE_SUCCESS";
export const GET_DECREES_RULES_CANCELED_REASON_DELETED_VALUE_FAIL =
  "GET_DECREES_RULES_CANCELED_REASON_DELETED_VALUE_FAIL";

export const GET_DECREES_RULES_ROLES = "GET_DECREES_RULES_ROLESS";
export const GET_DECREES_RULES_ROLES_SUCCESS =
  "GET_DECREES_RULES_ROLESS_SUCCESS";
export const GET_DECREES_RULES_ROLES_FAIL = "GET_DECREES_RULES_ROLESS_FAIL";

export const ADD_NEW_DECREES_RULES_ROLES = "ADD_NEW_DECREES_RULES_ROLES";
export const ADD_DECREES_RULES_ROLES_SUCCESS =
  "ADD_DECREES_RULES_ROLES_SUCCESS";
export const ADD_DECREES_RULES_ROLES_FAIL = "ADD_DECREES_RULES_ROLES_FAIL";

export const UPDATE_DECREES_RULES_ROLES = "UPDATE_DECREES_RULES_ROLES";
export const UPDATE_DECREES_RULES_ROLES_SUCCESS =
  "UPDATE_DECREES_RULES_ROLES_SUCCESS";
export const UPDATE_DECREES_RULES_ROLES_FAIL =
  "UPDATE_DECREES_RULES_ROLES_FAIL";

export const DELETE_DECREES_RULES_ROLES = "DELETE_DECREES_RULES_ROLES";
export const DELETE_DECREES_RULES_ROLES_SUCCESS =
  "DELETE_DECREES_RULES_ROLES_SUCCESS";
export const DELETE_DECREES_RULES_ROLES_FAIL =
  "DELETE_DECREES_RULES_ROLES_FAIL";

export const GET_DECREES_RULES_ROLES_DELETED_VALUE =
  "GET_DECREES_RULES_ROLES_DELETED_VALUE";
export const GET_DECREES_RULES_ROLES_DELETED_VALUE_SUCCESS =
  "GET_DECREES_RULES_ROLES_DELETED_VALUE_SUCCESS";
export const GET_DECREES_RULES_ROLES_DELETED_VALUE_FAIL =
  "GET_DECREES_RULES_ROLES_DELETED_VALUE_FAIL";
