/* LETTER_GRADES */
export const GET_LETTER_GRADES = "GET_LETTER_GRADES"
export const GET_LETTER_GRADES_SUCCESS = "GET_LETTER_GRADES_SUCCESS"
export const GET_LETTER_GRADES_FAIL = "GET_LETTER_GRADES_FAIL"


export const ADD_NEW_LETTER_GRADE = "ADD_NEW_LETTER_GRADE"
export const ADD_LETTER_GRADE_SUCCESS = "ADD_LETTER_GRADE_SUCCESS"
export const ADD_LETTER_GRADE_FAIL = "ADD_LETTER_GRADE_FAIL"

export const UPDATE_LETTER_GRADE = "UPDATE_LETTER_GRADE"
export const UPDATE_LETTER_GRADE_SUCCESS = "UPDATE_LETTER_GRADE_SUCCESS"
export const UPDATE_LETTER_GRADE_FAIL = "UPDATE_LETTER_GRADE_FAIL"

export const DELETE_LETTER_GRADE = "DELETE_LETTER_GRADE"
export const DELETE_LETTER_GRADE_SUCCESS = "DELETE_LETTER_GRADE_SUCCESS"
export const DELETE_LETTER_GRADE_FAIL = "DELETE_LETTER_GRADE_FAIL"

/* LETTER_GRADE_DETAILS */
export const GET_LETTER_GRADE_DETAILS = "GET_LETTER_GRADE_DETAILS"
export const GET_LETTER_GRADE_DETAILS_SUCCESS = "GET_LETTER_GRADE_DETAILS_SUCCESS"
export const GET_LETTER_GRADE_DETAILS_FAIL = "GET_LETTER_GRADE_DETAILS_FAIL"


export const ADD_NEW_LETTER_GRADE_DETAIL = "ADD_NEW_LETTER_GRADE_DETAIL"
export const ADD_LETTER_GRADE_DETAIL_SUCCESS = "ADD_LETTER_GRADE_DETAIL_SUCCESS"
export const ADD_LETTER_GRADE_DETAIL_FAIL = "ADD_LETTER_GRADE_DETAIL_FAIL"

export const UPDATE_LETTER_GRADE_DETAIL = "UPDATE_LETTER_GRADE_DETAIL"
export const UPDATE_LETTER_GRADE_DETAIL_SUCCESS = "UPDATE_LETTER_GRADE_DETAIL_SUCCESS"
export const UPDATE_LETTER_GRADE_DETAIL_FAIL = "UPDATE_LETTER_GRADE_DETAIL_FAIL"

export const DELETE_LETTER_GRADE_DETAIL = "DELETE_LETTER_GRADE_DETAIL"
export const DELETE_LETTER_GRADE_DETAIL_SUCCESS = "DELETE_LETTER_GRADE_DETAIL_SUCCESS"
export const DELETE_LETTER_GRADE_DETAIL_FAIL = "DELETE_LETTER_GRADE_DETAIL_FAIL"

export const GET_LETTER_GRADE_DELETED_VALUE = "GET_LETTER_GRADE_DELETED_VALUE"
export const GET_LETTER_GRADE_DELETED_VALUE_SUCCESS = "GET_LETTER_GRADE_DELETED_VALUE_SUCCESS"
export const GET_LETTER_GRADE_DELETED_VALUE_FAIL = "GET_LETTER_GRADE_DELETED_VALUE_FAIL"

export const GET_LETTER_GRADE_DETAILS_DELETED_VALUE = "GET_LETTER_GRADE_DETAILS_DELETED_VALUE"
export const GET_LETTER_GRADE_DETAILS_DELETED_VALUE_SUCCESS = "GET_LETTER_GRADE_DETAILS_DELETED_VALUE_SUCCESS"
export const GET_LETTER_GRADE_DETAILS_DELETED_VALUE_FAIL = "GET_LETTER_GRADE_DETAILS_DELETED_VALUE_FAIL"