export const GET_CITIES = "GET_CITIES"
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS"
export const GET_CITIES_FAIL = "GET_CITIES_FAIL"

export const ADD_NEW_CITY = "ADD_NEW_CITY"
export const ADD_CITY_SUCCESS = "ADD_CITY_SUCCESS"
export const ADD_CITY_FAIL = "ADD_CITY_FAIL"

export const IMPORT_CITIES = "IMPORT_CITIES"
export const IMPORT_CITIES_SUCCESS = "IMPORT_CITIES_SUCCESS"
export const IMPORT_CITIES_FAIL = "IMPORT_CITIES_FAIL"

export const UPDATE_CITY = "UPDATE_CITY"
export const UPDATE_CITY_SUCCESS = "UPDATE_CITY_SUCCESS"
export const UPDATE_CITY_FAIL = "UPDATE_CITY_FAIL"

export const DELETE_CITY = "DELETE_CITY"
export const DELETE_CITY_SUCCESS = "DELETE_CITY_SUCCESS"
export const DELETE_CITY_FAIL = "DELETE_CITY_FAIL"

export const GET_CITY_DELETED_VALUE = "GET_CITY_DELETED_VALUE"
export const GET_CITY_DELETED_VALUE_SUCCESS = "GET_CITY_DELETED_VALUE_SUCCESS"
export const GET_CITY_DELETED_VALUE_FAIL = "GET_CITY_DELETED_VALUE_FAIL"

