/* TRAINEE_REQUESTS */
export const GET_TRAINEE_REQUESTS = "GET_TRAINEE_REQUESTS";
export const GET_TRAINEE_REQUESTS_SUCCESS = "GET_TRAINEE_REQUESTS_SUCCESS";
export const GET_TRAINEE_REQUESTS_FAIL = "GET_TRAINEE_REQUESTS_FAIL";

export const ADD_NEW_TRAINEE_REQUEST = "ADD_NEW_TRAINEE_REQUEST";
export const ADD_TRAINEE_REQUEST_SUCCESS = "ADD_TRAINEE_REQUEST_SUCCESS";
export const ADD_TRAINEE_REQUEST_FAIL = "ADD_TRAINEE_REQUEST_FAIL";

export const UPDATE_TRAINEE_REQUEST = "UPDATE_TRAINEE_REQUEST";
export const UPDATE_TRAINEE_REQUEST_SUCCESS = "UPDATE_TRAINEE_REQUEST_SUCCESS";
export const UPDATE_TRAINEE_REQUEST_FAIL = "UPDATE_TRAINEE_REQUEST_FAIL";

export const DELETE_TRAINEE_REQUEST = "DELETE_TRAINEE_REQUEST";
export const DELETE_TRAINEE_REQUEST_SUCCESS = "DELETE_TRAINEE_REQUEST_SUCCESS";
export const DELETE_TRAINEE_REQUEST_FAIL = "DELETE_TRAINEE_REQUEST_FAIL";

/* GRADE TYPES */
export const GET_GRADE_TYPES = "GET_GRADE_TYPES";
export const GET_GRADE_TYPES_SUCCESS = "GET_GRADE_TYPES_SUCCESS";
export const GET_GRADE_TYPES_FAIL = "GET_GRADE_TYPES_FAIL";

/*CoursesObjection */
export const GET_FILTERED_COURSES_OBJECTION = "GET_FILTERED_COURSES_OBJECTION";
export const GET_FILTERED_COURSES_OBJECTION_SUCCESS =
  "GET_FILTERED_COURSES_OBJECTION_SUCCESS";
export const GET_FILTERED_COURSES_OBJECTION_FAIL =
  "GET_FILTERED_COURSES_OBJECTION_FAIL";
