/* GENERAL_MANAGEMENTS */
export const GET_GENERAL_MANAGEMENTS = "GET_GENERAL_MANAGEMENTS"
export const GET_GENERAL_MANAGEMENTS_SUCCESS = "GET_GENERAL_MANAGEMENTS_SUCCESS"
export const GET_GENERAL_MANAGEMENTS_FAIL = "GET_GENERAL_MANAGEMENTS_FAIL"

/* GENERAL_MANAGEMENTS PROFILE*/
export const GET_GENERAL_MANAGEMENT_PROFILE = "GET_GENERAL_MANAGEMENT_PROFILE"
export const GET_GENERAL_MANAGEMENT_PROFILE_SUCCESS = "GET_GENERAL_MANAGEMENT_PROFILE_SUCCESS"
export const GET_GENERAL_MANAGEMENT_PROFILE_FAIL = "GET_GENERAL_MANAGEMENT_PROFILE_FAIL"

export const ADD_NEW_GENERAL_MANAGEMENT = "ADD_NEW_GENERAL_MANAGEMENT"
export const ADD_GENERAL_MANAGEMENT_SUCCESS = "ADD_GENERAL_MANAGEMENT_SUCCESS"
export const ADD_GENERAL_MANAGEMENT_FAIL = "ADD_GENERAL_MANAGEMENT_FAIL"

export const UPDATE_GENERAL_MANAGEMENT = "UPDATE_GENERAL_MANAGEMENT"
export const UPDATE_GENERAL_MANAGEMENT_SUCCESS = "UPDATE_GENERAL_MANAGEMENT_SUCCESS"
export const UPDATE_GENERAL_MANAGEMENT_FAIL = "UPDATE_GENERAL_MANAGEMENT_FAIL"

export const DELETE_GENERAL_MANAGEMENT = "DELETE_GENERAL_MANAGEMENT"
export const DELETE_GENERAL_MANAGEMENT_SUCCESS = "DELETE_GENERAL_MANAGEMENT_SUCCESS"
export const DELETE_GENERAL_MANAGEMENT_FAIL = "DELETE_GENERAL_MANAGEMENT_FAIL"


/* YEAR_SEMESTERS */
export const GET_YEAR_SEMESTERS = "GET_YEAR_SEMESTERS"
export const GET_YEAR_SEMESTERS_SUCCESS = "GET_YEAR_SEMESTERS_SUCCESS"
export const GET_YEAR_SEMESTERS_FAIL = "GET_YEAR_SEMESTERS_FAIL"


export const GET_YEAR_SEM = "GET_YEAR_SEM"
