/* MAJORS_TYPES */
export const GET_MAJORS_TYPES = "GET_MAJORS_TYPES"
export const GET_MAJORS_TYPES_SUCCESS = "GET_MAJORS_TYPES_SUCCESS"
export const GET_MAJORS_TYPES_FAIL = "GET_MAJORS_TYPES_FAIL"


export const ADD_NEW_MAJOR_TYPE = "ADD_NEW_MAJOR_TYPE"
export const ADD_MAJOR_TYPE_SUCCESS = "ADD_MAJOR_TYPE_SUCCESS"
export const ADD_MAJOR_TYPE_FAIL = "ADD_MAJOR_TYPE_FAIL"

export const UPDATE_MAJOR_TYPE = "UPDATE_MAJOR_TYPE"
export const UPDATE_MAJOR_TYPE_SUCCESS = "UPDATE_MAJOR_TYPE_SUCCESS"
export const UPDATE_MAJOR_TYPE_FAIL = "UPDATE_MAJOR_TYPE_FAIL"

export const DELETE_MAJOR_TYPE = "DELETE_MAJOR_TYPE"
export const DELETE_MAJOR_TYPE_SUCCESS = "DELETE_MAJOR_TYPE_SUCCESS"
export const DELETE_MAJOR_TYPE_FAIL = "DELETE_MAJOR_TYPE_FAIL"

export const GET_MAJOR_TYPE_DELETED_VALUE = "GET_MAJOR_TYPE_DELETED_VALUE"
export const GET_MAJOR_TYPE_DELETED_VALUE_SUCCESS = "GET_MAJOR_TYPE_DELETED_VALUE_SUCCESS"
export const GET_MAJOR_TYPE_DELETED_VALUE_FAIL = "GET_CERTIFICATE_DELETED_VALUE_FAIL"
