/* traineesDeservesWarnings */
export const GET_TRAINEES_DESERVES_WARNINGS = "GET_TRAINEES_DESERVES_WARNINGS";
export const GET_TRAINEES_DESERVES_WARNINGS_SUCCESS =
  "GET_TRAINEES_DESERVES_WARNINGS_SUCCESS";
export const GET_TRAINEES_DESERVES_WARNINGS_FAIL =
  "GET_TRAINEES_DESERVES_WARNINGS_FAIL";

/* traineesDeservesWarnings */
export const GET_TRAINEE_DESERVE_WARNING_DELETED_VALUE =
  "GET_TRAINEE_DESERVE_WARNING_DELETED_VALUE";
export const GET_TRAINEE_DESERVE_WARNING_DELETED_VALUE_SUCCESS =
  "GET_TRAINEE_DESERVE_WARNING_DELETED_VALUE_SUCCESS";
export const GET_TRAINEE_DESERVE_WARNING_DELETED_VALUE_FAIL =
  "GET_TRAINEE_DESERVE_WARNING_DELETED_VALUE_FAIL";

export const ADD_NEW_TRAINEE_DESERVE_WARNING =
  "ADD_NEW_TRAINEE_DESERVE_WARNING";
export const ADD_TRAINEE_DESERVE_WARNING_SUCCESS =
  "ADD_TRAINEE_DESERVE_WARNING_SUCCESS";
export const ADD_TRAINEE_DESERVE_WARNING_FAIL =
  "ADD_TRAINEE_DESERVE_WARNING_FAIL";

export const UPDATE_TRAINEE_DESERVE_WARNING = "UPDATE_TRAINEE_DESERVE_WARNING";
export const UPDATE_TRAINEE_DESERVE_WARNING_SUCCESS =
  "UPDATE_TRAINEE_DESERVE_WARNING_SUCCESS";
export const UPDATE_TRAINEE_DESERVE_WARNING_FAIL =
  "UPDATE_TRAINEE_DESERVE_WARNING_FAIL";

export const DELETE_TRAINEE_DESERVE_WARNING = "DELETE_TRAINEE_DESERVE_WARNING";
export const DELETE_TRAINEE_DESERVE_WARNING_SUCCESS =
  "DELETE_TRAINEE_DESERVE_WARNING_SUCCESS";
export const DELETE_TRAINEE_DESERVE_WARNING_FAIL =
  "DELETE_TRAINEE_DESERVE_WARNING_FAIL";
