/*  ACADEMY BUILDING STRUCTURE */
export const GET_ACADEMY_BUILDING_STRUCTURES =
  "GET_ACADEMY_BUILDING_STRUCTURES";
export const GET_ACADEMY_BUILDING_STRUCTURES_SUCCESS =
  "GET_ACADEMY_BUILDING_STRUCTURES_SUCCESS";
export const GET_ACADEMY_BUILDING_STRUCTURES_FAIL =
  "GET_ACADEMY_BUILDING_STRUCTURES_FAIL";

/*  HALLS */
export const GET_HALLS = "GET_HALLS";
export const GET_HALLS_SUCCESS = "GET_HALLS_SUCCESS";
export const GET_HALLS_FAIL = "GET_HALLS_FAIL";

/*  HALLSTYPES */
export const GET_HALL_TYPES = "GET_HALL_TYPES";
export const GET_HALL_TYPES_SUCCESS = "GET_HALL_TYPES_SUCCESS";
export const GET_HALL_TYPES_FAIL = "GET_HALL_TYPES_FAIL";

/*  ACADEMY BUILDING STRUCTURE PROFILE */
export const GET_ACADEMY_BUILDING_STRUCTURE_DELETED_VALUE =
  "GET_ACADEMY_BUILDING_STRUCTURE_DELETED_VALUE";
export const GET_ACADEMY_BUILDING_STRUCTURE_DELETED_VALUE_SUCCESS =
  "GET_ACADEMY_BUILDING_STRUCTURE_DELETED_VALUE_SUCCESS";
export const GET_ACADEMY_BUILDING_STRUCTURE_DELETED_VALUE_FAIL =
  "GET_ACADEMY_BUILDING_STRUCTURE_DELETED_VALUE_FAIL";

export const ADD_NEW_ACADEMY_BUILDING_STRUCTURE =
  "ADD_NEW_ACADEMY_BUILDING_STRUCTURE";
export const ADD_ACADEMY_BUILDING_STRUCTURE_SUCCESS =
  "ADD_ACADEMY_BUILDING_STRUCTURE_SUCCESS";
export const ADD_ACADEMY_BUILDING_STRUCTURE_FAIL =
  "ADD_ACADEMY_BUILDING_STRUCTURE_FAIL";

export const UPDATE_ACADEMY_BUILDING_STRUCTURE =
  "UPDATE_ACADEMY_BUILDING_STRUCTURE";
export const UPDATE_ACADEMY_BUILDING_STRUCTURE_SUCCESS =
  "UPDATE_ACADEMY_BUILDING_STRUCTURE_SUCCESS";
export const UPDATE_ACADEMY_BUILDING_STRUCTURE_FAIL =
  "UPDATE_ACADEMY_BUILDING_STRUCTURE_FAIL";

export const DELETE_ACADEMY_BUILDING_STRUCTURE =
  "DELETE_ACADEMY_BUILDING_STRUCTURE";
export const DELETE_ACADEMY_BUILDING_STRUCTURE_SUCCESS =
  "DELETE_ACADEMY_BUILDING_STRUCTURE_SUCCESS";
export const DELETE_ACADEMY_BUILDING_STRUCTURE_FAIL =
  "DELETE_ACADEMY_BUILDING_STRUCTURE_FAIL";
