export const GET_LECTURE_PERMISSIONS = "GET_LECTURE_PERMISSIONS";
export const GET_LECTURE_PERMISSIONS_SUCCESS =
  "GET_LECTURE_PERMISSIONS_SUCCESS";
export const GET_LECTURE_PERMISSIONS_FAIL = "GET_LECTURE_PERMISSIONS_FAIL";

export const ADD_NEW_LECTURE_PERMISSION = "ADD_NEW_LECTURE_PERMISSION";
export const ADD_LECTURE_PERMISSION_SUCCESS = "ADD_LECTURE_PERMISSION_SUCCESS";
export const ADD_LECTURE_PERMISSION_FAIL = "ADD_LECTURE_PERMISSION_FAIL";

export const UPDATE_LECTURE_PERMISSION = "UPDATE_LECTURE_PERMISSION";
export const UPDATE_LECTURE_PERMISSION_SUCCESS =
  "UPDATE_LECTURE_PERMISSION_SUCCESS";
export const UPDATE_LECTURE_PERMISSION_FAIL = "UPDATE_LECTURE_PERMISSION_FAIL";

export const DELETE_LECTURE_PERMISSION = "DELETE_LECTURE_PERMISSION";
export const DELETE_LECTURE_PERMISSION_SUCCESS =
  "DELETE_LECTURE_PERMISSION_SUCCESS";
export const DELETE_LECTURE_PERMISSION_FAIL = "DELETE_LECTURE_PERMISSION_FAIL";

export const GET_LECTURE_PERMISSION_DELETED_VALUE =
  "GET_LECTURE_PERMISSION_DELETED_VALUE";
export const GET_LECTURE_PERMISSION_DELETED_VALUE_SUCCESS =
  "GET_LECTURE_PERMISSION_DELETED_VALUE_SUCCESS";
export const GET_LECTURE_PERMISSION_DELETED_VALUE_FAIL =
  "GET_LECTURE_PERMISSION_DELETED_VALUE_FAIL";
// //role permissions
// export const GET_LECTURE_PERMISSION_PERMISSIONS =
//   "GET_LECTURE_PERMISSION_PERMISSIONS";
// export const GET_LECTURE_PERMISSION_PERMISSIONS_SUCCESS =
//   "GET_LECTURE_PERMISSION_PERMISSIONS_SUCCESS";
// export const GET_LECTURE_PERMISSION_PERMISSIONS_FAIL =
//   "GET_LECTURE_PERMISSION_PERMISSIONS_FAIL";

// export const ADD_NEW_LECTURE_PERMISSION_PERMISSION =
//   "ADD_NEW_LECTURE_PERMISSION_PERMISSION";
// export const ADD_LECTURE_PERMISSION_PERMISSION_SUCCESS =
//   "ADD_LECTURE_PERMISSION_PERMISSION_SUCCESS";
// export const ADD_LECTURE_PERMISSION_PERMISSION_FAIL =
//   "ADD_LECTURE_PERMISSION_PERMISSION_FAIL";

// export const UPDATE_LECTURE_PERMISSION_PERMISSION =
//   "UPDATE_LECTURE_PERMISSION_PERMISSION";
// export const UPDATE_LECTURE_PERMISSION_PERMISSION_SUCCESS =
//   "UPDATE_LECTURE_PERMISSION_PERMISSION_SUCCESS";
// export const UPDATE_LECTURE_PERMISSION_PERMISSION_FAIL =
//   "UPDATE_LECTURE_PERMISSION_PERMISSION_FAIL";

// export const DELETE_LECTURE_PERMISSION_PERMISSION =
//   "DELETE_LECTURE_PERMISSION_PERMISSION";
// export const DELETE_LECTURE_PERMISSION_PERMISSION_SUCCESS =
//   "DELETE_LECTURE_PERMISSION_PERMISSION_SUCCESS";
// export const DELETE_LECTURE_PERMISSION_PERMISSION_FAIL =
//   "DELETE_LECTURE_PERMISSION_PERMISSION_FAIL";

// export const GET_LECTURE_PERMISSION_PERMISSION_DELETED_VALUE =
//   "GET_LECTURE_PERMISSION_PERMISSION_DELETED_VALUE";
// export const GET_LECTURE_PERMISSION_PERMISSION_DELETED_VALUE_SUCCESS =
//   "GET_LECTURE_PERMISSION_PERMISSION_DELETED_VALUE_SUCCESS";
// export const GET_LECTURE_PERMISSION_PERMISSION_DELETED_VALUE_FAIL =
//   "GET_LECTURE_PERMISSION_PERMISSION_DELETED_VALUE_FAIL";

// role user

export const ADD_NEW_LECTURE_PERMISSION_USER =
  "ADD_NEW_LECTURE_PERMISSION_USER";
export const ADD_LECTURE_PERMISSION_USER_SUCCESS =
  "ADD_LECTURE_PERMISSION_USER_SUCCESS";
export const ADD_LECTURE_PERMISSION_USER_FAIL =
  "ADD_LECTURE_PERMISSION_USER_FAIL";
