/* FINE_DEFINITIONS */
export const GET_FINES_DEFINITION = "GET_FINES_DEFINITION";
export const GET_FINES_DEFINITION_SUCCESS = "GET_FINES_DEFINITION_SUCCESS";
export const GET_FINES_DEFINITION_FAIL = "GET_FINES_DEFINITION_FAIL";

export const GET_CRITERIA = "GET_CRITERIA";
export const GET_CRITERIA_SUCCESS = "GET_CRITERIA_SUCCESS";
export const GET_CRITERIA_FAIL = "GET_CRITERIA_FAIL";

export const GET_FINE_DEFINITION_DELETED_VALUE = "GET_FINE_DEFINITION_DELETED_VALUE";
export const GET_FINE_DEFINITION_DELETED_VALUE_SUCCESS = "GET_FINE_DEFINITION_DELETED_VALUE_SUCCESS";
export const GET_FINE_DEFINITION_DELETED_VALUE_FAIL = "GET_FINE_DEFINITION_DELETED_VALUE_FAIL";

export const ADD_NEW_FINE_DEFINITION = "ADD_NEW_FINE_DEFINITION";
export const ADD_NEW_FINE_DEFINITION_SUCCESS = "ADD_NEW_FINE_DEFINITION_SUCCESS";
export const ADD_NEW_FINE_DEFINITION_FAIL = "ADD_NEW_FINE_DEFINITION_FAIL";

export const UPDATE_FINE_DEFINITION = "UPDATE_FINE_DEFINITION";
export const UPDATE_FINE_DEFINITION_SUCCESS = "UPDATE_FINE_DEFINITION_SUCCESS";
export const UPDATE_FINE_DEFINITION_FAIL = "UPDATE_FINE_DEFINITION_FAIL";

export const DELETE_FINE_DEFINITION = "DELETE_FINE_DEFINITION";
export const DELETE_FINE_DEFINITION_SUCCESS = "DELETE_FINE_DEFINITION_SUCCESS";
export const DELETE_FINE_DEFINITION_FAIL = "DELETE_FINE_DEFINITION_FAIL";

export const COPY_FINE = "COPY_FINE"
export const COPY_FINE_SUCCESS = "COPY_FINE_SUCCESS"
export const COPY_FINE_FAIL = "COPY_FINE_FAIL"
