/* CONTRACT_TYPES */
export const GET_CONTRACTS_TYPES = "GET_CONTRACTS_TYPES";
export const GET_CONTRACTS_TYPES_SUCCESS = "GET_CONTRACTS_TYPES_SUCCESS";
export const GET_CONTRACTS_TYPES_FAIL = "GET_CONTRACTS_TYPES_FAIL";

/* CONTRACT_TYPES PROFILE */
export const GET_CONTRACT_TYPE_DELETED_VALUE =
  "GET_CONTRACT_TYPE_DELETED_VALUE";
export const GET_CONTRACT_TYPE_DELETED_VALUE_SUCCESS =
  "GET_CONTRACT_TYPE_DELETED_VALUE_SUCCESS";
export const GET_CONTRACT_TYPE_DELETED_VALUE_FAIL =
  "GET_CONTRACT_TYPE_DELETED_VALUE_FAIL";

export const ADD_NEW_CONTRACT_TYPE = "ADD_NEW_CONTRACT_TYPE";
export const ADD_CONTRACT_TYPE_SUCCESS = "ADD_CONTRACT_TYPE_SUCCESS";
export const ADD_CONTRACT_TYPE_FAIL = "ADD_CONTRACT_TYPE_FAIL";

export const UPDATE_CONTRACT_TYPE = "UPDATE_CONTRACT_TYPE";
export const UPDATE_CONTRACT_TYPE_SUCCESS = "UPDATE_CONTRACT_TYPE_SUCCESS";
export const UPDATE_CONTRACT_TYPE_FAIL = "UPDATE_CONTRACT_TYPE_FAIL";

export const DELETE_CONTRACT_TYPE = "DELETE_CONTRACT_TYPE";
export const DELETE_CONTRACT_TYPE_SUCCESS = "DELETE_CONTRACT_TYPE_SUCCESS";
export const DELETE_CONTRACT_TYPE_FAIL = "DELETE_CONTRACT_TYPE_FAIL";
