/* LECTURE_PERIODS */
export const GET_LECTURE_PERIODS = "GET_LECTURE_PERIODS"
export const GET_LECTURE_PERIODS_SUCCESS = "GET_LECTURE_PERIODS_SUCCESS"
export const GET_LECTURE_PERIODS_FAIL = "GET_LECTURE_PERIODS_FAIL"

/* LECTURE_PERIODS PROFILE*/
export const GET_LECTURE_PERIOD_PROFILE = "GET_LECTURE_PERIOD_PROFILE"
export const GET_LECTURE_PERIOD_PROFILE_SUCCESS = "GET_LECTURE_PERIOD_PROFILE_SUCCESS"
export const GET_LECTURE_PERIOD_PROFILE_FAIL = "GET_LECTURE_PERIOD_PROFILE_FAIL"

export const ADD_NEW_LECTURE_PERIOD = "ADD_NEW_LECTURE_PERIOD"
export const ADD_LECTURE_PERIOD_SUCCESS = "ADD_LECTURE_PERIOD_SUCCESS"
export const ADD_LECTURE_PERIOD_FAIL = "ADD_LECTURE_PERIOD_FAIL"

export const UPDATE_LECTURE_PERIOD = "UPDATE_LECTURE_PERIOD"
export const UPDATE_LECTURE_PERIOD_SUCCESS = "UPDATE_LECTURE_PERIOD_SUCCESS"
export const UPDATE_LECTURE_PERIOD_FAIL = "UPDATE_LECTURE_PERIOD_FAIL"

export const DELETE_LECTURE_PERIOD = "DELETE_LECTURE_PERIOD"
export const DELETE_LECTURE_PERIOD_SUCCESS = "DELETE_LECTURE_PERIOD_SUCCESS"
export const DELETE_LECTURE_PERIOD_FAIL = "DELETE_LECTURE_PERIOD_FAIL"