/* REWARD_TYPES */
export const GET_REWARDS_TYPES = "GET_REWARDS_TYPES";
export const GET_REWARDS_TYPES_SUCCESS = "GET_REWARDS_TYPES_SUCCESS";
export const GET_REWARDS_TYPES_FAIL = "GET_REWARDS_TYPES_FAIL";

/* REWARD_TYPES PROFILE */
export const GET_REWARD_TYPE_DELETED_VALUE = "GET_REWARD_TYPE_DELETED_VALUE";
export const GET_REWARD_TYPE_DELETED_VALUE_SUCCESS =
  "GET_REWARD_TYPE_DELETED_VALUE_SUCCESS";
export const GET_REWARD_TYPE_DELETED_VALUE_FAIL =
  "GET_REWARD_TYPE_DELETED_VALUE_FAIL";

export const ADD_NEW_REWARD_TYPE = "ADD_NEW_REWARD_TYPE";
export const ADD_REWARD_TYPE_SUCCESS = "ADD_REWARD_TYPE_SUCCESS";
export const ADD_REWARD_TYPE_FAIL = "ADD_REWARD_TYPE_FAIL";

export const UPDATE_REWARD_TYPE = "UPDATE_REWARD_TYPE";
export const UPDATE_REWARD_TYPE_SUCCESS = "UPDATE_REWARD_TYPE_SUCCESS";
export const UPDATE_REWARD_TYPE_FAIL = "UPDATE_REWARD_TYPE_FAIL";

export const DELETE_REWARD_TYPE = "DELETE_REWARD_TYPE";
export const DELETE_REWARD_TYPE_SUCCESS = "DELETE_REWARD_TYPE_SUCCESS";
export const DELETE_REWARD_TYPE_FAIL = "DELETE_REWARD_TYPE_FAIL";
