export const GET_ACADEMICCERTIFICATES = "GET_ACADEMICCERTIFICATES"
export const GET_ACADEMICCERTIFICATES_SUCCESS = "GET_ACADEMICCERTIFICATES_SUCCESS"
export const GET_ACADEMICCERTIFICATES_FAIL = "GET_ACADEMICCERTIFICATES_FAIL"

/* ACADEMICCERTIFICATES PROFILE */
export const GET_ACADEMICCERTIFICATE_DELETED_VALUE = "GET_ACADEMICCERTIFICATE_DELETED_VALUE"
export const GET_ACADEMICCERTIFICATE_DELETED_VALUE_SUCCESS = "GET_ACADEMICCERTIFICATE_DELETED_VALUE_SUCCESS"
export const GET_ACADEMICCERTIFICATE_DELETED_VALUE_FAIL = "GET_ACADEMICCERTIFICATE_DELETED_VALUE_FAIL"

export const ADD_NEW_ACADEMICCERTIFICATES = "ADD_NEW_ACADEMICCERTIFICATES"
export const ADD_ACADEMICCERTIFICATES_SUCCESS = "ADD_ACADEMICCERTIFICATES_SUCCESS"
export const ADD_ACADEMICCERTIFICATES_FAIL = "ADD_ACADEMICCERTIFICATES_FAIL"

export const UPDATE_ACADEMICCERTIFICATE = "UPDATE_ACADEMICCERTIFICATE"
export const UPDATE_ACADEMICCERTIFICATE_SUCCESS = "UPDATE_ACADEMICCERTIFICATE_SUCCESS"
export const UPDATE_ACADEMICCERTIFICATE_FAIL = "UPDATE_ACADEMICCERTIFICATE_FAIL"

export const DELETE_ACADEMICCERTIFICATES = "DELETE_ACADEMICCERTIFICATES"
export const DELETE_ACADEMICCERTIFICATES_SUCCESS = "DELETE_ACADEMICCERTIFICATES_SUCCESS"
export const DELETE_ACADEMICCERTIFICATES_FAIL = "DELETE_ACADEMICCERTIFICATES_FAIL"


export const GET_FILTERED_ACADEMIC_CERTIFICATES = "GET_FILTERED_ACADEMIC_CERTIFICATES"
export const GET_FILTERED_ACADEMIC_CERTIFICATES_SUCCESS = "GET_FILTERED_ACADEMIC_CERTIFICATES_SUCCESS"
export const GET_FILTERED_ACADEMIC_CERTIFICATES_FAIL = "GET_FILTERED_ACADEMIC_CERTIFICATES_FAIL"

export const GET_COUNTRY_DELETED_VALUE = "GET_COUNTRY_DELETED_VALUE"
export const GET_COUNTRY_DELETED_VALUE_SUCCESS = "GET_COUNTRY_DELETED_VALUE_SUCCESS"
export const GET_COUNTRY_DELETED_VALUE_FAIL = "GET_COUNTRY_DELETED_VALUE_FAIL"
