/* DISMISS_DECREES_ABSENCE */
export const GET_DISMISS_DECREES_ABSENCE = " GET_DISMISS_DECREES_ABSENCE";
export const GET_DISMISS_DECREES_ABSENCE_SUCCESS =
  " GET_DISMISS_DECREES_ABSENCE_SUCCESS";
export const GET_DISMISS_DECREES_ABSENCE_FAIL =
  " GET_DISMISS_DECREES_ABSENCE_FAIL";

/* DISMISS_DECREE_ABSENCES PROFILE */
export const GET_DISMISS_DECREE_ABSENCE_DELETED_VALUE =
  " GET_DISMISS_DECREE_ABSENCE_DELETED_VALUE";
export const GET_DISMISS_DECREE_ABSENCE_DELETED_VALUE_SUCCESS =
  " GET_DISMISS_DECREE_ABSENCE_DELETED_VALUE_SUCCESS";
export const GET_DISMISS_DECREE_ABSENCE_DELETED_VALUE_FAIL =
  " GET_DISMISS_DECREE_ABSENCE_DELETED_VALUE_FAIL";

export const ADD_NEW_DISMISS_DECREE_ABSENCE = "ADD_NEW_DISMISS_DECREE_ABSENCE";
export const ADD_DISMISS_DECREE_ABSENCE_SUCCESS =
  "ADD_DISMISS_DECREE_ABSENCE_SUCCESS";
export const ADD_DISMISS_DECREE_ABSENCE_FAIL =
  "ADD_DISMISS_DECREE_ABSENCE_FAIL";

export const UPDATE_DISMISS_DECREE_ABSENCE = "UPDATE_DISMISS_DECREE_ABSENCE";
export const UPDATE_DISMISS_DECREE_ABSENCE_SUCCESS =
  "UPDATE_DISMISS_DECREE_ABSENCE_SUCCESS";
export const UPDATE_DISMISS_DECREE_ABSENCE_FAIL =
  "UPDATE_DISMISS_DECREE_ABSENCE_FAIL";

export const DELETE_DISMISS_DECREE_ABSENCE = "DELETE_DISMISS_DECREE_ABSENCE";
export const DELETE_DISMISS_DECREE_ABSENCE_SUCCESS =
  "DELETE_DISMISS_DECREE_ABSENCE_SUCCESS";
export const DELETE_DISMISS_DECREE_ABSENCE_FAIL =
  "DELETE_DISMISS_DECREE_ABSENCE_FAIL";
