/* TRAINEES */
export const GET_REGISTER_TRAINEES_ATTENDANCE =
  "GET_REGISTER_TRAINEES_ATTENDANCE";
export const GET_REGISTER_TRAINEES_ATTENDANCE_SUCCESS =
  "GET_REGISTER_TRAINEES_ATTENDANCE_SUCCESS";
export const GET_REGISTER_TRAINEES_ATTENDANCE_FAIL =
  "GET_REGISTER_TRAINEES_ATTENDANCE_FAIL";

/* TRAINEE PROFILE */
export const GET_REGISTER_TRAINEE_ATTENDANCE_DELETED_VALUE =
  "GET_REGISTER_TRAINEE_ATTENDANCE_DELETED_VALUE";
export const GET_REGISTER_TRAINEE_ATTENDANCE_DELETED_VALUE_SUCCESS =
  "GET_REGISTER_TRAINEE_ATTENDANCE_DELETED_VALUE_SUCCESS";
export const GET_REGISTER_TRAINEE_ATTENDANCE_DELETED_VALUE_FAIL =
  "GET_REGISTER_TRAINEE_ATTENDANCE_DELETED_VALUE_FAIL";

export const ADD_NEW_REGISTER_TRAINEE_ATTENDANCE =
  "ADD_NEW_REGISTER_TRAINEE_ATTENDANCE";
export const ADD_REGISTER_TRAINEE_ATTENDANCE_SUCCESS =
  "ADD_REGISTER_TRAINEE_ATTENDANCE_SUCCESS";
export const ADD_REGISTER_TRAINEE_ATTENDANCE_FAIL =
  "ADD_REGISTER_TRAINEE_ATTENDANCE_FAIL";

export const UPDATE_REGISTER_TRAINEE_ATTENDANCE =
  "UPDATE_REGISTER_TRAINEE_ATTENDANCE";
export const UPDATE_REGISTER_TRAINEE_ATTENDANCE_SUCCESS =
  "UPDATE_REGISTER_TRAINEE_ATTENDANCE_SUCCESS";
export const UPDATE_REGISTER_TRAINEE_ATTENDANCE_FAIL =
  "UPDATE_REGISTER_TRAINEE_ATTENDANCE_FAIL";

export const DELETE_REGISTER_TRAINEE_ATTENDANCE =
  "DELETE_REGISTER_TRAINEE_ATTENDANCE";
export const DELETE_REGISTER_TRAINEE_ATTENDANCE_SUCCESS =
  "DELETE_REGISTER_TRAINEE_ATTENDANCE_SUCCESS";
export const DELETE_REGISTER_TRAINEE_ATTENDANCE_FAIL =
  "DELETE_REGISTER_TRAINEE_ATTENDANCE_FAIL";
