/* QUALIFICATION_TRACKS */
export const GET_QUALIFICATIONS_TRACKS = "GET_QUALIFICATIONS_TRACKS"
export const GET_QUALIFICATIONS_TRACKS_SUCCESS = "GET_QUALIFICATIONS_TRACKS_SUCCESS"
export const GET_QUALIFICATIONS_TRACKS_FAIL = "GET_QUALIFICATIONS_TRACKS_FAIL"

/* SECTORS PROFILE */
export const GET_QUALIFICATION_TRACK_DELETED_VALUE = "GET_QUALIFICATION_TRACK_DELETED_VALUE"
export const GET_QUALIFICATION_TRACK_DELETED_VALUE_SUCCESS = "GET_QUALIFICATION_TRACK_DELETED_VALUE_SUCCESS"
export const GET_QUALIFICATION_TRACK_DELETED_VALUE_FAIL = "GET_QUALIFICATION_TRACK_DELETED_VALUE_FAIL"

export const ADD_NEW_QUALIFICATION_TRACK = "ADD_NEW_QUALIFICATION_TRACK"
export const ADD_QUALIFICATION_TRACK_SUCCESS = "ADD_QUALIFICATION_TRACK_SUCCESS"
export const ADD_QUALIFICATION_TRACK_FAIL = "ADD_QUALIFICATION_TRACK_FAIL"

export const UPDATE_QUALIFICATION_TRACK = "UPDATE_QUALIFICATION_TRACK"
export const UPDATE_QUALIFICATION_TRACK_SUCCESS = "UPDATE_QUALIFICATION_TRACK_SUCCESS"
export const UPDATE_QUALIFICATION_TRACK_FAIL = "UPDATE_QUALIFICATION_TRACK_FAIL"

export const DELETE_QUALIFICATION_TRACK = "DELETE_QUALIFICATION_TRACK"
export const DELETE_QUALIFICATION_TRACK_SUCCESS = "DELETE_QUALIFICATION_TRACK_SUCCESS"
export const DELETE_QUALIFICATION_TRACK_FAIL = "DELETE_QUALIFICATION_TRACK_FAIL"