/* SCHEDULING_LECTURES */
export const GET_SCHEDULING_LECTURES = "GET_SCHEDULING_LECTURES";
export const GET_SCHEDULING_LECTURES_SUCCESS = "GET_SCHEDULING_LECTURES_SUCCESS";
export const GET_SCHEDULING_LECTURES_FAIL = "GET_SCHEDULING_LECTURES_FAIL";

export const GET_ALL_SCHEDULING_LECTURES = "GET_ALL_SCHEDULING_LECTURES";
export const GET_ALL_SCHEDULING_LECTURES_SUCCESS =
  "GET_ALL_SCHEDULING_LECTURES_SUCCESS";
export const GET_ALL_SCHEDULING_LECTURES_FAIL =
  "GET_ALL_SCHEDULING_LECTURES_FAIL";

/* SCHEDULING_LECTURE PROFILE */
export const GET_SCHEDULING_LECTURE_PROFILE = "GET_SCHEDULING_LECTURE_PROFILE";
export const GET_SCHEDULING_LECTURE_PROFILE_SUCCESS =
  "GET_SCHEDULING_LECTURE_PROFILE_SUCCESS";
export const GET_SCHEDULING_LECTURE_PROFILE_FAIL =
  "GET_SCHEDULING_LECTURE_PROFILE_FAIL";

export const ADD_NEW_SCHEDULING_LECTURE = "ADD_NEW_SCHEDULING_LECTURE";
export const ADD_SCHEDULING_LECTURE_SUCCESS = "ADD_SCHEDULING_LECTURE_SUCCESS";
export const ADD_SCHEDULING_LECTURE_FAIL = "ADD_SCHEDULING_LECTURE_FAIL";

export const UPDATE_SCHEDULING_LECTURE = "UPDATE_SCHEDULING_LECTURE";
export const UPDATE_SCHEDULING_LECTURE_SUCCESS =
  "UPDATE_SCHEDULING_LECTURE_SUCCESS";
export const UPDATE_SCHEDULING_LECTURE_FAIL = "UPDATE_SCHEDULING_LECTURE_FAIL";

export const DELETE_SCHEDULING_LECTURE = "DELETE_SCHEDULING_LECTURE";
export const DELETE_SCHEDULING_LECTURE_SUCCESS =
  "DELETE_SCHEDULING_LECTURE_SUCCESS";
export const DELETE_SCHEDULING_LECTURE_FAIL = "DELETE_SCHEDULING_LECTURE_FAIL";

export const GET_INSTRUCTORS = "GET_INSTRUCTORS";
export const GET_INSTRUCTORS_SUCCESS = "GET_INSTRUCTORS_SUCCESS";
export const GET_INSTRUCTORS_FAIL = "GET_INSTRUCTORS_FAIL";

/* SECTION_LABS */
export const GET_SECTION_LABS = "GET_SECTION_LABS";
export const GET_SECTION_LABS_SUCCESS = "GET_SECTION_LABS_SUCCESS";
export const GET_SECTION_LABS_FAIL = "GET_SECTION_LABS_FAIL";

/* SECTION_LAB PROFILE */
export const GET_SECTION_LAB_PROFILE = "GET_SECTION_LAB_PROFILE";
export const GET_SECTION_LAB_PROFILE_SUCCESS =
  "GET_SECTION_LAB_PROFILE_SUCCESS";
export const GET_SECTION_LAB_PROFILE_FAIL = "GET_SECTION_LAB_PROFILE_FAIL";

export const ADD_NEW_SECTION_LAB = "ADD_NEW_SECTION_LAB";
export const ADD_SECTION_LAB_SUCCESS = "ADD_SECTION_LAB_SUCCESS";
export const ADD_SECTION_LAB_FAIL = "ADD_SECTION_LAB_FAIL";

export const UPDATE_SECTION_LAB = "UPDATE_SECTION_LAB";
export const UPDATE_SECTION_LAB_SUCCESS = "UPDATE_SECTION_LAB_SUCCESS";
export const UPDATE_SECTION_LAB_FAIL = "UPDATE_SECTION_LAB_FAIL";

export const DELETE_SECTION_LAB = "DELETE_SECTION_LAB";
export const DELETE_SECTION_LAB_SUCCESS = "DELETE_SECTION_LAB_SUCCESS";
export const DELETE_SECTION_LAB_FAIL = "DELETE_SECTION_LAB_FAIL";

/* SCHEDULE_TIMING */

export const GET_SCHEDULE_TIMINGS = "GET_SCHEDULE_TIMINGS";
export const GET_SCHEDULE_TIMINGS_SUCCESS = "GET_SCHEDULE_TIMINGS_SUCCESS";
export const GET_SCHEDULE_TIMINGS_FAIL = "GET_SCHEDULE_TIMINGS_FAIL";

export const GET_SCHEDULE_TIMING_PROFILE = "GET_SCHEDULE_TIMING_PROFILE";
export const GET_SCHEDULE_TIMING_PROFILE_SUCCESS =
  "GET_SCHEDULE_TIMING_PROFILE_SUCCESS";
export const GET_SCHEDULE_TIMING_PROFILE_FAIL =
  "GET_SCHEDULE_TIMING_PROFILE_FAIL";

export const ADD_NEW_SCHEDULE_TIMING = "ADD_NEW_SCHEDULE_TIMING";
export const ADD_SCHEDULE_TIMING_SUCCESS = "ADD_SCHEDULE_TIMING_SUCCESS";
export const ADD_SCHEDULE_TIMING_FAIL = "ADD_SCHEDULE_TIMING_FAIL";

export const DELETE_SCHEDULE_TIMING = "DELETE_SCHEDULE_TIMING";
export const DELETE_SCHEDULE_TIMING_SUCCESS = "DELETE_SCHEDULE_TIMING_SUCCESS";
export const DELETE_SCHEDULE_TIMING_FAIL = "DELETE_SCHEDULE_TIMING_FAIL";

/* SCHEDULE_TIMING_DESCS */
export const GET_SCHEDULE_TIMING_DESCS = "GET_SCHEDULE_TIMING_DESCS";
export const GET_SCHEDULE_TIMING_DESCS_SUCCESS =
  "GET_SCHEDULE_TIMING_DESCS_SUCCESS";
export const GET_SCHEDULE_TIMING_DESCS_FAIL = "GET_SCHEDULE_TIMING_DESCS_FAIL";

export const GET_FILTERED_SECTIONS = "GET_FILTERED_SECTIONS";
export const GET_FILTERED_SECTIONS_SUCCESS = "GET_FILTERED_SECTIONS_SUCCESS";
export const GET_FILTERED_SECTIONS_FAIL = "GET_SCHEDULING_LECTURES_FAIL";

/* DEFAULT_SETTINGS */
export const GET_DEFAULT_SETTINGS = "GET_DEFAULT_SETTINGS";


export const GET_SCHEDULE_MSG_VALUE = "GET_SCHEDULE_MSG_VALUE"
export const GET_SCHEDULE_MSG_VALUE_SUCCESS = "GET_SCHEDULE_MSG_VALUE_SUCCESS"
export const GET_SCHEDULE_MSG_VALUE_FAIL = "GET_SCHEDULE_MSG_VALUE_FAIL"


/* HALL_TIMING */

export const GET_HALL_TIMINGS = "GET_HALL_TIMINGS";
export const GET_HALL_TIMINGS_SUCCESS = "GET_HALL_TIMINGS_SUCCESS";
export const GET_HALL_TIMINGS_FAIL = "GET_HALL_TIMINGS_FAIL";
