/* STUDENTS */
export const GET_STUDENTS = "GET_STUDENTS"
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS"
export const GET_STUDENTS_FAIL = "GET_STUDENTS_FAIL"

export const ADD_NEW_STUDENT = "ADD_NEW_STUDENT"
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS"
export const ADD_STUDENT_FAIL = "ADD_STUDENT_FAIL"

export const UPDATE_STUDENT = "UPDATE_STUDENT"
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS"
export const UPDATE_STUDENT_FAIL = "UPDATE_STUDENT_FAIL"

export const DELETE_STUDENT = "DELETE_STUDENT"
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS"
export const DELETE_STUDENT_FAIL = "DELETE_STUDENT_FAIL"

export const GET_STUDENT_BY_ID = "GET_STUDENT_BY_ID"
export const GET_STUDENT_BY_ID_SUCCESS = "GET_STUDENT_BY_ID_SUCCESS"
export const GET_STUDENT_BY_ID_FAIL = "GET_STUDENT_BY_ID_FAIL"

export const GET_DEFAULT_REGREQDOCS = "GET_DEFAULT_REGREQDOCS"
export const GET_DEFAULT_REGREQDOCS_SUCCESS = "GET_DEFAULT_REGREQDOCS_SUCCESS"
export const GET_DEFAULT_REGREQDOCS_FAIL = "GET_DEFAULT_REGREQDOCS_FAIL"

export const GENERATE_STUDENT = "GENERATE_STUDENT"
export const GENERATE_STUDENT_SUCCESS = "GENERATE_STUDENT_SUCCESS"
export const GENERATE_STUDENT_FAIL = "GENERATE_STUDENT_FAIL"

export const GET_STUDENT_DELETED_VALUE = "GET_STUDENT_DELETED_VALUE"
export const GET_STUDENT_DELETED_VALUE_SUCCESS = "GET_STUDENT_DELETED_VALUE_SUCCESS"
export const GET_STUDENT_DELETED_VALUE_FAIL = "GET_STUDENT_DELETED_VALUE_FAIL"

/* TEMP_RELATIVES */
export const GET_TEMP_RELATIVES = "GET_TEMP_RELATIVES"
export const GET_TEMP_RELATIVES_SUCCESS = "GET_TEMP_RELATIVES_SUCCESS"
export const GET_TEMP_RELATIVES_FAIL = "GET_TEMP_RELATIVES_FAIL"

export const GET_TEMP_RELATIVE_DELETED_VALUE = "GET_TEMP_RELATIVE_DELETED_VALUE"
export const GET_TEMP_RELATIVE_DELETED_VALUE_SUCCESS = "GET_TEMP_RELATIVE_DELETED_VALUE_SUCCESS"
export const GET_TEMP_RELATIVE_DELETED_VALUE_FAIL = "GET_TEMP_RELATIVE_DELETED_VALUE_FAIL"

