/* REQUIREMENT_TYPES */
export const GET_REQUIREMENT_TYPES = "GET_REQUIREMENT_TYPES"
export const GET_REQUIREMENT_TYPES_SUCCESS = "GET_REQUIREMENT_TYPES_SUCCESS"
export const GET_REQUIREMENT_TYPES_FAIL = "GET_REQUIREMENT_TYPES_FAIL"

/* REQUIREMENT_TYPES PROFILE*/
export const GET_REQUIREMENT_DELETED_VALUE = "GET_REQUIREMENT_DELETED_VALUE"
export const GET_REQUIREMENT_DELETED_VALUE_SUCCESS = "GET_REQUIREMENT_DELETED_VALUE_SUCCESS"
export const GET_REQUIREMENT_DELETED_VALUE_FAIL = "GET_REQUIREMENT_DELETED_VALUE_FAIL"

export const ADD_NEW_REQUIREMENT_TYPE = "ADD_NEW_REQUIREMENT_TYPE"
export const ADD_REQUIREMENT_TYPE_SUCCESS = "ADD_REQUIREMENT_TYPE_SUCCESS"
export const ADD_REQUIREMENT_TYPE_FAIL = "ADD_REQUIREMENT_TYPE_FAIL"

export const UPDATE_REQUIREMENT_TYPE = "UPDATE_REQUIREMENT_TYPE"
export const UPDATE_REQUIREMENT_TYPE_SUCCESS = "UPDATE_REQUIREMENT_TYPE_SUCCESS"
export const UPDATE_REQUIREMENT_TYPE_FAIL = "UPDATE_REQUIREMENT_TYPE_FAIL"

export const DELETE_REQUIREMENT_TYPE = "DELETE_REQUIREMENT_TYPE"
export const DELETE_REQUIREMENT_TYPE_SUCCESS = "DELETE_REQUIREMENT_TYPE_SUCCESS"
export const DELETE_REQUIREMENT_TYPE_FAIL = "DELETE_REQUIREMENT_TYPE_FAIL"