/* USER_TYPES */
export const GET_USER_TYPES = "GET_USER_TYPES"
export const GET_USER_TYPES_SUCCESS = "GET_USER_TYPES_SUCCESS"
export const GET_USER_TYPES_FAIL = "GET_USER_TYPES_FAIL"

/* USER_TYPES PROFILE*/
export const GET_REQUIREMENT_DELETED_VALUE = "GET_REQUIREMENT_DELETED_VALUE"
export const GET_REQUIREMENT_DELETED_VALUE_SUCCESS = "GET_REQUIREMENT_DELETED_VALUE_SUCCESS"
export const GET_REQUIREMENT_DELETED_VALUE_FAIL = "GET_REQUIREMENT_DELETED_VALUE_FAIL"

export const ADD_NEW_USER_TYPE = "ADD_NEW_USER_TYPE"
export const ADD_USER_TYPE_SUCCESS = "ADD_USER_TYPE_SUCCESS"
export const ADD_USER_TYPE_FAIL = "ADD_USER_TYPE_FAIL"

export const UPDATE_USER_TYPE = "UPDATE_USER_TYPE"
export const UPDATE_USER_TYPE_SUCCESS = "UPDATE_USER_TYPE_SUCCESS"
export const UPDATE_USER_TYPE_FAIL = "UPDATE_USER_TYPE_FAIL"

export const DELETE_USER_TYPE = "DELETE_USER_TYPE"
export const DELETE_USER_TYPE_SUCCESS = "DELETE_USER_TYPE_SUCCESS"
export const DELETE_USER_TYPE_FAIL = "DELETE_USER_TYPE_FAIL"