export const GET_USER_MNGS= "GET_USER_MNGS"
export const GET_USER_MNGS_SUCCESS= "GET_USER_MNGS_SUCCESS"
export const GET_USER_MNGS_FAIL="GET_USER_MNGS_FAIL"

export const ADD_NEW_USER_MNG= "ADD_NEW_USER_MNG"
export const ADD_USER_MNG_SUCCESS= "ADD_USER_MNG_SUCCESS"
export const ADD_USER_MNG_FAIL="ADD_USER_MNG_FAIL"

export const UPDATE_USER_MNG= "UPDATE_USER_MNG"
export const UPDATE_USER_MNG_SUCCESS= "UPDATE_USER_MNG_SUCCESS"
export const UPDATE_USER_MNG_FAIL="UPDATE_USER_MNG__FAIL"

export const DELETE_USER_MNG= "DELETE_USER_MNG"
export const DELETE_USER_MNG_SUCCESS= "DELETE_USER_MNG_SUCCESS"
export const DELETE_USER_MNG_FAIL= "DELETE_USER_MNG_FAIL"

export const GET_USER_MNG_DELETED_VALUE = "GET_USER_MNG_DELETED_VALUE"
export const GET_USER_MNG_DELETED_VALUE_SUCCESS = "GET_USER_MNG_DELETED_VALUE_SUCCESS"
export const GET_USER_MNG_DELETED_VALUE_FAIL = "GET_USER_MNG_DELETED_VALUE_FAIL"


export const GET_USER_FACULTIES= "GET_USER_FACULTIES"
export const GET_USER_FACULTIES_SUCCESS= "GET_USER_FACULTIES_SUCCESS"
export const GET_USER_FACULTIES_FAIL="GET_USER_FACULTIES_FAIL"

export const ADD_NEW_USER_FACULTY= "ADD_NEW_USER_FACULTY"
export const ADD_USER_FACULTY_SUCCESS= "ADD_USER_FACULTY_SUCCESS"
export const ADD_USER_FACULTY_FAIL="ADD_USER_FACULTY_FAIL"


export const DELETE_USER_FACULTY= "DELETE_USER_FACULTY"
export const DELETE_USER_FACULTY_SUCCESS= "DELETE_USER_FACULTY_SUCCESS"
export const DELETE_USER_FACULTY_FAIL= "DELETE_USER_FACULTY_FAIL"

export const GET_USER_FACULTY_DELETED_VALUE= "GET_USER_FACULTY_DELETED_VALUE"
export const GET_USER_FACULTY_DELETED_VALUE_SUCCESS= "GET_USER_FACULTY_DELETED_VALUE_SUCCESS"
export const GET_USER_FACULTY_DELETED_VALUE_FAIL= "GET_USER_FACULTY_DELETED_VALUE_FAIL"


/*user role */


export const ADD_NEW_USER_ROLE = "ADD_NEW_USER_ROLE";
export const ADD_USER_ROLE_SUCCESS = "ADD_USER_ROLE_SUCCESS";
export const ADD_USER_ROLE_FAIL = "ADD_USER_ROLE_FAIL";
