export const UNARCHIVE_COURSE_REQUESTS = "UNARCHIVE_COURSE_REQUESTS";
export const UNARCHIVE_COURSE_REQUESTS_SUCCESS =
  "UNARCHIVE_COURSE_REQUESTS_SUCCESS";
export const UNARCHIVE_COURSE_REQUESTS_FAIL = "UNARCHIVE_COURSE_REQUESTS_FAIL";

export const ADD_UNARCHIVE_COURSE_REQUEST = "ADD_UNARCHIVE_COURSE_REQUEST";
export const ADD_UNARCHIVE_COURSE_REQUEST_SUCCESS =
  "ADD_UNARCHIVE_COURSE_REQUEST_SUCCESS";
export const ADD_UNARCHIVE_COURSE_REQUEST_FAIL =
  "ADD_UNARCHIVE_COURSE_REQUEST_FAIL";

export const UPDATE_UNARCHIVE_COURSE_REQUEST =
  "UPDATE_UNARCHIVE_COURSE_REQUEST";
export const UPDATE_UNARCHIVE_COURSE_REQUEST_SUCCESS =
  "UPDATE_UNARCHIVE_COURSE_REQUEST_SUCCESS";
export const UPDATE_UNARCHIVE_COURSE_REQUEST_FAIL =
  "UPDATE_UNARCHIVE_COURSE_REQUEST_FAIL";

export const DELETE_UNARCHIVE_COURSE_REQUEST =
  "DELETE_UNARCHIVE_COURSE_REQUEST";
export const DELETE_UNARCHIVE_COURSE_REQUEST_SUCCESS =
  "DELETE_UNARCHIVE_COURSE_REQUEST_SUCCESS";
export const DELETE_UNARCHIVE_COURSE_REQUEST_FAIL =
  "DELETE_UNARCHIVE_COURSE_REQUEST_FAIL";

export const GET_UNARCHIVE_COURSE_REQUEST_DELETED_VALUE =
  "GET_UNARCHIVE_COURSE_REQUEST_DELETED_VALUE";
export const GET_UNARCHIVE_COURSE_REQUEST_DELETED_VALUE_SUCCESS =
  "GET_UNARCHIVE_COURSE_REQUEST_DELETED_VALUE_SUCCESS";
export const GET_UNARCHIVE_COURSE_REQUEST_DELETED_VALUE_FAIL =
  "GET_UNARCHIVE_COURSE_REQUEST_DELETED_VALUE_FAIL";

export const GET_OPERATIONS_NEEDED = "GET_OPERATIONS_NEEDED";
export const GET_OPERATIONS_NEEDED_SUCCESS = "GET_OPERATIONS_NEEDED_SUCCESS";
export const GET_OPERATIONS_NEEDED_FAIL = "GET_OPERATIONS_NEEDED_FAIL";
