/* FEES_DEFINITIONS */
export const GET_FEES_DEFINITION = "GET_FEES_DEFINITION";
export const GET_FEES_DEFINITION_SUCCESS = "GET_FEES_DEFINITION_SUCCESS";
export const GET_FEES_DEFINITION_FAIL = "GET_FEES_DEFINITION_FAIL";

export const GET_FEES_DEFINITION_DELETED_VALUE = "GET_FEES_DEFINITION_DELETED_VALUE";
export const GET_FEES_DEFINITION_DELETED_VALUE_SUCCESS = "GET_FEES_DEFINITION_DELETED_VALUE_SUCCESS";
export const GET_FEES_DEFINITION_DELETED_VALUE_FAIL = "GET_FEES_DEFINITION_DELETED_VALUE_FAIL";

export const ADD_NEW_FEES_DEFINITION = "ADD_NEW_FEES_DEFINITION";
export const ADD_NEW_FEES_DEFINITION_SUCCESS = "ADD_NEW_FEES_DEFINITION_SUCCESS";
export const ADD_NEW_FEES_DEFINITION_FAIL = "ADD_NEW_FEES_DEFINITION_FAIL";

export const UPDATE_FEES_DEFINITION = "UPDATE_FEES_DEFINITION";
export const UPDATE_FEES_DEFINITION_SUCCESS = "UPDATE_FEES_DEFINITION_SUCCESS";
export const UPDATE_FEES_DEFINITION_FAIL = "UPDATE_FEES_DEFINITION_FAIL";

export const DELETE_FEES_DEFINITION = "DELETE_FEES_DEFINITION";
export const DELETE_FEES_DEFINITION_SUCCESS = "DELETE_FEES_DEFINITION_SUCCESS";
export const DELETE_FEES_DEFINITION_FAIL = "DELETE_FEES_DEFINITION_FAIL";

export const COPY_FEES = "COPY_FEES"
export const COPY_FEES_SUCCESS = "COPY_FEES_SUCCESS"
export const COPY_FEES_FAIL = "COPY_FEES_FAIL"

export const GET_FEES_CONDITIONS = "GET_FEES_CONDITIONS";
export const GET_FEES_CONDITIONS_SUCCESS = "GET_FEES_CONDITIONS_SUCCESS";
export const GET_FEES_CONDITIONS_FAIL = "GET_FEES_CONDITIONS_FAIL";

export const ADD_NEW_FEES_CONDITION = "ADD_NEW_FEES_CONDITION";
export const ADD_NEW_FEES_CONDITION_SUCCESS = "ADD_NEW_FEES_CONDITION_SUCCESS";
export const ADD_NEW_FEES_CONDITION_FAIL = "ADD_NEW_FEES_CONDITION_FAIL";

export const UPDATE_FEES_CONDITION = "UPDATE_FEES_CONDITION";
export const UPDATE_FEES_CONDITION_SUCCESS = "UPDATE_FEES_CONDITION_SUCCESS";
export const UPDATE_FEES_CONDITION_FAIL = "UPDATE_FEES_CONDITION_FAIL";

export const DELETE_FEES_CONDITION = "DELETE_FEES_CONDITION";
export const DELETE_FEES_CONDITION_SUCCESS = "DELETE_FEES_CONDITION_SUCCESS";
export const DELETE_FEES_CONDITION_FAIL = "DELETE_FEES_CONDITION_FAIL";

export const GET_FEES_PRICES = "GET_FEES_PRICES";
export const GET_FEES_PRICES_SUCCESS = "GET_FEES_PRICES_SUCCESS";
export const GET_FEES_PRICES_FAIL = "GET_FEES_PRICES_FAIL";

export const ADD_NEW_FEES_PRICE = "ADD_NEW_FEES_PRICE";
export const ADD_NEW_FEES_PRICE_SUCCESS = "ADD_NEW_FEES_PRICE_SUCCESS";
export const ADD_NEW_FEES_PRICE_FAIL = "ADD_NEW_FEES_PRICE_FAIL";

export const UPDATE_FEES_PRICE = "UPDATE_FEES_PRICE";
export const UPDATE_FEES_PRICE_SUCCESS = "UPDATE_FEES_PRICE_SUCCESS";
export const UPDATE_FEES_PRICE_FAIL = "UPDATE_FEES_PRICE_FAIL";

export const DELETE_FEES_PRICE = "DELETE_FEES_PRICE";
export const DELETE_FEES_PRICE_SUCCESS = "DELETE_FEES_PRICE_SUCCESS";
export const DELETE_FEES_PRICE_FAIL = "DELETE_FEES_PRICE_FAIL";

export const COPY_FEES_PRICE = "COPY_FEES_PRICE"
export const COPY_FEES_PRICE_SUCCESS = "COPY_FEES_PRICE_SUCCESS"
export const COPY_FEES_PRICE_FAIL = "COPY_FEES_PRICE_FAIL"

export const GET_FEES_SERVICES = "GET_FEES_SERVICES";
export const GET_FEES_SERVICES_SUCCESS = "GET_FEES_SERVICES_SUCCESS";
export const GET_FEES_SERVICES_FAIL = "GET_FEES_SERVICES_FAIL";

export const ADD_NEW_FEES_SERVICE = "ADD_NEW_FEES_SERVICE";
export const ADD_NEW_FEES_SERVICE_SUCCESS = "ADD_NEW_FEES_SERVICE_SUCCESS";
export const ADD_NEW_FEES_SERVICE_FAIL = "ADD_NEW_FEES_SERVICE_FAIL";

export const UPDATE_FEES_SERVICE = "UPDATE_FEES_SERVICE";
export const UPDATE_FEES_SERVICE_SUCCESS = "UPDATE_FEES_SERVICE_SUCCESS";
export const UPDATE_FEES_SERVICE_FAIL = "UPDATE_FEES_SERVICE_FAIL";

export const DELETE_FEES_SERVICE = "DELETE_FEES_SERVICE";
export const DELETE_FEES_SERVICE_SUCCESS = "DELETE_FEES_SERVICE_SUCCESS";
export const DELETE_FEES_SERVICE_FAIL = "DELETE_FEES_SERVICE_FAIL";

export const COPY_FEES_SERVICE = "COPY_FEES_SERVICE"
export const COPY_FEES_SERVICE_SUCCESS = "COPY_FEES_SERVICE_SUCCESS"
export const COPY_FEES_SERVICE_FAIL = "COPY_FEES_SERVICE_FAIL"

export const GET_FISCAL_YEAR_DETAILS = "GET_FISCAL_YEAR_DETAILS";
export const GET_FISCAL_YEAR_DETAILS_SUCCESS = "GET_FISCAL_YEAR_DETAILS_SUCCESS";
export const GET_FISCAL_YEAR_DETAILS_FAIL = "GET_FISCAL_YEAR_DETAILS_FAIL";

export const GET_EXECUTE_METHODS = "GET_EXECUTE_METHODS";
export const GET_EXECUTE_METHODS_SUCCESS = "GET_EXECUTE_METHODS_SUCCESS";
export const GET_EXECUTE_METHODS_FAIL = "GET_EXECUTE_METHODS_FAIL";
