/* CERTIFICATE_TYPES */
export const GET_CERTIFICATE_TYPES = "GET_CERTIFICATE_TYPES"
export const GET_CERTIFICATE_TYPES_SUCCESS = "GET_CERTIFICATE_TYPES_SUCCESS"
export const GET_CERTIFICATE_TYPES_FAIL = "GET_CERTIFICATE_TYPES_FAIL"

/* CERTIFICATE_TYPES PROFILE */
export const GET_CERTIFICATE_TYPE_DELETED_VALUE = "GET_CERTIFICATE_TYPE_DELETED_VALUE"
export const GET_CERTIFICATE_TYPE_DELETED_VALUE_SUCCESS = "GET_CERTIFICATE_TYPE_DELETED_VALUE_SUCCESS"
export const GET_CERTIFICATE_TYPE_DELETED_VALUE_FAIL = "GET_CERTIFICATE_TYPE_DELETED_VALUE_FAIL"

export const ADD_NEW_CERTIFICATE_TYPE = "ADD_NEW_CERTIFICATE_TYPE"
export const ADD_CERTIFICATE_TYPE_SUCCESS = "ADD_CERTIFICATE_TYPE_SUCCESS"
export const ADD_CERTIFICATE_TYPE_FAIL = "ADD_CERTIFICATE_TYPE_FAIL"

export const UPDATE_CERTIFICATE_TYPE = "UPDATE_CERTIFICATE_TYPE"
export const UPDATE_CERTIFICATE_TYPE_SUCCESS = "UPDATE_CERTIFICATE_TYPE_SUCCESS"
export const UPDATE_CERTIFICATE_TYPE_FAIL = "UPDATE_CERTIFICATE_TYPE_FAIL"

export const DELETE_CERTIFICATE_TYPE = "DELETE_CERTIFICATE_TYPE"
export const DELETE_CERTIFICATE_TYPE_SUCCESS = "DELETE_CERTIFICATE_TYPE_SUCCESS"
export const DELETE_CERTIFICATE_TYPE_FAIL = "DELETE_CERTIFICATE_TYPE_FAIL"