export const GET_GOVERNORATES = "GET_GOVERNORATES"
export const GET_GOVERNORATES_SUCCESS = "GET_GOVERNORATES_SUCCESS"
export const GET_GOVERNORATES_FAIL = "GET_GOVERNORATES_FAIL"

/* GOVERNORATE PROFILE */
export const GET_GOVERNORATE_DELETED_VALUE = "GET_GOVERNORATE_DELETED_VALUE"
export const GET_GOVERNORATE_DELETED_VALUE_SUCCESS = "GET_GOVERNORATE_DELETED_VALUE_SUCCESS"
export const GET_GOVERNORATE_DELETED_VALUE_FAIL = "GET_GOVERNORATE_DELETED_VALUE_FAIL"

export const ADD_NEW_GOVERNORATE = "ADD_NEW_GOVERNORATE"
export const ADD_GOVERNORATE_SUCCESS = "ADD_GOVERNORATE_SUCCESS"
export const ADD_GOVERNORATE_FAIL = "ADD_GOVERNORATE_FAIL"

export const IMPORT_GOVERNORATES = "IMPORT_GOVERNORATES"
export const IMPORT_GOVERNORATES_SUCCESS = "IMPORT_GOVERNORATES_SUCCESS"
export const IMPORT_GOVERNORATES_FAIL = "IMPORT_GOVERNORATES_FAIL"

export const UPDATE_GOVERNORATE = "UPDATE_GOVERNORATE"
export const UPDATE_GOVERNORATE_SUCCESS = "UPDATE_GOVERNORATE_SUCCESS"
export const UPDATE_GOVERNORATE_FAIL = "UPDATE_GOVERNORATE_FAIL"

export const DELETE_GOVERNORATE = "DELETE_GOVERNORATE"
export const DELETE_GOVERNORATE_SUCCESS = "DELETE_GOVERNORATE_SUCCESS"
export const DELETE_GOVERNORATE_FAIL = "DELETE_GOVERNORATE_FAIL"