export const GET_TRAINEES_DECREES = "GET_TRAINEES_DECREES";
export const GET_TRAINEES_DECREES_SUCCESS = "GET_TRAINEES_DECREES_SUCCESS";
export const GET_TRAINEES_DECREES_FAIL = "GET_TRAINEES_DECREES_FAIL";

export const ADD_NEW_TRAINEE_DECREE = "ADD_NEW_TRAINEE_DECREE";
export const ADD_TRAINEE_DECREE_SUCCESS = "ADD_TRAINEE_DECREE_SUCCESS";
export const ADD_TRAINEE_DECREE_FAIL = "ADD_TRAINEE_DECREE_FAIL";

export const UPDATE_TRAINEE_DECREE = "UPDATE_TRAINEE_DECREE";
export const UPDATE_TRAINEE_DECREE_SUCCESS = "UPDATE_TRAINEE_DECREE_SUCCESS";
export const UPDATE_TRAINEE_DECREE_FAIL = "UPDATE_TRAINEE_DECREE_FAIL";

export const DELETE_TRAINEE_DECREE = "DELETE_TRAINEE_DECREE";
export const DELETE_TRAINEE_DECREE_SUCCESS = "DELETE_TRAINEE_DECREE_SUCCESS";
export const DELETE_TRAINEE_DECREE_FAIL = "DELETE_TRAINEE_DECREE_FAIL";

export const GET_TRAINEE_DECREE_DELETED_VALUE =
  "GET_TRAINEE_DECREE_DELETED_VALUE";
export const GET_TRAINEE_DECREE_DELETED_VALUE_SUCCESS =
  "GET_TRAINEE_DECREE_DELETED_VALUE_SUCCESS";
export const GET_TRAINEE_DECREE_DELETED_VALUE_FAIL =
  "GET_TRAINEE_DECREE_DELETED_VALUE_FAIL";

export const GET_FILTERED_COURSES_PLANS = "GET_FILTERED_COURSES_PLANS";
export const GET_FILTERED_COURSES_PLANS_SUCCESS =
  "GET_FILTERED_COURSES_PLANS_SUCCESS";
export const GET_FILTERED_COURSES_PLANS_FAIL =
  "GET_FILTERED_COURSES_PLANS_FAIL";

export const GET_ACADEMY_TRAINEES_DECREE = "GET_ACADEMY_TRAINEES_DECREE";
export const GET_ACADEMY_TRAINEES_DECREE_SUCCESS =
  "GET_ACADEMY_TRAINEES_DECREE_SUCCESS";
export const GET_ACADEMY_TRAINEES_DECREE_FAIL =
  "GET_ACADEMY_TRAINEES_DECREE_FAIL";

export const GET_COURSES_DECREES = "GET_COURSES_DECREES";
export const GET_COURSES_DECREES_SUCCESS = "GET_COURSES_DECREES_SUCCESS";
export const GET_COURSES_DECREES_FAIL = "GET_COURSES_DECREES_FAIL";

export const GET_DECREE_STATUS = "GET_DECREE_STATUS";
export const GET_DECREE_STATUS_SUCCESS = "GET_DECREE_STATUS_SUCCESS";
export const GET_DECREE_STATUS_FAIL = "GET_DECREE_STATUS_FAIL";

export const GET_TRAINEE_DECREES_DISMISS = "GET_TRAINEE_DECREES_DISMISS";
export const GET_TRAINEE_DECREES_DISMISS_SUCCESS =
  "GET_TRAINEE_DECREES_DISMISS_SUCCESS";
export const GET_TRAINEE_DECREES_DISMISS_FAIL =
  "GET_TRAINEE_DECREES_DISMISS_FAIL";
