export const GET_TRAINEES_DECREES = "GET_TRAINEES_DECREES";
export const GET_TRAINEES_DECREES_SUCCESS = "GET_TRAINEES_DECREES_SUCCESS";
export const GET_TRAINEES_DECREES_FAIL = "GET_TRAINEES_DECREES_FAIL";

export const ADD_NEW_TRAINEES_DECREES = "ADD_NEW_TRAINEES_DECREES";
export const ADD_TRAINEES_DECREES_SUCCESS = "ADD_TRAINEES_DECREES_SUCCESS";
export const ADD_TRAINEES_DECREES_FAIL = "ADD_TRAINEES_DECREES_FAIL";

export const UPDATE_TRAINEES_DECREES = "UPDATE_TRAINEES_DECREES";
export const UPDATE_TRAINEES_DECREES_SUCCESS =
  "UPDATE_TRAINEES_DECREES_SUCCESS";
export const UPDATE_TRAINEES_DECREES_FAIL = "UPDATE_TRAINEES_DECREES__FAIL";

export const DELETE_TRAINEES_DECREES = "DELETE_TRAINEES_DECREES";
export const DELETE_TRAINEES_DECREES_SUCCESS =
  "DELETE_TRAINEES_DECREES_SUCCESS";
export const DELETE_TRAINEES_DECREES_FAIL = "DELETE_TRAINEES_DECREES_FAIL";

export const GET_TRAINEES_DECREES_DELETED_VALUE =
  "GET_TRAINEES_DECREES_DELETED_VALUE";
export const GET_TRAINEES_DECREES_DELETED_VALUE_SUCCESS =
  "GET_TRAINEES_DECREES_DELETED_VALUE_SUCCESS";
export const GET_TRAINEES_DECREES_DELETED_VALUE_FAIL =
  "GET_TRAINEES_DECREES_DELETED_VALUE_FAIL";

export const GET_FILTERED_COURSES_PLANS = "GET_FILTERED_COURSES_PLANS";
export const GET_FILTERED_COURSES_PLANS_SUCCESS =
  "GET_FILTERED_COURSES_PLANS_SUCCESS";
export const GET_FILTERED_COURSES_PLANS_FAIL =
  "GET_FILTERED_COURSES_PLANS_FAIL";

export const GET_ACADEMY_TRAINEES_DECREE = "GET_ACADEMY_TRAINEES_DECREE";
export const GET_ACADEMY_TRAINEES_DECREE_SUCCESS =
  "GET_ACADEMY_TRAINEES_DECREE_SUCCESS";
export const GET_ACADEMY_TRAINEES_DECREE_FAIL =
  "GET_ACADEMY_TRAINEES_DECREE_FAIL";

export const GET_COURSES_DECREES = "GET_COURSES_DECREES";
export const GET_COURSES_DECREES_SUCCESS = "GET_COURSES_DECREES_SUCCESS";
export const GET_COURSES_DECREES_FAIL = "GET_COURSES_DECREES_FAIL";

export const GET_DECREE_STATUS = "GET_DECREE_STATUS";
export const GET_DECREE_STATUS_SUCCESS = "GET_DECREE_STATUS_SUCCESS";
export const GET_DECREE_STATUS_FAIL = "GET_DECREE_STATUS_FAIL";

export const GET_TRAINEE_DECREES_DISMISS = "GET_TRAINEE_DECREES_DISMISS";
export const GET_TRAINEE_DECREES_DISMISS_SUCCESS =
  "GET_TRAINEE_DECREES_DISMISS_SUCCESS";
export const GET_TRAINEE_DECREES_DISMISS_FAIL =
  "GET_TRAINEE_DECREES_DISMISS_FAIL";
