/* warining */
export const GET_EXCEPTIONAL_PERIODS = "GET_EXCEPTIONAL_PERIODS"
export const GET_EXCEPTIONAL_PERIODS_SUCCESS = "GET_EXCEPTIONAL_PERIODS_SUCCESS"
export const GET_EXCEPTIONAL_PERIODS_FAIL = "GET_EXCEPTIONAL_PERIODS_FAIL"

export const ADD_NEW_EXCEPTIONAL_PERIOD = "ADD_NEW_EXCEPTIONAL_PERIOD"
export const ADD_EXCEPTIONAL_PERIOD_SUCCESS = "ADD_EXCEPTIONAL_PERIOD_SUCCESS"
export const ADD_EXCEPTIONAL_PERIOD_FAIL = "ADD_EXCEPTIONAL_PERIOD_FAIL"

export const UPDATE_EXCEPTIONAL_PERIOD = "UPDATE_EXCEPTIONAL_PERIOD"
export const UPDATE_EXCEPTIONAL_PERIOD_SUCCESS = "UPDATE_EXCEPTIONAL_PERIOD_SUCCESS"
export const UPDATE_EXCEPTIONAL_PERIOD_FAIL = "UPDATE_EXCEPTIONAL_PERIOD_FAIL"

export const DELETE_EXCEPTIONAL_PERIOD = "DELETE_EXCEPTIONAL_PERIOD"
export const DELETE_EXCEPTIONAL_PERIOD_SUCCESS = "DELETE_EXCEPTIONAL_PERIOD_SUCCESS"
export const DELETE_EXCEPTIONAL_PERIOD_FAIL = "DELETE_EXCEPTIONAL_PERIOD_FAIL"

export const GET_EXCEPTIONAL_PERIOD_DELETED_VALUE = "GET_EXCEPTIONAL_PERIOD_DELETED_VALUE"
export const GET_EXCEPTIONAL_PERIOD_DELETED_VALUE_SUCCESS = "GET_EXCEPTIONAL_PERIOD_DELETED_VALUE_SUCCESS"
export const GET_EXCEPTIONAL_PERIOD_DELETED_VALUE_FAIL = "GET_EXCEPTIONAL_PERIOD_DELETED_VALUE_FAIL"

export const GET_EXCEPTIONAL_PERIODS_OPT = "GET_EXCEPTIONAL_PERIODS_OPT"
export const GET_EXCEPTIONAL_PERIODS_OPT_SUCCESS = "GET_EXCEPTIONAL_PERIODS_OPT_SUCCESS"
export const GET_EXCEPTIONAL_PERIODS_OPT_FAIL = "GET_EXCEPTIONAL_PERIODS_OPT_FAIL"

