export const GET_COURSES_CATALOGS = "GET_COURSES_CATALOGS"
export const GET_COURSES_CATALOGS_SUCCESS = "GET_COURSES_CATALOGS_SUCCESS"
export const GET_COURSES_CATALOGS_FAIL = "GET_COURSES_CATALOGS_FAIL"

export const GET_COURSES_CATALOGS_DELETED_VALUE = "GET_COURSES_CATALOGS_DELETED_VALUE"
export const GET_COURSES_CATALOGS_DELETED_VALUE_SUCCESS = "GET_COURSES_CATALOGS_DELETED_VALUE_SUCCESS"
export const GET_COURSES_CATALOGS_DELETED_VALUE_FAIL = "GET_COURSES_CATALOGS_DELETED_VALUE_FAIL"

export const ADD_NEW_COURSES_CATALOGS = "ADD_NEW_COURSES_CATALOGS"
export const ADD_COURSES_CATALOGS_SUCCESS = "ADD_COURSES_CATALOGS_SUCCESS"
export const ADD_COURSES_CATALOGS_FAIL = "ADD_COURSES_CATALOGS_FAIL"

export const UPDATE_COURSES_CATALOGS = "UPDATE_COURSES_CATALOGS"
export const UPDATE_COURSES_CATALOGS_SUCCESS = "UPDATE_COURSES_CATALOGS_SUCCESS"
export const UPDATE_COURSES_CATALOGS_FAIL = "UPDATE_COURSES_CATALOGS_FAIL"

export const DELETE_COURSES_CATALOGS = "DELETE_COURSES_CATALOGS"
export const DELETE_COURSES_CATALOGS_SUCCESS = "DELETE_COURSES_CATALOGS_SUCCESS"
export const DELETE_COURSES_CATALOGS_FAIL = "DELETE_COURSES_CATALOGS_FAIL"
