export const GET_COURSES_CATALOGS = "GET_COURSES_CATALOGS"
export const GET_COURSES_CATALOGS_SUCCESS = "GET_COURSES_CATALOGS_SUCCESS"
export const GET_COURSES_CATALOGS_FAIL = "GET_COURSES_CATALOGS_FAIL"

export const GET_COURSES_CATALOGS_DELETED_VALUE = "GET_COURSES_CATALOGS_DELETED_VALUE"
export const GET_COURSES_CATALOGS_DELETED_VALUE_SUCCESS = "GET_COURSES_CATALOGS_DELETED_VALUE_SUCCESS"
export const GET_COURSES_CATALOGS_DELETED_VALUE_FAIL = "GET_COURSES_CATALOGS_DELETED_VALUE_FAIL"

export const ADD_NEW_COURSES_CATALOGS = "ADD_NEW_COURSES_CATALOGS"
export const ADD_COURSES_CATALOGS_SUCCESS = "ADD_COURSES_CATALOGS_SUCCESS"
export const ADD_COURSES_CATALOGS_FAIL = "ADD_COURSES_CATALOGS_FAIL"

export const UPDATE_COURSES_CATALOGS = "UPDATE_COURSES_CATALOGS"
export const UPDATE_COURSES_CATALOGS_SUCCESS = "UPDATE_COURSES_CATALOGS_SUCCESS"
export const UPDATE_COURSES_CATALOGS_FAIL = "UPDATE_COURSES_CATALOGS_FAIL"

export const DELETE_COURSES_CATALOGS = "DELETE_COURSES_CATALOGS"
export const DELETE_COURSES_CATALOGS_SUCCESS = "DELETE_COURSES_CATALOGS_SUCCESS"
export const DELETE_COURSES_CATALOGS_FAIL = "DELETE_COURSES_CATALOGS_FAIL"

/// datalist options 

export const GET_COURSES_CATALOGS_DATALIST = "GET_COURSES_CATALOGS_DATALIST";
export const GET_COURSES_CATALOGS_DATALIST_SUCCESS = "GET_COURSES_CATALOGS_DATALIST_SUCCESS";
export const GET_COURSES_CATALOGS_DATALIST_FAIL = "GET_COURSES_CATALOGS_DATALIST_FAIL";

//// courses catalog prereqqq

export const GET_COURSE_CATALOGE_PREREQUISITES = "GET_COURSE_CATALOGE_PREREQUISITES";
export const GET_COURSE_CATALOGE_PREREQUISITES_SUCCESS = "GET_COURSE_CATALOGE_PREREQUISITES_SUCCESS";
export const GET_COURSE_CATALOGE_PREREQUISITES_FAIL = "GET_COURSE_CATALOGE_PREREQUISITES_FAIL";

export const GET_COURSE_CATALOGE_PREREQUISITES_DELETED_VALUE = "GET_COURSE_CATALOGE_PREREQUISITES_DELETED_VALUE";
export const GET_COURSE_CATALOGE_PREREQUISITES_DELETED_VALUE_SUCCESS = "GET_COURSE_CATALOGE_PREREQUISITES_DELETED_VALUE_SUCCESS";
export const GET_COURSE_CATALOGE_PREREQUISITES_DELETED_VALUE_FAIL = "GET_COURSE_CATALOGE_PREREQUISITES_DELETED_VALUE_FAIL";

export const ADD_NEW_COURSE_CATALOGE_PREREQUISITES = "ADD_NEW_COURSE_CATALOGE_PREREQUISITES";
export const ADD_COURSE_CATALOGE_PREREQUISITES_SUCCESS = "ADD_COURSE_CATALOGE_PREREQUISITES_SUCCESS";
export const ADD_COURSE_CATALOGE_PREREQUISITES_FAIL = "ADD_COURSE_CATALOGE_PREREQUISITES_FAIL";

export const UPDATE_COURSE_CATALOGE_PREREQUISITES = "UPDATE_COURSE_CATALOGE_PREREQUISITES";
export const UPDATE_COURSE_CATALOGE_PREREQUISITES_SUCCESS = "UPDATE_COURSE_CATALOGE_PREREQUISITES_SUCCESS";
export const UPDATE_COURSE_CATALOGE_PREREQUISITES_FAIL = "UPDATE_COURSE_CATALOGE_PREREQUISITES_FAIL";

export const DELETE_COURSE_CATALOGE_PREREQUISITES = "DELETE_COURSE_CATALOGE_PREREQUISITES";
export const DELETE_COURSE_CATALOGE_PREREQUISITES_SUCCESS = "DELETE_COURSE_CATALOGE_PREREQUISITES_SUCCESS";
export const DELETE_COURSE_CATALOGE_PREREQUISITES_FAIL = "DELETE_COURSE_CATALOGE_PREREQUISITES_FAIL";
