/* COUNTRIES */
export const GET_COUNTRIES = "GET_COUNTRIES"
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS"
export const GET_COUNTRIES_FAIL = "GET_COUNTRIES_FAIL"

export const GET_COUNTRY_DELETED_VALUE = "GET_COUNTRY_DELETED_VALUE"
export const GET_COUNTRY_DELETED_VALUE_SUCCESS = "GET_COUNTRY_DELETED_VALUE_SUCCESS"
export const GET_COUNTRY_DELETED_VALUE_FAIL = "GET_COUNTRY_DELETED_VALUE_FAIL"

export const ADD_NEW_COUNTRY = "ADD_NEW_COUNTRY"
export const ADD_COUNTRY_SUCCESS = "ADD_COUNTRY_SUCCESS"
export const ADD_COUNTRY_FAIL = "ADD_COUNTRY_FAIL"

export const IMPORT_COUNTRIES = "IMPORT_COUNTRIES"
export const IMPORT_COUNTRIES_SUCCESS = "IMPORT_COUNTRIES_SUCCESS"
export const IMPORT_COUNTRIES_FAIL = "IMPORT_COUNTRIES_FAIL"

export const UPDATE_COUNTRY = "UPDATE_COUNTRY"
export const UPDATE_COUNTRY_SUCCESS = "UPDATE_COUNTRY_SUCCESS"
export const UPDATE_COUNTRY_FAIL = "UPDATE_COUNTRY_FAIL"

export const DELETE_COUNTRY = "DELETE_COUNTRY"
export const DELETE_COUNTRY_SUCCESS = "DELETE_COUNTRY_SUCCESS"
export const DELETE_COUNTRY_FAIL = "DELETE_COUNTRY_FAIL"