/* NATIONALITIES */
export const GET_NATIONALITIES = "GET_NATIONALITIES"
export const GET_NATIONALITIES_SUCCESS = "GET_NATIONALITIES_SUCCESS"
export const GET_NATIONALITIES_FAIL = "GET_NATIONALITIES_FAIL"

/* NATIONALITIES PROFILE */
export const GET_NATIONALITY_DELETED_VALUE = "GET_NATIONALITY_DELETED_VALUE"
export const GET_NATIONALITY_DELETED_VALUE_SUCCESS = "GET_NATIONALITY_DELETED_VALUE_SUCCESS"
export const GET_NATIONALITY_DELETED_VALUE_FAIL = "GET_NATIONALITY_DELETED_VALUE_FAIL"

export const ADD_NEW_NATIONALITY = "ADD_NEW_NATIONALITY"
export const ADD_NATIONALITY_SUCCESS = "ADD_NATIONALITY_SUCCESS"
export const ADD_NATIONALITY_FAIL = "ADD_NATIONALITY_FAIL"

export const IMPORT_NATIONALITIES = "IMPORT_NATIONALITIES"
export const IMPORT_NATIONALITIES_SUCCESS = "IMPORT_NATIONALITIES_SUCCESS"
export const IMPORT_NATIONALITIES_FAIL = "IMPORT_NATIONALITIES_FAIL"

export const UPDATE_NATIONALITY = "UPDATE_NATIONALITY"
export const UPDATE_NATIONALITY_SUCCESS = "UPDATE_NATIONALITY_SUCCESS"
export const UPDATE_NATIONALITY_FAIL = "UPDATE_NATIONALITY_FAIL"

export const DELETE_NATIONALITY = "DELETE_NATIONALITY"
export const DELETE_NATIONALITY_SUCCESS = "DELETE_NATIONALITY_SUCCESS"
export const DELETE_NATIONALITY_FAIL = "DELETE_NATIONALITY_FAIL"