export const GET_COURSES = "GET_COURSES"
export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS"
export const GET_COURSES_FAIL = "GET_COURSES_FAIL"

export const ADD_NEW_COURSE = "ADD_NEW_COURSE"
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS"
export const ADD_COURSE_FAIL = "ADD_COURSE_FAIL"

export const UPDATE_COURSE = "UPDATE_COURSE"
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS"
export const UPDATE_COURSE_FAIL = "UPDATE_COURSE_FAIL"

export const DELETE_COURSE = "DELETE_COURSE"
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS"
export const DELETE_COURSE_FAIL = "DELETE_COURSE_FAIL"

export const GET_COURSE_REQUIRED_COURSES = "GET_COURSE_REQUIRED_COURSES"
export const GET_COURSE_REQUIRED_COURSES_SUCCESS = "GET_COURSE_REQUIRED_COURSES_SUCCESS"
export const GET_COURSE_REQUIRED_COURSES_FAIL = "GET_COURSE_REQUIRED_COURSES_FAIL"

export const ADD_NEW_COURSE_REQUIRED_COURSE = "ADD_NEW_COURSE_REQUIRED_COURSE"
export const ADD_COURSE_REQUIRED_COURSE_SUCCESS = "ADD_COURSE_REQUIRED_COURSE_SUCCESS"
export const ADD_COURSE_REQUIRED_COURSE_FAIL = "ADD_COURSE_REQUIRED_COURSE_FAIL"

export const UPDATE_COURSE_REQUIRED_COURSE = "UPDATE_COURSE_REQUIRED_COURSE"
export const UPDATE_COURSE_REQUIRED_COURSE_SUCCESS = "UPDATE_COURSE_REQUIRED_COURSE_SUCCESS"
export const UPDATE_COURSE_REQUIRED_COURSE_FAIL = "UPDATE_COURSE_REQUIRED_COURSE_FAIL"

export const DELETE_COURSE_REQUIRED_COURSE = "DELETE_COURSE_REQUIRED_COURSE"
export const DELETE_COURSE_REQUIRED_COURSE_SUCCESS = "DELETE_COURSE_REQUIRED_COURSE_SUCCESS"
export const DELETE_COURSE_REQUIRED_COURSE_FAIL = "DELETE_COURSE_REQUIRED_COURSE_FAIL"

export const GET_COURSES_OPT = "GET_COURSES_OPT"
export const GET_COURSES_OPT_SUCCESS = "GET_COURSES_OPT_SUCCESS"
export const GET_COURSES_OPT_FAIL = "GET_COURSES_OPT_FAIL"

export const GET_COURSE_DELETED_VALUE = "GET_COURSE_DELETED_VALUE"
export const GET_COURSE_DELETED_VALUE_SUCCESS = "GET_COURSE_DELETED_VALUE_SUCCESS"
export const GET_COURSE_DELETED_VALUE_FAIL = "GET_COURSE_DELETED_VALUE_FAIL"
