/* MARKS_OBJECTIONS */
export const GET_MARKS_OBJECTIONS = "GET_MARKS_OBJECTIONS";
export const GET_MARKS_OBJECTIONS_SUCCESS = "GET_MARKS_OBJECTIONS_SUCCESS";
export const GET_MARKS_OBJECTIONS_FAIL = "GET_MARKS_OBJECTIONS_FAIL";

/* MARKS_OBJECTIONS */
export const GET_MARK_OBJECTION_DELETED_VALUE =
  "GET_MARK_OBJECTION_DELETED_VALUE";
export const GET_MARK_OBJECTION_DELETED_VALUE_SUCCESS =
  "GET_MARK_OBJECTION_DELETED_VALUE_SUCCESS";
export const GET_MARK_OBJECTION_DELETED_VALUE_FAIL =
  "GET_MARK_OBJECTION_DELETED_VALUE_FAIL";

export const ADD_NEW_MARK_OBJECTION = "ADD_NEW_MARK_OBJECTION";
export const ADD_MARK_OBJECTION_SUCCESS = "ADD_MARK_OBJECTION_SUCCESS";
export const ADD_MARK_OBJECTION_FAIL = "ADD_MARK_OBJECTION_FAIL";

export const UPDATE_MARK_OBJECTION = "UPDATE_MARK_OBJECTION";
export const UPDATE_MARK_OBJECTION_SUCCESS = "UPDATE_MARK_OBJECTION_SUCCESS";
export const UPDATE_MARK_OBJECTION_FAIL = "UPDATE_MARK_OBJECTION_FAIL";

export const DELETE_MARK_OBJECTION = "DELETE_MARK_OBJECTION";
export const DELETE_MARK_OBJECTION_SUCCESS = "DELETE_MARK_OBJECTION_SUCCESS";
export const DELETE_MARK_OBJECTION_FAIL = "DELETE_MARK_OBJECTION_FAIL";

/* REQUEST_STATUS */
export const GET_REQUEST_STATUS = "GET_REQUEST_STATUS";
export const GET_REQUEST_STATUS_SUCCESS = "GET_REQUEST_STATUS_SUCCESS";
export const GET_REQUEST_STATUS_FAIL = "GET_REQUEST_STATUS_FAIL";

/* REQUEST_TYPES */
export const GET_REQUEST_TYPES = "GET_REQUEST_TYPES";
export const GET_REQUEST_TYPES_SUCCESS = "GET_REQUEST_TYPES_SUCCESS";
export const GET_REQUEST_TYPES_FAIL = "GET_REQUEST_TYPES_FAIL";

/*CoursesObjection */
export const GET_FILTERED_COURSES_OBJECTION = "GET_FILTERED_COURSES_OBJECTION";
export const GET_FILTERED_COURSES_OBJECTION_SUCCESS =
  "GET_FILTERED_COURSES_OBJECTION_SUCCESS";
export const GET_FILTERED_COURSES_OBJECTION_FAIL =
  "GET_FILTERED_COURSES_OBJECTION_FAIL";
