/* CERTIFICATES */
export const GET_CERTIFICATES = "GET_CERTIFICATES";
export const GET_CERTIFICATES_SUCCESS = "GET_CERTIFICATES_SUCCESS";
export const GET_CERTIFICATES_FAIL = "GET_CERTIFICATES_FAIL";

export const ADD_NEW_CERTIFICATE = "ADD_NEW_CERTIFICATE";
export const ADD_CERTIFICATE_SUCCESS = "ADD_CERTIFICATE_SUCCESS";
export const ADD_CERTIFICATE_FAIL = "ADD_CERTIFICATE_FAIL";

export const UPDATE_CERTIFICATE = "UPDATE_CERTIFICATE";
export const UPDATE_CERTIFICATE_SUCCESS = "UPDATE_CERTIFICATE_SUCCESS";
export const UPDATE_CERTIFICATE_FAIL = "UPDATE_CERTIFICATE_FAIL";

export const DELETE_CERTIFICATE = "DELETE_CERTIFICATE";
export const DELETE_CERTIFICATE_SUCCESS = "DELETE_CERTIFICATE_SUCCESS";
export const DELETE_CERTIFICATE_FAIL = "DELETE_CERTIFICATE_FAIL";

export const GET_CERTIFICATE_DELETED_VALUE = "GET_CERTIFICATE_DELETED_VALUE";
export const GET_CERTIFICATE_DELETED_VALUE_SUCCESS =
  "GET_CERTIFICATE_DELETED_VALUE_SUCCESS";
export const GET_CERTIFICATE_DELETED_VALUE_FAIL =
  "GET_CERTIFICATE_DELETED_VALUE_FAIL";

/* CERTIFICATES */
export const GET_FILTERED_COURSES_CERTIFICATES =
  "GET_FILTERED_COURSES_CERTIFICATES";
export const GET_FILTERED_COURSES_CERTIFICATES_SUCCESS =
  "GET_FILTERED_COURSES_CERTIFICATES_SUCCESS";
export const GET_FILTERED_COURSES_CERTIFICATES_FAIL =
  "GET_FILTERED_COURSES_CERTIFICATES_FAIL";
