/* GRADES */
export const GET_CHECKED_GRADES = "GET_CHECKED_GRADES";
export const GET_CHECKED_GRADES_SUCCESS = "GET_CHECKED_GRADES_SUCCESS";
export const GET_CHECKED_GRADES_FAIL = "GET_CHECKED_GRADES_FAIL";

export const IMPORT_CHECKED_GRADES = "IMPORT_CHECKED_GRADES";
export const IMPORT_CHECKED_GRADES_SUCCESS = "IMPORT_CHECKED_GRADES_SUCCESS";
export const IMPORT_CHECKED_GRADES_FAIL = "IMPORT_CHECKED_GRADES_FAIL";

export const UPDATE_CHECKED_GRADE = "UPDATE_CHECKED_GRADE";
export const UPDATE_CHECKED_GRADE_SUCCESS = "UPDATE_CHECKED_GRADE_SUCCESS";
export const UPDATE_CHECKED_GRADE_FAIL = "UPDATE_CHECKED_GRADE_FAIL";
