/* STUDENTS_REQUESTS */
export const GET_STUDENTS_REQUESTS = "GET_STUDENTS_REQUESTS"
export const GET_STUDENTS_REQUESTS_SUCCESS = "GET_STUDENTS_REQUESTS_SUCCESS"
export const GET_STUDENTS_REQUESTS_FAIL = "GET_STUDENTS_REQUESTS_FAIL"

export const ADD_NEW_STUDENT_REQUEST = "ADD_NEW_STUDENT_REQUEST"
export const ADD_STUDENT_REQUEST_SUCCESS = "ADD_STUDENT_REQUEST_SUCCESS"
export const ADD_STUDENT_REQUEST_FAIL = "ADD_STUDENT_REQUEST_FAIL"

export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST"
export const UPDATE_STUDENT_REQUEST_SUCCESS = "UPDATE_STUDENT_REQUEST_SUCCESS"
export const UPDATE_STUDENT_REQUEST_FAIL = "UPDATE_STUDENT_REQUEST_FAIL"

export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST"
export const DELETE_STUDENT_REQUEST_SUCCESS = "DELETE_STUDENT_REQUEST_SUCCESS"
export const DELETE_STUDENT_REQUEST_FAIL = "DELETE_STUDENT_REQUEST_FAIL"

export const GET_PREV_UNI_COURSES = "GET_PREV_UNI_COURSES"
export const GET_PREV_UNI_COURSES_SUCCESS = "GET_PREV_UNI_COURSES_SUCCESS"
export const GET_PREV_UNI_COURSES_FAIL = "GET_PREV_UNI_COURSES_FAIL"

export const ADD_NEW_PREV_UNI_COURSE = "ADD_NEW_PREV_UNI_COURSE"
export const ADD_PREV_UNI_COURSE_SUCCESS = "ADD_PREV_UNI_COURSE_SUCCESS"
export const ADD_PREV_UNI_COURSE_FAIL = "ADD_PREV_UNI_COURSE_FAIL"

export const UPDATE_PREV_UNI_COURSE = "UPDATE_PREV_UNI_COURSE"
export const UPDATE_PREV_UNI_COURSE_SUCCESS = "UPDATE_PREV_UNI_COURSE_SUCCESS"
export const UPDATE_PREV_UNI_COURSE_FAIL = "UPDATE_PREV_UNI_COURSE_FAIL"

export const DELETE_PREV_UNI_COURSE = "DELETE_PREV_UNI_COURSE"
export const DELETE_PREV_UNI_COURSE_SUCCESS = "DELETE_PREV_UNI_COURSE_SUCCESS"
export const DELETE_PREV_UNI_COURSE_FAIL = "DELETE_PREV_UNI_COURSE_FAIL"

export const GET_TRANSFER_COURSES = "GET_TRANSFER_COURSES"
export const GET_TRANSFER_COURSES_SUCCESS = "GET_TRANSFER_COURSES_SUCCESS"
export const GET_TRANSFER_COURSES_FAIL = "GET_TRANSFER_COURSES_FAIL"

export const ADD_NEW_TRANSFER_COURSE = "ADD_NEW_TRANSFER_COURSE"
export const ADD_TRANSFER_COURSE_SUCCESS = "ADD_TRANSFER_COURSE_SUCCESS"
export const ADD_TRANSFER_COURSE_FAIL = "ADD_TRANSFER_COURSE_FAIL"

export const UPDATE_TRANSFER_COURSE = "UPDATE_TRANSFER_COURSE"
export const UPDATE_TRANSFER_COURSE_SUCCESS = "UPDATE_TRANSFER_COURSE_SUCCESS"
export const UPDATE_TRANSFER_COURSE_FAIL = "UPDATE_TRANSFER_COURSE_FAIL"

export const DELETE_TRANSFER_COURSE = "DELETE_TRANSFER_COURSE"
export const DELETE_TRANSFER_COURSE_SUCCESS = "DELETE_TRANSFER_COURSE_SUCCESS"
export const DELETE_TRANSFER_COURSE_FAIL = "DELETE_TRANSFER_COURSE_FAIL"

export const UPDATE_TRANSFER_COURSE_STATE = "UPDATE_TRANSFER_COURSE_STATE"
export const UPDATE_TRANSFER_COURSE_STATE_SUCCESS = "UPDATE_TRANSFER_COURSE_STATE_SUCCESS"
export const UPDATE_TRANSFER_COURSE_STATE_FAIL = "UPDATE_TRANSFER_COURSE_STATE_FAIL"

export const GET_LAST_REQUEST_NUM = "GET_LAST_REQUEST_NUM"
export const GET_LAST_REQUEST_NUM_SUCCESS = "GET_LAST_REQUEST_NUM_SUCCESS"
export const GET_LAST_REQUEST_NUM_FAIL = "GET_LAST_REQUEST_NUM_FAIL"

export const GET_REQUEST_DETAILS = "GET_REQUEST_DETAILS"
export const GET_REQUEST_DETAILS_SUCCESS = "GET_REQUEST_DETAILS_SUCCESS"
export const GET_REQUEST_DETAILS_FAIL = "GET_REQUEST_DETAILS_FAIL"
