/* COURSE DISTRIBUTIONS */
export const GET_COURSE_DISTRIBUTIONS = "GET_COURSE_DISTRIBUTIONS"
export const GET_COURSE_DISTRIBUTIONS_SUCCESS = "GET_COURSE_DISTRIBUTIONS_SUCCESS"
export const GET_COURSE_DISTRIBUTIONS_FAIL = "GET_COURSE_DISTRIBUTIONS_FAIL"

/* COURSE DISTRIBUTION PROFILE */
export const GET_COURSE_DISTRIBUTION_DELETED_VALUE = "GET_COURSE_DISTRIBUTION_DELETED_VALUE"
export const GET_COURSE_DISTRIBUTION_DELETED_VALUE_SUCCESS = "GET_COURSE_DISTRIBUTION_DELETED_VALUE_SUCCESS"
export const GET_COURSE_DISTRIBUTION_DELETED_VALUE_FAIL = "GET_COURSE_DISTRIBUTION_DELETED_VALUE_FAIL"

export const ADD_NEW_COURSE_DISTRIBUTION = "ADD_NEW_COURSE_DISTRIBUTION"
export const ADD_COURSE_DISTRIBUTION_SUCCESS = "ADD_COURSE_DISTRIBUTION_SUCCESS"
export const ADD_COURSE_DISTRIBUTION_FAIL = "ADD_COURSE_DISTRIBUTION_FAIL"

export const UPDATE_COURSE_DISTRIBUTION = "UPDATE_COURSE_DISTRIBUTION"
export const UPDATE_COURSE_DISTRIBUTION_SUCCESS = "UPDATE_COURSE_DISTRIBUTION_SUCCESS"
export const UPDATE_COURSE_DISTRIBUTION_FAIL = "UPDATE_COURSE_DISTRIBUTION_FAIL"

export const DELETE_COURSE_DISTRIBUTION = "DELETE_COURSE_DISTRIBUTION"
export const DELETE_COURSE_DISTRIBUTION_SUCCESS = "DELETE_COURSE_DISTRIBUTION_SUCCESS"
export const DELETE_COURSE_DISTRIBUTION_FAIL = "DELETE_COURSE_DISTRIBUTION_FAIL"
