/* LEVELING_DECISIONS */
export const GET_LEVELING_DECISIONS = "GET_LEVELING_DECISIONS"
export const GET_LEVELING_DECISIONS_SUCCESS = "GET_LEVELING_DECISIONS_SUCCESS"
export const GET_LEVELING_DECISIONS_FAIL = "GET_LEVELING_DECISIONS_FAIL"


export const ADD_NEW_LEVELING_DECISION = "ADD_NEW_LEVELING_DECISION"
export const ADD_LEVELING_DECISION_SUCCESS = "ADD_LEVELING_DECISION_SUCCESS"
export const ADD_LEVELING_DECISION_FAIL = "ADD_LEVELING_DECISION_FAIL"

export const UPDATE_LEVELING_DECISION = "UPDATE_LEVELING_DECISION"
export const UPDATE_LEVELING_DECISION_SUCCESS = "UPDATE_LEVELING_DECISION_SUCCESS"
export const UPDATE_LEVELING_DECISION_FAIL = "UPDATE_LEVELING_DECISION_FAIL"

export const DELETE_LEVELING_DECISION = "DELETE_LEVELING_DECISION"
export const DELETE_LEVELING_DECISION_SUCCESS = "DELETE_LEVELING_DECISION_SUCCESS"
export const DELETE_LEVELING_DECISION_FAIL = "DELETE_LEVELING_DECISION_FAIL"

/* LEVELING_DECISION_DETAILS */
export const GET_LEVELING_DECISION_DETAILS = "GET_LEVELING_DECISION_DETAILS"
export const GET_LEVELING_DECISION_DETAILS_SUCCESS = "GET_LEVELING_DECISION_DETAILS_SUCCESS"
export const GET_LEVELING_DECISION_DETAILS_FAIL = "GET_LEVELING_DECISION_DETAILS_FAIL"


export const ADD_NEW_LEVELING_DECISION_DETAIL = "ADD_NEW_LEVELING_DECISION_DETAIL"
export const ADD_LEVELING_DECISION_DETAIL_SUCCESS = "ADD_LEVELING_DECISION_DETAIL_SUCCESS"
export const ADD_LEVELING_DECISION_DETAIL_FAIL = "ADD_LEVELING_DECISION_DETAIL_FAIL"

export const UPDATE_LEVELING_DECISION_DETAIL = "UPDATE_LEVELING_DECISION_DETAIL"
export const UPDATE_LEVELING_DECISION_DETAIL_SUCCESS = "UPDATE_LEVELING_DECISION_DETAIL_SUCCESS"
export const UPDATE_LEVELING_DECISION_DETAIL_FAIL = "UPDATE_LEVELING_DECISION_DETAIL_FAIL"

export const DELETE_LEVELING_DECISION_DETAIL = "DELETE_LEVELING_DECISION_DETAIL"
export const DELETE_LEVELING_DECISION_DETAIL_SUCCESS = "DELETE_LEVELING_DECISION_DETAIL_SUCCESS"
export const DELETE_LEVELING_DECISION_DETAIL_FAIL = "DELETE_LEVELING_DECISION_DETAIL_FAIL"

export const GET_LEVELING_DECISION_DELETED_VALUE = "GET_LEVELING_DECISION_DELETED_VALUE"
export const GET_LEVELING_DECISION_DELETED_VALUE_SUCCESS = "GET_LEVELING_DECISION_DELETED_VALUE_SUCCESS"
export const GET_LEVELING_DECISION_DELETED_VALUE_FAIL = "GET_LEVELING_DECISION_DELETED_VALUE_FAIL"


export const GET_LEVELING_DECISION_DETAILS_DELETED_VALUE = "GET_LEVELING_DECISION_DETAILS_DELETED_VALUE"
export const GET_LEVELING_DECISION_DETAILS_DELETED_VALUE_SUCCESS = "GET_LEVELING_DECISION_DETAILS_DELETED_VALUE_SUCCESS"
export const GET_LEVELING_DECISION_DETAILS_DELETED_VALUE_FAIL = "GET_LEVELING_DECISION_DETAILS_DELETED_VALUE_FAIL"

/* COPYFACUTLY */

export const COPY_FACULTY = "COPY_FACULTY"
export const COPY_FACULTY_SUCCESS = "COPY_FACULTY_SUCCESS"
export const COPY_FACULTY_FAIL = "COPY_FACULTY_FAIL"