/* ADMISSION_CONDITIONS */
export const GET_ADMISSION_CONDITIONS = "GET_ADMISSION_CONDITIONS"
export const GET_ADMISSION_CONDITIONS_SUCCESS = "GET_ADMISSION_CONDITIONS_SUCCESS"
export const GET_ADMISSION_CONDITIONS_FAIL = "GET_ADMISSION_CONDITIONS_FAIL"

export const ADD_NEW_ADMISSION_CONDITION = "ADD_NEW_ADMISSION_CONDITION"
export const ADD_ADMISSION_CONDITION_SUCCESS = "ADD_ADMISSION_CONDITION_SUCCESS"
export const ADD_ADMISSION_CONDITION_FAIL = "ADD_ADMISSION_CONDITION_FAIL"

export const UPDATE_ADMISSION_CONDITION = "UPDATE_ADMISSION_CONDITION"
export const UPDATE_ADMISSION_CONDITION_SUCCESS = "UPDATE_ADMISSION_CONDITION_SUCCESS"
export const UPDATE_ADMISSION_CONDITION_FAIL = "UPDATE_ADMISSION_CONDITION_FAIL"

export const DELETE_ADMISSION_CONDITION = "DELETE_ADMISSION_CONDITION"
export const DELETE_ADMISSION_CONDITION_SUCCESS = "DELETE_ADMISSION_CONDITION_SUCCESS"
export const DELETE_ADMISSION_CONDITION_FAIL = "DELETE_ADMISSION_CONDITION_FAIL"


export const GET_ADMISSION_SETTING = "GET_ADMISSION_SETTING"


export const GET_FILTERED_FACULTIES = "GET_FILTERED_FACULTIES"
export const GET_FILTERED_FACULTIES_SUCCESS = "GET_FILTERED_FACULTIES_SUCCESS"
export const GET_FILTERED_FACULTIES_FAIL = "GET_FILTERED_FACULTIES_FAIL"

export const GET_ADMISSION_CONDITION_DELETED_VALUE = "GET_ADMISSION_CONDITION_DELETED_VALUE"
export const GET_ADMISSION_CONDITION_DELETED_VALUE_SUCCESS = "GET_ADMISSION_CONDITION_DELETED_VALUE_SUCCESS"
export const GET_ADMISSION_CONDITION_DELETED_VALUE_FAIL = "GET_ADMISSION_CONDITION_DELETED_VALUE_FAIL"

export const COPY_ADMISSION_COND = "COPY_ADMISSION_COND"
export const COPY_ADMISSION_COND_SUCCESS = "COPY_ADMISSION_COND_SUCCESS"
export const COPY_ADMISSION_COND_FAIL = "COPY_ADMISSION_COND_FAIL"




