export const GET_TRAINING_FORMATS = "GET_TRAINING_FORMATS"
export const GET_TRAINING_FORMATS_SUCCESS = "GET_TRAINING_FORMATS_SUCCESS"
export const GET_TRAINING_FORMATS_FAIL = "GET_TRAINING_FORMATS_FAIL"

export const GET_TRAINING_FORMAT_DELETED_VALUE = "GET_TRAINING_FORMAT_DELETED_VALUE"
export const GET_TRAINING_FORMAT_DELETED_VALUE_SUCCESS = "GET_TRAINING_FORMAT_DELETED_VALUE_SUCCESS"
export const GET_TRAINING_FORMAT_DELETED_VALUE_FAIL = "GET_TRAINING_FORMAT_DELETED_VALUE_FAIL"

export const ADD_NEW_TRAINING_FORMAT = "ADD_NEW_TRAINING_FORMAT"
export const ADD_TRAINING_FORMAT_SUCCESS = "ADD_TRAINING_FORMAT_SUCCESS"
export const ADD_TRAINING_FORMAT_FAIL = "ADD_TRAINING_FORMAT_FAIL"

export const UPDATE_TRAINING_FORMAT = "UPDATE_TRAINING_FORMAT"
export const UPDATE_TRAINING_FORMAT_SUCCESS = "UPDATE_TRAINING_FORMAT_SUCCESS"
export const UPDATE_TRAINING_FORMAT_FAIL = "UPDATE_TRAINING_FORMAT_FAIL"

export const DELETE_TRAINING_FORMAT = "DELETE_TRAINING_FORMAT"
export const DELETE_TRAINING_FORMAT_SUCCESS = "DELETE_TRAINING_FORMAT_SUCCESS"
export const DELETE_TRAINING_FORMAT_FAIL = "DELETE_TRAINING_FORMAT_FAIL"
