export const GET_HIDDEN_GRADES = "GET_HIDDEN_GRADES"
export const GET_HIDDEN_GRADES_SUCCESS = "GET_HIDDEN_GRADES_SUCCESS"
export const GET_HIDDEN_GRADES_FAIL = "GET_HIDDEN_GRADES_FAIL"

export const GET_HIDDEN_GRADE_DELETED_VALUE = "GET_HIDDEN_GRADE_DELETED_VALUE"
export const GET_HIDDEN_GRADE_DELETED_VALUE_SUCCESS = "GET_HIDDEN_GRADE_DELETED_VALUE_SUCCESS"
export const GET_HIDDEN_GRADE_DELETED_VALUE_FAIL = "GET_HIDDEN_GRADE_DELETED_VALUE_FAIL"

export const ADD_NEW_HIDDEN_GRADE = "ADD_NEW_HIDDEN_GRADE"
export const ADD_HIDDEN_GRADE_SUCCESS = "ADD_HIDDEN_GRADE_SUCCESS"
export const ADD_HIDDEN_GRADE_FAIL = "ADD_HIDDEN_GRADE_FAIL"

export const UPDATE_HIDDEN_GRADE = "UPDATE_HIDDEN_GRADE"
export const UPDATE_HIDDEN_GRADE_SUCCESS = "UPDATE_HIDDEN_GRADE_SUCCESS"
export const UPDATE_HIDDEN_GRADE_FAIL = "UPDATE_HIDDEN_GRADE_FAIL"

export const DELETE_HIDDEN_GRADE = "DELETE_HIDDEN_GRADE"
export const DELETE_HIDDEN_GRADE_SUCCESS = "DELETE_HIDDEN_GRADE_SUCCESS"
export const DELETE_HIDDEN_GRADE_FAIL = "DELETE_HIDDEN_GRADE_FAIL"