/* JUSTIFY_TRAINEES_ABSENCE */
export const GET_JUSTIFY_TRAINEES_ABSENCE = "GET_JUSTIFY_TRAINEES_ABSENCE";
export const GET_JUSTIFY_TRAINEES_ABSENCE_SUCCESS =
  "GET_JUSTIFY_TRAINEES_ABSENCE_SUCCESS";
export const GET_JUSTIFY_TRAINEES_ABSENCE_FAIL =
  "GET_JUSTIFY_TRAINEES_ABSENCE_FAIL";

/* JUSTIFY_TRAINEE_ABSENCE PROFILE */
export const GET_JUSTIFY_TRAINEE_ABSENCE_DELETED_VALUE =
  "GET_JUSTIFY_TRAINEE_ABSENCE_DELETED_VALUE";
export const GET_JUSTIFY_TRAINEE_ABSENCE_DELETED_VALUE_SUCCESS =
  "GET_JUSTIFY_TRAINEE_ABSENCE_DELETED_VALUE_SUCCESS";
export const GET_JUSTIFY_TRAINEE_ABSENCE_DELETED_VALUE_FAIL =
  "GET_JUSTIFY_TRAINEE_ABSENCE_DELETED_VALUE_FAIL";

export const ADD_NEW_JUSTIFY_TRAINEE_ABSENCE =
  "ADD_NEW_JUSTIFY_TRAINEE_ABSENCE";
export const ADD_JUSTIFY_TRAINEE_ABSENCE_SUCCESS =
  "ADD_JUSTIFY_TRAINEE_ABSENCE_SUCCESS";
export const ADD_JUSTIFY_TRAINEE_ABSENCE_FAIL =
  "ADD_JUSTIFY_TRAINEE_ABSENCE_FAIL";

export const UPDATE_JUSTIFY_TRAINEE_ABSENCE = "UPDATE_JUSTIFY_TRAINEE_ABSENCE";
export const UPDATE_JUSTIFY_TRAINEE_ABSENCE_SUCCESS =
  "UPDATE_JUSTIFY_TRAINEE_ABSENCE_SUCCESS";
export const UPDATE_JUSTIFY_TRAINEE_ABSENCE_FAIL =
  "UPDATE_JUSTIFY_TRAINEE_ABSENCE_FAIL";

export const DELETE_JUSTIFY_TRAINEE_ABSENCE = "DELETE_JUSTIFY_TRAINEE_ABSENCE";
export const DELETE_JUSTIFY_TRAINEE_ABSENCE_SUCCESS =
  "DELETE_JUSTIFY_TRAINEE_ABSENCE_SUCCESS";
export const DELETE_JUSTIFY_TRAINEE_ABSENCE_FAIL =
  "DELETE_JUSTIFY_TRAINEE_ABSENCE_FAIL";
