/* EMPLOYEES */
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";
export const GET_EMPLOYEES_FAIL = "GET_EMPLOYEES_FAIL";

/* EMPLOYEES */
export const GET_EMPLOYEE_DELETED_VALUE = "GET_EMPLOYEE_DELETED_VALUE";
export const GET_EMPLOYEE_DELETED_VALUE_SUCCESS =
  "GET_EMPLOYEE_DELETED_VALUE_SUCCESS";
export const GET_EMPLOYEE_DELETED_VALUE_FAIL =
  "GET_EMPLOYEE_DELETED_VALUE_FAIL";

export const ADD_NEW_EMPLOYEE = "ADD_NEW_EMPLOYEE";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAIL = "ADD_EMPLOYEE_FAIL";

export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_FAIL = "UPDATE_EMPLOYEE_FAIL";

export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_FAIL = "DELETE_EMPLOYEE_FAIL";

export const GET_NATIONALITIES_OPT = "GET_NATIONALITIES_OPT";
export const GET_NATIONALITIES_OPT_SUCCESS = "GET_NATIONALITIES_OPT_SUCCESS";
export const GET_NATIONALITIES_OPT_FAIL = "GET_NATIONALITIES_OPT_FAIL";

export const GET_GENDERSCH = "GET_GENDERS";
export const GET_GENDERSCH_SUCCESS = "GET_GENDERS_SUCCESS";
export const GET_GENDERSCH_FAIL = "GET_GENDERS_FAIL";

// export const GET_ADMINISTRATIVE_SUPERVISORS_OPT =
//   "GET_ADMINISTRATIVE_SUPERVISORS_OPT";
// export const GET_ADMINISTRATIVE_SUPERVISORS_OPT_FAIL =
//   "GET_ADMINISTRATIVE_SUPERVISORS_OPT_FAIL";
// export const GET_ADMINISTRATIVE_SUPERVISORS_OPT_SUCCESS =
//   "GET_ADMINISTRATIVE_SUPERVISORS_OPT_SUCCESS";

export const GET_JOB_RANKS_OPT = "GET_JOB_RANKS_OPT";
export const GET_JOB_RANKS_OPT_FAIL = "GET_JOB_RANKS_OPT_FAIL";
export const GET_JOB_RANKS_OPT_SUCCESS = "GET_JOB_RANKS_OPT_SUCCESS";

export const GET_JOB_TITLES_OPT = "GET_JOB_TITLES_OPT";
export const GET_JOB_TITLES_OPT_FAIL = "GET_JOB_TITLES_OPT_FAIL";
export const GET_JOB_TITLES_OPT_SUCCESS = "GET_JOB_TITLES_OPT_SUCCESS";

export const GET_CORPORATE_NODES_OPT = "GET_CORPORATE_NODES_OPT";
export const GET_CORPORATE_NODES_OPT_FAIL = "GET_CORPORATE_NODES_OPT_FAIL";
export const GET_CORPORATE_NODES_OPT_SUCCESS =
  "GET_CORPORATE_NODES_OPT_SUCCESS";

export const GET_COST_CENTERS_OPT = "GET_COST_CENTERS_OPT";
export const GET_COST_CENTERS_OPT_FAIL = "GET_COST_CENTERS_OPT_FAIL";
export const GET_COST_CENTERS_OPT_SUCCESS = "GET_COST_CENTERS_OPT_SUCCESS";

export const GET_PHYSIACL_WORK_LOCATIONS_OPT =
  "GET_PHYSIACL_WORK_LOCATIONS_OPT";
export const GET_PHYSIACL_WORK_LOCATIONS_OPT_FAIL =
  "GET_PHYSIACL_WORK_LOCATIONS_OPT_FAIL";
export const GET_PHYSIACL_WORK_LOCATIONS_OPT_SUCCESS =
  "GET_PHYSIACL_WORK_LOCATIONS_OPT_SUCCESS";

export const GET_ACADEMIC_YEARS_OPT = "GET_ACADEMIC_YEARS_OPT";
export const GET_ACADEMIC_YEARS_OPT_FAIL = "GET_ACADEMIC_YEARS_OPT_FAIL";
export const GET_ACADEMIC_YEARS_OPT_SUCCESS = "GET_ACADEMIC_YEARS_OPT_SUCCESS";

export const GET_COUNTRIES_OPT = "GET_COUNTRIES_OPT";
export const GET_COUNTRIES_OPT_FAIL = "GET_COUNTRIES_OPT_FAIL";
export const GET_COUNTRIES_OPT_SUCCESS = "GET_COUNTRIES_OPT_SUCCESS";

export const GET_CITIES_OPT = "GET_CITIES_OPT";
export const GET_CITIES_OPT_FAIL = "GET_CITIES_OPT_FAIL";
export const GET_CITIES_OPT_SUCCESS = "GET_CITIES_OPT_SUCCESS";

export const GET_STATES_OPT = "GET_STATES_OPT";
export const GET_STATES_OPT_FAIL = "GET_STATES_OPT_FAIL";
export const GET_STATES_OPT_SUCCESS = "GET_STATES_OPT_SUCCESS";

export const GET_EMPLOYEES_NAMES = "GET_EMPLOYEES_NAMES";
export const GET_EMPLOYEES_NAMES_FAIL = "GET_EMPLOYEES_NAMES_FAIL";
export const GET_EMPLOYEES_NAMES_SUCCESS = "GET_EMPLOYEES_NAMES_SUCCESS";
