/* warining */
export const GET_WARNINGS = "GET_WARNINGS"
export const GET_WARNINGS_SUCCESS = "GET_WARNINGS_SUCCESS"
export const GET_WARNINGS_FAIL = "GET_WARNINGS_FAIL"

export const ADD_NEW_WARNING = "ADD_NEW_WARNING"
export const ADD_WARNING_SUCCESS = "ADD_WARNING_SUCCESS"
export const ADD_WARNING_FAIL = "ADD_WARNING_FAIL"

export const UPDATE_WARNING = "UPDATE_WARNING"
export const UPDATE_WARNING_SUCCESS = "UPDATE_WARNING_SUCCESS"
export const UPDATE_WARNING_FAIL = "UPDATE_WARNING_FAIL"

export const DELETE_WARNING = "DELETE_WARNING"
export const DELETE_WARNING_SUCCESS = "DELETE_WARNING_SUCCESS"
export const DELETE_WARNING_FAIL = "DELETE_WARNING_FAIL"

export const GET_WARNING_DELETED_VALUE = "GET_WARNING_DELETED_VALUE"
export const GET_WARNING_DELETED_VALUE_SUCCESS = "GET_WARNING_DELETED_VALUE_SUCCESS"
export const GET_WARNING_DELETED_VALUE_FAIL = "GET_WARNING_DELETED_VALUE_FAIL"